"""Exact-statement generation, candidate-proof hygiene and native kernel runs.

Two proof paths are supported:
  * ``coordinator_template``: the trusted coordinator renders a proof from the
    reduced witness using pinned support lemmas (the M1 calibration path);
  * ``external_file``: a candidate process supplies the proof source; the
    coordinator freezes the Target module first and rejects proofs that do not
    inhabit exactly that statement.
"""
from __future__ import annotations

import os
import platform
import subprocess
from pathlib import Path

from .model import (
    agda_bool,
    agda_nat,
    agda_value,
    apply_ops,
    continuation_from_json,
    observation_mode,
    value_from_json,
)
from .util import (
    MachineOverviewError,
    git_state,
    json_bytes,
    sha256_bytes,
    sha256_file,
    utc_now,
    write_bytes,
    write_json,
    write_text,
)

OPTIONS = "{-# OPTIONS --safe --cubical --guardedness #-}"

FORBIDDEN_MARKERS = (
    "postulate",
    "primitive ",
    "{!!}",
    "{-# TERMINATING #-}",
    "{-# NON_TERMINATING #-}",
    "--type-in-type",
    "--no-positivity-check",
    "--no-termination-check",
    "--no-universe-check",
    "--allow-unsolved-metas",
    "--allow-incomplete-matches",
)

HEADER_IMPORTS = [
    "open import Cubical.Foundations.Prelude",
    "open import Cubical.Data.Bool.Base using (Bool; true; false)",
    "open import Cubical.Data.Bool.Properties using (true≢false; false≢true)",
    "open import Cubical.Data.Nat.Base using (ℕ; zero; suc)",
    "open import PartialityRaceTimeout",
]


def check_proof_hygiene(text: str, origin: str) -> None:
    for marker in FORBIDDEN_MARKERS:
        if marker in text:
            raise MachineOverviewError(f"CANDIDATE_FORBIDDEN_DECLARATION:{origin}:{marker}")
    if "module Proof where" not in text:
        raise MachineOverviewError(f"CANDIDATE_MODULE_NAME_INVALID:{origin}")
    if "Target." not in text:
        raise MachineOverviewError(f"CANDIDATE_DOES_NOT_REFERENCE_TARGET:{origin}")


def _render_context_definitions(ops: list[dict]) -> tuple[list[str], dict[str, str]]:
    lines: list[str] = []
    names: dict[str, str] = {}
    partner_index = 0
    continuation_index = 0
    for op in ops:
        if op["kind"] in ("race_left", "race_right"):
            key = f"partner:{op['partner']}"
            if key not in names:
                name = f"partner{partner_index}"
                partner_index += 1
                lines += [f"{name} : Delay Bool", f"{name} = {agda_value(value_from_json(op['partner']))}", ""]
                names[key] = name
        elif op["kind"] == "bind":
            key = f"continuation:{op['continuation']}"
            if key not in names:
                name = f"cur{continuation_index}"
                continuation_index += 1
                continuation = continuation_from_json(op["continuation"])
                lines += [
                    f"{name} : Bool → Delay Bool",
                    f"{name} true = {agda_value(continuation[True])}",
                    f"{name} false = {agda_value(continuation[False])}",
                    "",
                ]
                names[key] = name
    return lines, names


def render_context_expression(ops: list[dict], names: dict[str, str], base: str) -> str:
    expression = base
    for op in ops:
        if op["kind"] == "race_left":
            partner_name = names["partner:" + str(op["partner"])]
            expression = f"({expression} race {partner_name})"
        elif op["kind"] == "race_right":
            partner_name = names["partner:" + str(op["partner"])]
            expression = f"({partner_name} race {expression})"
        elif op["kind"] == "bind":
            continuation_name = names["continuation:" + str(op["continuation"])]
            expression = f"({expression} bind {continuation_name})"
        elif op["kind"] == "deadline":
            expression = f"(deadline {agda_nat(op['k'])} {expression})"
        else:
            raise MachineOverviewError(f"UNKNOWN_CONTEXT_OP:{op['kind']}")
    return expression


def negative_control_horizon(left: tuple, right: tuple) -> int:
    """A declared deadline that provably cannot separate a result-equivalent pair."""
    indices = [value[1] for value in (left, right) if value[0] == "ret"]
    return max(indices) if indices else 0


def render_target(case: dict, witness: dict) -> str:
    left = value_from_json(witness["pair"]["left"])
    right = value_from_json(witness["pair"]["right"])
    ops = witness["ops"]
    mode = observation_mode(ops)
    definition_lines, names = _render_context_definitions(ops)
    observed_type = "Optional Bool" if mode == "deadline" else "Delay Bool"
    lines = [
        OPTIONS,
        "",
        f"-- Generated by machine_overview for case {case['case_id']} / witness {witness['witness_id']}.",
        "-- This module fixes the exact statement the candidate proof must inhabit;",
        "-- its SHA-256 is recorded before any proof source is accepted.",
        "",
        "module Target where",
        "",
        *HEADER_IMPORTS,
        "",
        "p : Delay Bool",
        f"p = {agda_value(left)}",
        "",
        "q : Delay Bool",
        f"q = {agda_value(right)}",
        "",
        *definition_lines,
        f"left : {observed_type}",
        f"left = {render_context_expression(ops, names, 'p')}",
        "",
        f"right : {observed_type}",
        f"right = {render_context_expression(ops, names, 'q')}",
        "",
        "-- Non-separating deadline instance used by the negative control.",
        "control-left : Optional Bool",
        f"control-left = deadline {agda_nat(negative_control_horizon(left, right))} p",
        "",
        "control-right : Optional Bool",
        f"control-right = deadline {agda_nat(negative_control_horizon(left, right))} q",
        "",
    ]
    return "\n".join(lines)


def render_proof(case: dict, witness: dict) -> str:
    left = value_from_json(witness["pair"]["left"])
    right = value_from_json(witness["pair"]["right"])
    ops = witness["ops"]
    mode = observation_mode(ops)
    observed_left = value_from_json(witness["left_observation"])
    observed_right = value_from_json(witness["right_observation"])
    lines = [
        OPTIONS,
        "",
        f"-- Coordinator-templated proof for {case['case_id']} / {witness['witness_id']}.",
        "-- The proof only instantiates pinned support lemmas with computable facts.",
        "",
        "module Proof where",
        "",
        *HEADER_IMPORTS,
        "open import Target",
        "open import MVSupport",
        "",
        "equiv : Target.p ≈ Target.q",
    ]
    if left[0] == "omega" and right[0] == "omega":
        lines.append("equiv = MVSupport.≈-same-omega")
    elif left[0] == "ret" and right[0] == "ret" and left[2] == right[2]:
        lines.append(
            f"equiv = MVSupport.≈-same-ret {agda_nat(left[1])} {agda_nat(right[1])} {agda_bool(left[2])}"
        )
    else:
        raise MachineOverviewError("EQUIVALENCE_TEMPLATE_UNSUPPORTED")

    lines += ["", f"gap : {'¬ (Target.left ≡ Target.right)' if mode == 'deadline' else '¬ (Target.left ≈ Target.right)'}"]
    if mode == "deadline":
        if observed_left[0] == "some" and observed_right[0] == "none":
            lines.append(f"gap e = MVSupport.some-neq-none {agda_bool(observed_left[1])} e")
        elif observed_left[0] == "none" and observed_right[0] == "some":
            lines.append(f"gap e = MVSupport.none-neq-some {agda_bool(observed_right[1])} e")
        elif observed_left[0] == "some" and observed_right[0] == "some" and observed_left[1] != observed_right[1]:
            lemma = "true≢false" if observed_left[1] else "false≢true"
            lines.append(
                f"gap e = MVSupport.some-neq-some {agda_bool(observed_left[1])} {agda_bool(observed_right[1])} {lemma} e"
            )
        else:
            raise MachineOverviewError("DEADLINE_GAP_TEMPLATE_UNSUPPORTED")
    else:
        if observed_left[0] == "ret" and observed_right[0] == "ret" and observed_left[2] != observed_right[2]:
            # We exhibit Conv right a (a = left value), which reduces to c ≡ a
            # with c = right value; the lemma must refute c ≡ a.
            lemma = "true≢false" if observed_right[2] else "false≢true"
            lines.append(
                f"gap h = {lemma} (⇔-fwd (h {agda_bool(observed_left[2])}) refl)"
            )
        elif observed_left[0] == "ret" and observed_right[0] == "omega":
            lines.append(
                f"gap h = lower (⇔-fwd (h {agda_bool(observed_left[2])}) refl)"
            )
        elif observed_left[0] == "omega" and observed_right[0] == "ret":
            lines.append(
                f"gap h = lower (⇔-bwd (h {agda_bool(observed_right[2])}) refl)"
            )
        else:
            raise MachineOverviewError("DELAY_GAP_TEMPLATE_UNSUPPORTED")
    lines.append("")
    return "\n".join(lines)


def render_verify(witness: dict) -> str:
    mode = observation_mode(witness["ops"])
    claim = "¬ (Target.left ≡ Target.right)" if mode == "deadline" else "¬ (Target.left ≈ Target.right)"
    lines = [
        OPTIONS,
        "",
        "-- Coordinator-owned entry module: it must only accept a proof that",
        "-- inhabits exactly the frozen Target statement.",
        "",
        "module Verify where",
        "",
        *HEADER_IMPORTS,
        "open import Target",
        "open import Proof",
        "",
        "check-equiv : Target.p ≈ Target.q",
        "check-equiv = Proof.equiv",
        "",
        f"check-gap : {claim}",
        "check-gap = Proof.gap",
        "",
    ]
    return "\n".join(lines)


def render_controls(witness: dict) -> str:
    mode = observation_mode(witness["ops"])
    claim = "¬ (Target.left ≡ Target.right)" if mode == "deadline" else "¬ (Target.left ≈ Target.right)"
    lines = [
        OPTIONS,
        "",
        "-- Positive controls: a completion-preserving consumer does not separate",
        "-- the same result-equivalent pair, while the declared consumer does.",
        "",
        "module Controls where",
        "",
        *HEADER_IMPORTS,
        "open import Target",
        "open import Proof",
        "",
        "keeping : Bool → Delay Bool",
        "keeping _ = ret zero true",
        "",
        "preserved : (Target.p bind keeping) ≈ (Target.q bind keeping)",
        "preserved = bind-cong Target.p Target.q keeping keeping Proof.equiv (λ a → ≈-refl (keeping a))",
        "",
        f"not-preserved : {claim}",
        "not-preserved = Proof.gap",
        "",
    ]
    return "\n".join(lines)


def render_falsify(witness: dict) -> str:
    return "\n".join([
        OPTIONS,
        "",
        "-- Negative control: this instance does NOT separate the pair, so the",
        "-- kernel must reject the following claim (expected non-zero exit).",
        "",
        "module Falsify where",
        "",
        *HEADER_IMPORTS,
        "open import Target",
        "open import MVSupport",
        "",
        "bad : ¬ (Target.control-left ≡ Target.control-right)",
        "bad e = MVSupport.some-neq-none true e",
        "",
    ])


def _kernel_environment(toolchain: dict) -> dict[str, str]:
    cache = toolchain["runtime_cache"]
    env = dict(os.environ)
    for key in ("xdg_data_home", "xdg_config_home", "tmpdir"):
        Path(cache[key]).mkdir(parents=True, exist_ok=True)
    env["XDG_DATA_HOME"] = cache["xdg_data_home"]
    env["XDG_CONFIG_HOME"] = cache["xdg_config_home"]
    env["TMPDIR"] = cache["tmpdir"]
    return env


def kernel_command(repo_root: Path, toolchain: dict, include_dirs: list[str], entry: str) -> list[str]:
    agda = toolchain["agda"]
    cubical = toolchain["cubical_library"]
    library_registry = toolchain["project_library_registry"]
    command = [
        agda["local_binary"],
        "--ignore-interfaces",
        f"--library-file={repo_root / library_registry}",
        "-l",
        f"cubical-{cubical['version']}",
    ]
    for include in include_dirs:
        command += ["-i", include]
    command.append(entry)
    return command


def run_kernel(
    repo_root: Path,
    run_dir: Path,
    *,
    label: str,
    toolchain: dict,
    include_dirs: list[str],
    entry: str,
    expect_success: bool,
) -> dict:
    target_dir = run_dir / "kernel" / label
    command = kernel_command(repo_root, toolchain, include_dirs, entry)
    environment = _kernel_environment(toolchain)
    started = utc_now()
    result = subprocess.run(command, cwd=repo_root, capture_output=True, check=False, env=environment)
    completed = utc_now()
    receipt = {
        "label": label,
        "command_argv": command,
        "cwd": str(repo_root),
        "entry": entry,
        "expect_success": expect_success,
        "exit_code": result.returncode,
        "stdout_bytes": len(result.stdout),
        "stdout_sha256": sha256_bytes(result.stdout),
        "stderr_bytes": len(result.stderr),
        "stderr_sha256": sha256_bytes(result.stderr),
        "started_at_utc": started,
        "completed_at_utc": completed,
        "environment": "\n".join([
            f"platform={platform.platform()}",
            f"python={platform.python_version()}",
            f"agda_binary={toolchain['agda']['local_binary']}",
            f"agda_binary_sha256={sha256_file(Path(toolchain['agda']['local_binary']))}",
            "dependency_policy=pinned Agda release asset, pinned Cubical release tree, no network",
            "",
        ]),
    }
    if expect_success:
        receipt["expectation_met"] = result.returncode == 0
        receipt["status"] = "KERNEL_ACCEPTED" if result.returncode == 0 else "KERNEL_REJECTED_UNEXPECTED"
    else:
        receipt["expectation_met"] = result.returncode != 0
        receipt["status"] = "KERNEL_REJECTED_AS_EXPECTED" if result.returncode != 0 else "KERNEL_ACCEPTED_UNEXPECTED"
    write_bytes(target_dir / "stdout.txt", result.stdout)
    write_bytes(target_dir / "stderr.txt", result.stderr)
    write_text(target_dir / "environment.txt", receipt["environment"] + "\n")
    write_json(target_dir / "command.json", {
        "command_argv": command,
        "cwd": str(repo_root),
        "exit_code": result.returncode,
    })
    return receipt


def verify_witness(
    repo_root: Path,
    *,
    run_id: str,
    case_path: Path,
    case: dict,
    witness: dict,
    profile_report: dict,
    toolchain: dict,
    registry: dict,
    run_dir: Path,
    proof_origin: str = "coordinator_template",
    proof_text: str | None = None,
    replay: bool = True,
) -> dict:
    started = utc_now()
    # All rejection paths below run before any side effect: a rejected candidate
    # must not consume a run id or leave a partial receipt behind.
    target_text = render_target(case, witness)
    target_bytes = target_text.encode("utf-8")
    target_sha = sha256_bytes(target_bytes)
    if case.get("target_text_hash") and case["target_text_hash"] != target_sha:
        raise MachineOverviewError("TARGET_CHANGED")

    if proof_text is None:
        proof_text = render_proof(case, witness)
    check_proof_hygiene(proof_text, proof_origin)

    run_dir.mkdir(parents=True, exist_ok=False)
    generated = run_dir / "generated"
    generated.mkdir(parents=True)

    write_bytes(generated / "Target.agda", target_bytes)
    write_bytes(generated / "Proof.agda", proof_text.encode("utf-8"))
    write_bytes(generated / "Verify.agda", render_verify(witness).encode("utf-8"))
    write_bytes(generated / "Controls.agda", render_controls(witness).encode("utf-8"))
    write_bytes(generated / "Falsify.agda", render_falsify(witness).encode("utf-8"))

    include_dirs = [
        "machine-overview/formal",
        "HoTT/formal/partiality-race-timeout",
        "machine-overview/runs/{}/generated".format(run_id),
    ]
    kernel_receipts: list[dict] = []
    kernel_receipts.append(run_kernel(
        repo_root, run_dir, label="verify", toolchain=toolchain,
        include_dirs=include_dirs, entry=f"machine-overview/runs/{run_id}/generated/Verify.agda",
        expect_success=True,
    ))
    kernel_receipts.append(run_kernel(
        repo_root, run_dir, label="controls", toolchain=toolchain,
        include_dirs=include_dirs, entry=f"machine-overview/runs/{run_id}/generated/Controls.agda",
        expect_success=True,
    ))
    kernel_receipts.append(run_kernel(
        repo_root, run_dir, label="negative-control", toolchain=toolchain,
        include_dirs=include_dirs, entry=f"machine-overview/runs/{run_id}/generated/Falsify.agda",
        expect_success=False,
    ))
    if replay:
        replay_receipt = run_kernel(
            repo_root, run_dir, label="verify-replay", toolchain=toolchain,
            include_dirs=include_dirs, entry=f"machine-overview/runs/{run_id}/generated/Verify.agda",
            expect_success=True,
        )
        first = kernel_receipts[0]
        replay_receipt["replay_match"] = (
            replay_receipt["exit_code"] == first["exit_code"]
            and replay_receipt["stdout_sha256"] == first["stdout_sha256"]
            and replay_receipt["stderr_sha256"] == first["stderr_sha256"]
        )
        kernel_receipts.append(replay_receipt)

    verify_ok = all(
        item["expectation_met"] for item in kernel_receipts if item["label"] in ("verify", "controls", "negative-control")
    )
    if replay:
        verify_ok = verify_ok and bool(kernel_receipts[-1].get("replay_match"))

    receipt = {
        "schema_version": "machine-overview-verify-run/v1",
        "run_id": run_id,
        "kind": "verify",
        "case_id": case["case_id"],
        "case_revision": case["revision"],
        "case_pointer": str(case_path),
        "witness_id": witness["witness_id"],
        "started_at_utc": started,
        "completed_at_utc": utc_now(),
        "coordinator_version": registry["coordinator_version"],
        "profile": {
            "profile_id": profile_report["profile_id"],
            "profile_status": profile_report["status"],
            "toolchain_ref": profile_report["toolchain_ref"],
        },
        "proof_origin": proof_origin,
        "toolchain_identity": {
            "agda_binary": toolchain["agda"]["local_binary"],
            "agda_binary_sha256": sha256_file(Path(toolchain["agda"]["local_binary"])),
            "agda_version": toolchain["agda"]["version"],
            "cubical_library_file": toolchain["cubical_library"]["library_file"],
            "cubical_library_file_sha256": sha256_file(Path(toolchain["cubical_library"]["library_file"])),
            "cubical_version": toolchain["cubical_library"]["version"],
            "cubical_tree_sha256": toolchain["cubical_library"]["tree_sha256"],
        },
        "generated_sources": {
            name: {"sha256": sha256_file(generated / name), "bytes": (generated / name).stat().st_size}
            for name in ("Target.agda", "Proof.agda", "Verify.agda", "Controls.agda", "Falsify.agda")
        },
        "target_text_hash": target_sha,
        "statement": {
            "pair": witness["pair"],
            "ops": witness["ops"],
            "observation_mode": witness["observation_mode"],
            "left_observation": witness["left_observation"],
            "right_observation": witness["right_observation"],
            "separation_kind": witness["separation_kind"],
        },
        "kernel_runs": kernel_receipts,
        "status": "NATIVE_CHECKED_CALIBRATION_INSTANCE" if verify_ok else "NATIVE_CHECK_FAILED",
        "claim_relation": {
            "kind": "calibration_instance_of_known_mechanism",
            "related_claims": case.get("claim_refs", []),
            "registers_new_claim": False,
            "note": "Exploration receipts stay under machine-overview/runs; "
                    "they do not enter HoTT/CLAIM_EVIDENCE_MATRIX.md.",
        },
        "git": git_state(repo_root),
    }
    write_json(run_dir / "RUN.json", receipt)
    return receipt
