#!/usr/bin/env python3
"""Checkpoint P18 branch switch and route P19."""
from __future__ import annotations
import argparse,hashlib,importlib.util,json,re,subprocess,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];OUT=Path(__file__).resolve().parent;SID='S-RES-20260921-ASTRA-P18-FIFTH-SUCCESSOR-DISCOVERY';BASE=f'.codex/research/hott/sessions/{SID}/';PLAN='R-HOTT-FOUR-TRACK-PLAN-20260921';ABX='R-ABX-ACTION-20260921';P17='R-P17-CUBICAL-HOTT-CAUCHY-REALS-CORPUS-20260921';P18='R-P18-FIFTH-SUCCESSOR-DISCOVERY-20260921'
REP='audit/p18-fifth-successor-discovery-20260921/P18-FIFTH-SUCCESSOR-DISCOVERY-REPORT.md';VER='audit/p18-fifth-successor-discovery-20260921/verify_p18_fifth_successor_discovery.py';REC='audit/p18-fifth-successor-discovery-20260921/P18-FIFTH-SUCCESSOR-DISCOVERY-VERIFICATION.json';SCR='audit/p18-fifth-successor-discovery-20260921/checkpoint_p18_fifth_successor_discovery.py';S=(REP,VER,REC,SCR,'goal.md','goal-3.md','feature-list.md','rulings.md','HoTT后续研究总体方案.md','HoTT后续研究总体方案/003 - 分支顺序、准入与停止条件.md','HoTT后续研究总体方案/005 - 当前第一步与交接.md','audit/p6-origin-structure-stratified-20260921/P6-ORIGIN-STRUCTURE-STRATIFIED-COMPARISON-REPORT.md','audit/p7-origin-directed-diagram-spec-20260921/P7-ORIGIN-DIRECTED-DIAGRAM-SPEC-REPORT.md')
def h(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def rw(t,p,v):
 a=t.splitlines()
 for i,x in enumerate(a):
  if x.startswith(p):a[i]=v;return '\n'.join(a)+'\n'
 raise AssertionError(p)
def audit(c):
 hs=re.findall(r'^### (KC-\d+) · .*? · (.+)$',(ROOT/'核心认知.md').read_text(),re.M);assert len(hs)==46;s=f'# {SID} 核心认知回评\n\n{c["generation"]}；46 条。\n\n- core_change: NO\n- direction_change: P18_SWITCH_TO_P1_OBJECT_THEORY_P19_NEXT\n- panorama_change: P3_CONTINUATION_REJECTED_AS_SAME_CLASS\n- essay_change: NO\n- update_decision: P18 stops repeated P3 scanning and selects an object-theory kernelization task.\n- cross_conflicts: no object-theory theorem exists yet.\n- unresolved: P19, actual K and HoTT defect remain open.\n- writer_compatibility: G-V5-SESSION-AUDIT-SHARD-WRITE-GAP-001.\n\n| KC | 主题 | relation | 本单元判断 | 证据、反证条件 |\n|---|---|---|---|---|\n'
 for k,t in hs:s+=f'| `{k}` | {t} | NOT_TOUCHED | P18 branch switch only. | `{REP}`；P19可改变。 |\n'
 return s+'\n## 波次定位\n\nP18从P3切到P1；P19最小对象理论。\n'
def main():
 a=argparse.ArgumentParser();a.add_argument('--apply',action='store_true');x=a.parse_args();subprocess.check_call([sys.executable,'-B',VER,'--write'],cwd=ROOT);assert all((ROOT/q).is_file()for q in S);sp=importlib.util.spec_from_file_location('r',ROOT/'.codex/tools/cognition_runtime.py');r=importlib.util.module_from_spec(sp);sp.loader.exec_module(r);st=json.loads((ROOT/r.STATE).read_text());assert st['revision']==237 and st['latest_session']=='S-RES-20260921-ASTRA-P17-CUBICAL-CAUCHY-REALS';head=json.loads((ROOT/r.HEAD).read_text());assert all(h(ROOT/q)==v for q,v in head['tracked'].items());pl=r.plan(ROOT,profile='research',task_ids=[PLAN]);(OUT/'P18-CHECKPOINT-PLAN.json').write_bytes(r.dump(pl));st['revision']=238;st['latest_session']=SID
 for q in(PLAN,ABX,P17):
  v=st['records'][q];v['related_records']=list(dict.fromkeys(v.get('related_records',[])+[P18,SID]));v['revalidation']=v.get('revalidation','')+' Revision238 records P18 branch switch; previous scope unchanged.'
 p=st['records'][PLAN];p.update(status='four_track_p18_switch_to_p1_object_theory_p19_next',evidence_status='P3_CONTINUATION_REJECTED_AS_SAME_CLASS / SWITCH_TO_P1_OBJECT_THEORY / P19_ORIGIN_DIRECTED_DIAGRAM_KERNELIZATION_NEXT / GOAL_ACTIVE');p['full_sources']=list(dict.fromkeys(p.get('full_sources',[])+list(S)));p['source_hashes'].update({q:h(ROOT/q)for q in p['full_sources']if(ROOT/q).is_file()})
 st['records'][P18]={'kind':'result','path':REP,'lifecycle_status':'CURRENT','evidence_status':'P3_CONTINUATION_REJECTED_AS_SAME_CLASS / SWITCH_TO_P1_OBJECT_THEORY / ORIGIN_DIRECTED_DIAGRAM_KERNELIZATION_CANDIDATE / P19_NOT_STARTED / NO_NEW_HOTT_DEFECT_CLAIM','status':'complete_with_scope_p19_next','depends_on':[],'related_records':[PLAN,ABX,P17],'full_sources':list(S),'source_hashes':{q:h(ROOT/q)for q in S},'scope':'P18 branch selection only, no object theory theorem or K.'};st['records'][SID]={'kind':'session','path':BASE+'SESSION.md','lifecycle_status':'HISTORICAL','evidence_status':'P18_BRANCH_SWITCH_CHECKPOINTED_WITH_SCOPE','status':'complete_with_scope','depends_on':[],'related_records':[P18,PLAN,ABX],'full_sources':[BASE+n for n in('SESSION.md','RUNS.json','CORE_COGNITION_AUDIT.md')]}
 st['execution_control'].update(status='FOUR_TRACK_P18_SWITCH_TO_P1_OBJECT_THEORY_P19_NEXT',current_phase='PHASE_2_P18_COMPLETE_P19_ORIGIN_DIRECTED_DIAGRAM_KERNELIZATION_NEXT',second_phase_status='P3_PAUSED_SAME_CLASS_P1_P19_NEXT',last_checkpoint_session=SID,checkpoint_result=f'.codex/cognition/checkpoints/{SID}/result.json',next_minimal_verification='P19-ORIGIN-DIRECTED-DIAGRAM-KERNELIZATION-001. Select the native HoTT/cubical backend already present in local assets, freeze its exact record/Σ/Path/HIT support, and formalize the smallest OriginDirectedDiagram-style structure plus a bare forgetful map and positive/negative controls. Do not claim non-representability or a HoTT defect; if no new checkable obligation is possible, return RESTATEMENT_ONLY.')
 st['projection']['status']='FOUR_TRACK_P18_SWITCH_TO_P1_OBJECT_THEORY / NEXT_P19_ORIGIN_DIRECTED_DIAGRAM_KERNELIZATION / GOAL_ACTIVE / NO_NEW_HOTT_DEFECT_CLAIM'
 dr='| `DIR-U-HOTT-FOUR-TRACK` | P18从P3切换至P1对象理论 | 反漂移规则 | `P3_PAUSED / P19_NEXT / GOAL_ACTIVE` | `PARADOX_DISCOVERY` | P18 | P19最小对象形式化 | P18 report；revision238 |';ar='| `DIR-U-ABX-ORIGINAL-CIRCLE` | ABX P18分支切换 | P18 | `P3_PAUSED_SAME_CLASS / P19_NEXT` | `PARADOX_DISCOVERY` | P18 | P19对象理论 | P18 report；revision238 |';pr='| `OUT-HOTT-FOUR-TRACK-PLAN` | P18反漂移分支切换 | `DIR-U-HOTT-FOUR-TRACK` | P15/P17+P6/P7 | `SWITCH_TO_P1 / P19_NEXT` | 避免重复consumer扫描 | 不证明K或缺陷 | P18 report；revision238 |';ap='| `OUT-ABX-ACTION-INTAKE` | ABX P18切换P1 | `DIR-U-ABX-ORIGINAL-CIRCLE` | P6/P7对象规格 | `P19_NEXT` | 结构对象待检查 | 不证明原M/N桥 | P18 report；revision238 |';mem='P18已完成：P15/P17同类结构防御后停止P3扩展，切换到P1对象理论。当前P19将最小化OriginDirectedDiagram结构、forgetful map和正负控制；不预设不可表达性。入口：`audit/p18-fifth-successor-discovery-20260921/P18-FIFTH-SUCCESSOR-DISCOVERY-REPORT.md`；revision238。';fr='- P18已完成：停止同类P3 consumer扫描，切至P1对象理论。P19最小化OriginDirectedDiagram和forgetful map；不预设缺陷。入口：`audit/p18-fifth-successor-discovery-20260921/P18-FIFTH-SUCCESSOR-DISCOVERY-REPORT.md`。';rs='当前 active goal 在P18后继续：P19=ORIGIN_DIRECTED_DIAGRAM_KERNELIZATION，核原生后端能力并形式化最小结构、bare forgetful map和正负控制；无新可检查义务则RESTATEMENT_ONLY。入口：`audit/p18-fifth-successor-discovery-20260921/P18-FIFTH-SUCCESSOR-DISCOVERY-REPORT.md`；revision238。'
 fs=[]
 for rel in list(r.MUTABLE)+list(r.mutable_shard_paths(ROOT)):
  raw=(ROOT/rel).read_bytes();t=raw.decode()
  if rel==r.STATE:t=r.dump(st).decode()
  elif rel==r.DIRECTION:t=t.replace('source_state_revision: 237','source_state_revision: 238',1).replace('projection_generation: 20260921-direction-237','projection_generation: 20260921-direction-238',1).replace('semantic_status: FOUR_TRACK_P17_EXPLICIT_CAUCHY_APPROXIMATION_DEFENSE_P18_NEXT','semantic_status: FOUR_TRACK_P18_SWITCH_TO_P1_OBJECT_THEORY_P19_NEXT',1)
  elif rel==r.PANORAMA:t=t.replace('source_state_revision: 237','source_state_revision: 238',1).replace('projection_generation: 20260921-outcome-237','projection_generation: 20260921-outcome-238',1).replace('semantic_status: FOUR_TRACK_P17_EXPLICIT_CAUCHY_APPROXIMATION_DEFENSE_P18_NEXT','semantic_status: FOUR_TRACK_P18_SWITCH_TO_P1_OBJECT_THEORY_P19_NEXT',1)
  elif rel=='方向追踪/002 - 治理与用户方向.md':t=rw(rw(t,'| `DIR-U-HOTT-FOUR-TRACK` |',dr),'| `DIR-U-ABX-ORIGINAL-CIRCLE` |',ar)
  elif rel=='全景视野/003 - 当前机器证明包与原生重放.md':t=rw(rw(t,'| `OUT-HOTT-FOUR-TRACK-PLAN` |',pr),'| `OUT-ABX-ACTION-INTAKE` |',ap)
  elif rel=='MEMORY/001 - 当前执行队列.md':t=rw(t,'P17已完成：',mem)
  elif rel=='MEMORY/003 - 当前验证状态与顺序日志.md':t+='\nS-RES-20260921-ASTRA-P18-FIFTH-SUCCESSOR-DISCOVERY：P18切换P1对象理论，P19；revision238。\n'
  elif rel==r.PREFIX+'FRONTIER.md':t=rw(t,'- P17已完成：',fr)
  elif rel==r.PREFIX+'RESUME.md':t=rw(t,'当前 active goal 在P17后继续：',rs)
  fs.append({'path':rel,'expected_sha256':r.sha(raw),'text':t})
 sess=f'# {SID}\n\n- tier: T3 P18 branch switch\n- status: COMPLETED_WITH_SCOPE / P19_NEXT\n';runs={'schema_version':'hott-session-runs/v1','session_id':SID,'primary_runs':[{'kind':'P18 anti-drift branch decision','result':'PASS_WITH_SCOPE','mathematics':'NO_NEW_KERNEL_RUN'}],'new_math_claims':[],'new_kernel_replay':False}
 for n,t in(('SESSION.md',sess),('RUNS.json',r.dump(runs).decode()),('CORE_COGNITION_AUDIT.md',audit(st['current_core']))):fs.append({'path':BASE+n,'expected_sha256':None,'text':t})
 pay={'schema_version':'cognition-checkpoint/v1','session_id':SID,'load_profile':'research','task_ids':[PLAN],'authorization':'用户已授权按goal-3持续推进、公开/本地侦察和checkpoint；不启动Sub Agent、不push、不发布。','files':fs};(OUT/'P18-checkpoint-payload.json').write_bytes(r.dump(pay));z=r.checkpoint(ROOT,pl['snapshot'],pay,apply=x.apply);(OUT/('P18-checkpoint-apply.json'if x.apply else 'P18-checkpoint-dry-run.json')).write_bytes(r.dump(z));print(json.dumps({k:v for k,v in z.items()if k!='paths'},ensure_ascii=False))
if __name__=='__main__':main()
