#!/usr/bin/env python3
"""Checkpoint P29's one-rung reflection control and route P30 crosswalk."""
from __future__ import annotations
import argparse,hashlib,importlib.util,json,re,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];OUT=Path(__file__).resolve().parent;SID='S-RES-20260921-ASTRA-P29-CLIMBER-CORPUS';BASE=f'.codex/research/hott/sessions/{SID}/';PLAN='R-HOTT-FOUR-TRACK-PLAN-20260921';P28='R-P28-CFTT-STAGED-QUOTATION-SPLICE-UNSTAGING-CORPUS-20260921';P29='R-P29-CLIMBER-OBJECT-PROVABILITY-SOUNDNESS-CORPUS-20260921';DIR='audit/p29-climber-object-provability-soundness-corpus-20260921';SOURCES=(f'{DIR}/P29-CLIMBER-OBJECT-PROVABILITY-SOUNDNESS-CORPUS-REPORT.md',f'{DIR}/P29-CLIMBER-SOURCE-FREEZE.json',f'{DIR}/run_p29_climber.py',f'{DIR}/runs/20260921-P29-CLIMBER-BUILD-SMOKE-01/RUN.json',f'{DIR}/verify_p29_climber_object_provability_soundness_corpus.py',f'{DIR}/P29-CLIMBER-OBJECT-PROVABILITY-SOUNDNESS-CORPUS-VERIFICATION.json')
def h(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def rt():
 s=importlib.util.spec_from_file_location('r',ROOT/'.codex/tools/cognition_runtime.py');assert s and s.loader;m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return m
def ed():
 sys.path.insert(0,str(ROOT/'scripts/audit'));import projection_edit;return projection_edit
def audit(core):
 rows=re.findall(r'^### (KC-\d+) · .*? · (.+)$',(ROOT/'核心认知.md').read_text(),re.M);assert len(rows)==46
 x=f'# {SID} 核心认知回评\n\n{core["generation"]}；46 条；兼容单文件审计登记 `G-V5-SESSION-AUDIT-SHARD-WRITE-GAP-001`。\n\n- core_change: NO\n- direction_change: P29 generic reflection control complete; P30 HoTT obligation crosswalk next.\n- panorama_change: object prov/rung and metalanguage soundness boundary recorded.\n- essay_change: NO\n- update_decision: avoid more generic prov scans; map exact obligations to HoTT-specific assets.\n- cross_conflicts: no HoTT defect or same-theory global self-validation established.\n- unresolved: P30 crosswalk and future HoTT-specific source selection.\n- writer_compatibility: G-V5-SESSION-AUDIT-SHARD-WRITE-GAP-001.\n\n| KC | 主题 | relation | 本单元判断 | 证据、反证条件 |\n|---|---|---|---|---|\n'
 for kc,title in rows:
  rel='DEEPENED' if kc in {'KC-000025','KC-000026','KC-000027','KC-000028','KC-000029','KC-000035','KC-000036','KC-000041','KC-000043','KC-000044','KC-000045','KC-000046'} else 'NOT_TOUCHED'
  x+=f'| `{kc}` | {title} | `{rel}` | '+('P29给出分层reflection的编译正控制。' if rel=='DEEPENED' else '本单元未直接检验该用户原文。')+' | P29 report；P30交叉表可更新。 |\n'
 return x+'\n## 波次定位\n\nP29完成generic strongest control；P30把其明确义务映射到现有HoTT assets，防止后续把generic control误称HoTT instance。\n'
def main():
 ap=argparse.ArgumentParser();ap.add_argument('--apply',action='store_true');a=ap.parse_args();r=rt();e=ed();assert all((ROOT/x).is_file() for x in SOURCES);st=json.loads((ROOT/r.STATE).read_text());assert st['revision']==245 and st['latest_session']=='S-RES-20260921-ASTRA-P28-CFTT-CORPUS';hd=json.loads((ROOT/r.HEAD).read_text());assert all(h(ROOT/p)==v for p,v in hd['tracked'].items());pl=r.plan(ROOT,profile='research',task_ids=[PLAN]);(OUT/'P29-CHECKPOINT-PLAN.json').write_bytes(r.dump(pl));st['revision']=246;st['latest_session']=SID
 p=st['records'][PLAN];p['related_records']=list(dict.fromkeys(p.get('related_records',[])+[P29,SID]));p['status']='four_track_p3_paused_p1_expression_p4_not_triggered_p22_parked_p30_hott_reflection_crosswalk_next';p['evidence_status']='P3_PAUSED_SAME_CLASS / P1_MINIMAL_EXPRESSIBILITY_POSITIVE_CONTROL / P4_NOT_TRIGGERED_BY_TRANSLATION_GAP_ALONE / P22_GUARDED_BRIDGE_PARKED / P29_GENERIC_REFLECTION_CONTROL / P30_HOTT_REFLECTION_OBLIGATION_CROSSWALK_NEXT / GOAL_ACTIVE';p['full_sources']=list(dict.fromkeys(p.get('full_sources',[])+list(SOURCES)));p['source_hashes'].update({x:h(ROOT/x) for x in p['full_sources'] if (ROOT/x).is_file()});p['revalidation']=p.get('revalidation','')+' Revision246 records P29 Climber generic reflection control and routes P30 HoTT obligation crosswalk; P28 scope unchanged.'
 st['records'][P29]={'kind':'result','path':SOURCES[0],'lifecycle_status':'CURRENT','evidence_status':'CLOSE_WITH_SCOPE / OBJECT_PROVABILITY_AND_ONE_RUNG_REFLECTION_CONFIRMED / METALANGUAGE_SOUNDNESS_AND_LEVEL_STRATIFICATION_EXPLICIT / NOT_HOTT_AND_NOT_SAME_THEORY_GLOBAL_SELF_VALIDATION / P30_HOTT_REFLECTION_OBLIGATION_CROSSWALK_SELECTED / NO_NEW_HOTT_DEFECT_CLAIM','status':'complete_with_scope','depends_on':[],'related_records':[PLAN,P28,SID],'full_sources':list(SOURCES),'source_hashes':{x:h(ROOT/x) for x in SOURCES},'scope':'Fixed propositional Lean artifact; not an HoTT instance or global self-validation theorem.'}
 st['records'][SID]={'kind':'session','path':BASE+'SESSION.md','lifecycle_status':'HISTORICAL','evidence_status':'P29_CHECKPOINTED_WITH_SCOPE','status':'complete_with_scope','depends_on':[],'related_records':[PLAN,P28,P29],'full_sources':[BASE+x for x in ('SESSION.md','RUNS.json','CORE_COGNITION_AUDIT.md')]}
 st['execution_control'].update({'status':'FOUR_TRACK_P3_PAUSED_P1_EXPRESSIBLE_P4_NOT_TRIGGERED_P22_PARKED_P30_HOTT_REFLECTION_CROSSWALK_NEXT','current_phase':'PHASE_2_P29_GENERIC_REFLECTION_CONTROL_P30_HOTT_OBLIGATION_CROSSWALK_NEXT','second_phase_status':'P3_PAUSED_P1_POSITIVE_CONTROL_P4_NOT_TRIGGERED_GUARD_PARKED_P30_NEXT','last_checkpoint_session':SID,'checkpoint_result':f'.codex/cognition/checkpoints/{SID}/result.json','next_minimal_verification':'P30-HOTT-REFLECTION-OBLIGATION-CROSSWALK-001. Map P29 six reflection obligations to existing version-pinned HoTT/HoTT-related sources and P24-P28 assets. Freeze exact calculus, object syntax, provability relation, reflection consumer, meta-soundness owner, rung index and same-task usage. Conduct local/historical reconnaissance and judge whether a fresh public search can change the selected next source. Do not call generic provability control a HoTT instance.'});st['projection']['status']='FOUR_TRACK_P3_PAUSED_P1_EXPRESSIBLE_P4_NOT_TRIGGERED_GUARD_PARKED / P29_GENERIC_REFLECTION_CONTROL / NEXT_P30_HOTT_OBLIGATION_CROSSWALK / GOAL_ACTIVE / NO_NEW_HOTT_DEFECT_CLAIM'
 mem=e.load(ROOT,'MEMORY.md');dire=e.load(ROOT,'方向追踪.md');pan=e.load(ROOT,'全景视野.md');essay=e.load(ROOT,'扩展认知.md')
 old='P28 已核对 CFTT staging source：实际quote/splice/unstaging合同存在，但Agda supplement是postulated HOAS，generativity用primTrustMe，不构成对象provability/self-validation。下一=P29：固定 climber@`6994d29dda860c3a82de207b1f39ea89526f61c9`审计object `prov`和soundness gate；P3/P1/P4/Guard继续停放。入口：`audit/p28-cftt-staged-quotation-splice-unstaging-corpus-20260921/P28-CFTT-STAGED-QUOTATION-SPLICE-UNSTAGING-CORPUS-REPORT.md`；revision245。'
 new='P29 已编译核对 Climber：object `prov`、RFN(T₀)与Con(T₀)一阶阶梯成立，但每一级soundness/interpretation属于Lean元语言，且非HoTT。下一=P30：以P29六义务逐项对照现有HoTT资产并选择下一专属来源；P3/P1/P4/Guard继续停放。入口：`audit/p29-climber-object-provability-soundness-corpus-20260921/P29-CLIMBER-OBJECT-PROVABILITY-SOUNDNESS-CORPUS-REPORT.md`；revision246。'
 e.replace_in_shard(mem,'MEMORY/001 - 当前执行队列.md',old,new);e.append_to_shard(mem,'MEMORY/003 - 当前验证状态与顺序日志.md','\nS-RES-20260921-ASTRA-P29-CLIMBER-CORPUS：Climber object prov/RFN/Con one-rung经Lean build/smoke复核，meta soundness分层；P30 HoTT义务交叉表next；revision246。\n')
 e.replace_in_index(dire,'source_state_revision: 245','source_state_revision: 246');e.replace_in_index(dire,'projection_generation: 20260921-direction-245','projection_generation: 20260921-direction-246');e.replace_in_index(dire,'semantic_status: FOUR_TRACK_P28_CFTT_STAGING_SCOPED_P29_CLIMBER_NEXT','semantic_status: FOUR_TRACK_P29_GENERIC_REFLECTION_CONTROL_P30_HOTT_CROSSWALK_NEXT')
 e.replace_in_shard(dire,'方向追踪/002 - 治理与用户方向.md','| `DIR-U-HOTT-FOUR-TRACK` | P28：CFTT staged quote/splice审计 | P27/P28 | `P29_CLIMBER_PROVABILITY_AUDIT_NEXT / GOAL_ACTIVE` | `PARADOX_DISCOVERY` | `OUT-HOTT-FOUR-TRACK-PLAN` | staging存在但object introspection被界定 | P28 report；revision245 |','| `DIR-U-HOTT-FOUR-TRACK` | P29：Climber object prov/RFN审计 | P28/P29 | `P30_HOTT_REFLECTION_CROSSWALK_NEXT / GOAL_ACTIVE` | `PARADOX_DISCOVERY` | `OUT-HOTT-FOUR-TRACK-PLAN` | generic reflection正确分层，需HoTT对照 | P29 report；revision246 |')
 e.replace_in_shard(dire,'方向追踪/002 - 治理与用户方向.md','| `DIR-U-ABX-ORIGINAL-CIRCLE` | ABX 原圆环 P3 实际消费者分支停放 | P21/P28 | `P3_PAUSED / INDEPENDENT_P29_AUDIT` | `EVIDENCE_DISCIPLINE` | `OUT-ABX-ACTION-INTAKE` | 仅新版本固定实际 K 或强 R 才重开 | P21/P28 reports；revision245 |','| `DIR-U-ABX-ORIGINAL-CIRCLE` | ABX 原圆环 P3 实际消费者分支停放 | P21/P29 | `P3_PAUSED / P30_HOTT_CROSSWALK` | `EVIDENCE_DISCIPLINE` | `OUT-ABX-ACTION-INTAKE` | 仅新版本固定实际 K 或强 R 才重开 | P21/P29 reports；revision246 |')
 e.replace_in_index(pan,'source_state_revision: 245','source_state_revision: 246');e.replace_in_index(pan,'projection_generation: 20260921-outcome-245','projection_generation: 20260921-outcome-246');e.replace_in_index(pan,'semantic_status: FOUR_TRACK_P28_CFTT_STAGING_SCOPED_P29_CLIMBER_NEXT','semantic_status: FOUR_TRACK_P29_GENERIC_REFLECTION_CONTROL_P30_HOTT_CROSSWALK_NEXT')
 e.replace_in_shard(pan,'全景视野/003 - 当前机器证明包与原生重放.md','| `OUT-HOTT-FOUR-TRACK-PLAN` | P28 CFTT staged quote/splice审计 | `DIR-U-HOTT-FOUR-TRACK` | P27/P28 | `P28_SCOPED / P29_NEXT` | HOAS/postulate/generativity不等于object provability | 不证明HoTT缺陷 | P28 report；revision245 |','| `OUT-HOTT-FOUR-TRACK-PLAN` | P29 Climber object prov/RFN审计 | `DIR-U-HOTT-FOUR-TRACK` | P28/P29 | `P29_SCOPED / P30_NEXT` | generic prov/rung依赖元语言soundness | 不证明HoTT缺陷 | P29 report；revision246 |')
 e.replace_in_shard(pan,'全景视野/003 - 当前机器证明包与原生重放.md','| `OUT-ABX-ACTION-INTAKE` | ABX P3停放，独立 P28已审CFTT | `DIR-U-ABX-ORIGINAL-CIRCLE` | P15/P17/P19/P20/P22/P25/P26/P27/P28 | `P3_PAUSED / P29_AUDIT_NEXT` | 避免重复，保留新实际K重开条件 | 不证明原M/N桥 | P21/P28 reports；revision245 |','| `OUT-ABX-ACTION-INTAKE` | ABX P3停放，独立 P29已审Climber | `DIR-U-ABX-ORIGINAL-CIRCLE` | P15/P17/P19/P20/P22/P25/P26/P27/P28/P29 | `P3_PAUSED / P30_CROSSWALK_NEXT` | 避免重复，保留新实际K重开条件 | 不证明原M/N桥 | P21/P29 reports；revision246 |')
 e.append_to_shard(pan,'全景视野/006 - ERCF-3 与 T3 脉冲及失败台账.md','\n## P29：Climber object prov/RFN正控制（revision246）\n\n固定Lean artifact编译了T₀ `prov`、T₁反射与Con(T₀)阶梯；soundness在元语言，非HoTT/非同层全局自验证。P30提取精确HoTT义务。\n');e.append_to_shard(pan,'全景视野/008 - 当前未完成.md','\n12. `P30-HOTT-REFLECTION-OBLIGATION-CROSSWALK-001`：把P29对象provability/反射六义务逐项对照当前HoTT assets，防止generic正控制误称HoTT实例，并生成下一专属source。\n')
 simple={x:(ROOT/x).read_text() for x in r.MUTABLE if x not in {r.STATE,'MEMORY.md','方向追踪.md','全景视野.md','扩展认知.md'}}
 simple[r.PREFIX+'FRONTIER.md']=simple[r.PREFIX+'FRONTIER.md'].replace('- P28确认CFTT有quote/splice/unstaging合同，但Agda supplement是postulated HOAS且generativity用primTrustMe；不构成object provability/self-validation。下一P29审计climber@`6994d29dda860c3a82de207b1f39ea89526f61c9`的object provability/soundness。入口：`audit/p28-cftt-staged-quotation-splice-unstaging-corpus-20260921/P28-CFTT-STAGED-QUOTATION-SPLICE-UNSTAGING-CORPUS-REPORT.md`。','- P29确认Climber@`6994d29dda860c3a82de207b1f39ea89526f61c9`具有object prov/RFN/Con一阶梯，但解释和soundness在Lean元语言，非HoTT/非同层全局自验证。下一P30做HoTT义务交叉表。入口：`audit/p29-climber-object-provability-soundness-corpus-20260921/P29-CLIMBER-OBJECT-PROVABILITY-SOUNDNESS-CORPUS-REPORT.md`。',1)
 simple[r.PREFIX+'RESUME.md']=simple[r.PREFIX+'RESUME.md'].replace('当前 active goal 在P28后继续：CFTT staged@`9c4e2017669086e2f77df5014f1c215a5a7e07a3` 已审，quote/splice/unstaging合同在postulated HOAS/primTrustMe generativity边界内，非object self-validation。P29审计climber@`6994d29dda860c3a82de207b1f39ea89526f61c9`的object provability/soundness；不重审P3/P1最小接口/跨后端/Guard停放分支。入口：`audit/p28-cftt-staged-quotation-splice-unstaging-corpus-20260921/P28-CFTT-STAGED-QUOTATION-SPLICE-UNSTAGING-CORPUS-REPORT.md`；revision245。','当前 active goal 在P29后继续：Climber@`6994d29dda860c3a82de207b1f39ea89526f61c9` 的object prov/RFN/Con一阶梯已build/smoke核对，但soundness/interpretation在Lean元语言，非HoTT实例。P30逐项交叉到现有HoTT assets；不重审P3/P1最小接口/跨后端/Guard停放分支。入口：`audit/p29-climber-object-provability-soundness-corpus-20260921/P29-CLIMBER-OBJECT-PROVABILITY-SOUNDNESS-CORPUS-REPORT.md`；revision246。',1)
 rows=[]
 for d in (mem,dire,pan,essay):rows+=e.payload_rows(d,ROOT)
 seen={x['path'] for x in rows}
 for rel in r.MUTABLE:
  if rel not in seen:rows.append({'path':rel,'expected_sha256':h(ROOT/rel),'text':r.dump(st).decode() if rel==r.STATE else simple[rel]})
 session=f'# {SID}\n\n- host: codex-desktop\n- model: runtime-model-not-certified-by-tool\n- tier: T3\n- status: `P29_CHECKPOINTED_WITH_SCOPE / P30_HOTT_CROSSWALK_NEXT / NO_NEW_HOTT_DEFECT_CLAIM`\n- load_receipt: research plan snapshot `{pl["snapshot"]}`; P29 source/run evidence and HoTT scope boundary reviewed.\n- authorization: 用户已授权按 goal-3 持续推进、公开/本地侦察和 checkpoint；不启动 Sub Agent、不 push、不发布。\n'
 runs={'schema_version':'hott-session-runs/v1','session_id':SID,'primary_runs':[{'kind':'P29 Climber external build/smoke','result':'BUILD_AND_SMOKE_ACCEPTED_WITH_SCOPE','receipt':f'{DIR}/runs/20260921-P29-CLIMBER-BUILD-SMOKE-01/RUN.json'},{'kind':'P29 source verifier','result':'PASS_WITH_SCOPE'}],'new_math_claims':[],'new_kernel_replay':False}
 rows += [{'path':BASE+'SESSION.md','expected_sha256':None,'text':session},{'path':BASE+'RUNS.json','expected_sha256':None,'text':r.dump(runs).decode()},{'path':BASE+'CORE_COGNITION_AUDIT.md','expected_sha256':None,'text':audit(st['current_core'])}]
 payload={'schema_version':'cognition-checkpoint/v1','session_id':SID,'load_profile':'research','task_ids':[PLAN],'authorization':'用户已授权按goal-3持续推进、公开/本地侦察和checkpoint；不启动Sub Agent、不push、不发布。','files':rows};(OUT/'P29-CHECKPOINT-PAYLOAD.json').write_bytes(r.dump(payload));res=r.checkpoint(ROOT,pl['snapshot'],payload,apply=a.apply);(OUT/('P29-CHECKPOINT-APPLY.json' if a.apply else 'P29-CHECKPOINT-DRY-RUN.json')).write_bytes(r.dump(res));print(json.dumps({k:v for k,v in res.items() if k!='paths'},ensure_ascii=False,indent=2))
if __name__=='__main__':main()
