#!/usr/bin/env python3
"""Verify the current core, curation, source slices and migration receipt.

The validator rebuilds every generated byte in memory.  It proves exact source
copying, complete registered-message disposition, chronological/contiguous IDs
and a total mapping from the declared previous-generation ref. It does not certify the
mathematical truth of user statements or a model's comprehension.
"""
from __future__ import annotations

import argparse
import importlib.util
import json
import re
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
BUILDER_PATH = Path(__file__).with_name("build_core_cognition.py")


def load_builder():
    spec = importlib.util.spec_from_file_location("core_builder", BUILDER_PATH)
    if spec is None or spec.loader is None:
        raise RuntimeError("BUILDER_IMPORT_FAILED")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", type=Path, default=ROOT)
    parser.add_argument("--core", type=Path, default=Path("核心认知.md"))
    parser.add_argument("--manifest", type=Path, default=Path("核心认知.manifest.json"))
    parser.add_argument("--curation", type=Path, default=Path("scripts/audit/core-cognition-curation-v4.json"))
    parser.add_argument("--transition", type=Path, default=Path("audit/core-cognition-generation-4-transition-20260912.json"))
    args = parser.parse_args()
    root = args.project_root.resolve()
    try:
        builder = load_builder()
        manifest, expected_core, expected_manifest_bytes, units = builder.build(root, args.curation)
        actual_core_bytes = (root / args.core).read_bytes()
        actual_manifest_bytes = (root / args.manifest).read_bytes()
        if actual_core_bytes != expected_core.encode("utf-8"):
            raise RuntimeError("CORE_NOT_CANONICAL_GENERATOR_OUTPUT")
        if actual_manifest_bytes != expected_manifest_bytes:
            raise RuntimeError("MANIFEST_NOT_CANONICAL_GENERATOR_OUTPUT")
        actual_manifest = json.loads(actual_manifest_bytes.decode("utf-8"))
        if actual_manifest.get("schema_version") != "core-cognition/v2":
            raise RuntimeError("MANIFEST_SCHEMA_INVALID")
        if actual_manifest.get("asset_class") != "MACHINE_MANAGED_CANONICAL":
            raise RuntimeError("MANIFEST_ASSET_CLASS_INVALID")
        if not re.fullmatch(r"core-cognition-generation-[0-9]+", str(actual_manifest.get("generation"))):
            raise RuntimeError("GENERATION_INVALID")
        ids = [str(row.get("id")) for row in actual_manifest.get("units", [])]
        if ids != [f"KC-{index:06d}" for index in range(1, len(ids) + 1)]:
            raise RuntimeError("KC_IDS_NONCONTIGUOUS")
        parsed = builder.parse_core_payloads(actual_core_bytes.decode("utf-8"))
        if list(parsed) != ids:
            raise RuntimeError("CORE_MANIFEST_ID_ORDER_MISMATCH")
        for row in actual_manifest["units"]:
            unit_id = row["id"]
            payload = parsed[unit_id]
            if builder.sha256(payload.encode("utf-8")) != row.get("unit_sha256"):
                raise RuntimeError(f"PAYLOAD_HASH_MISMATCH:{unit_id}")
            if len(payload.encode("utf-8")) != row.get("unit_bytes"):
                raise RuntimeError(f"PAYLOAD_BYTES_MISMATCH:{unit_id}")
            if row.get("author_class") != "USER_OWNED_DIRECT":
                raise RuntimeError(f"NON_DIRECT_AUTHOR_CLASS:{unit_id}")
            if re.search(r"# Response annotations:|<response-annotations>|AI回答：|^Gemini:$", payload, re.M):
                raise RuntimeError(f"RELAYED_AI_TEXT_IN_CORE:{unit_id}")
        dispositions = actual_manifest.get("message_disposition")
        if not isinstance(dispositions, list) or not dispositions:
            raise RuntimeError("REGISTERED_MESSAGE_DENOMINATOR_EMPTY")
        message_ids = [str(row.get("source_message_id")) for row in dispositions]
        if len(message_ids) != len(set(message_ids)):
            raise RuntimeError("DUPLICATE_MESSAGE_DISPOSITION")
        unit_counts = Counter(str(row["source_message_id"]) for row in actual_manifest["units"])
        for row in dispositions:
            included = row.get("disposition") == "INCLUDED"
            if included != (unit_counts[str(row["source_message_id"])] > 0):
                raise RuntimeError(f"MESSAGE_UNIT_DISPOSITION_MISMATCH:{row['source_message_id']}")
            if row.get("unit_count") != unit_counts[str(row["source_message_id"])]:
                raise RuntimeError(f"MESSAGE_UNIT_COUNT_MISMATCH:{row['source_message_id']}")
        utc_order = [str(row["timestamp_utc"]) for row in actual_manifest["units"]]
        if utc_order != sorted(utc_order):
            raise RuntimeError("CORE_NOT_CHRONOLOGICAL")

        previous_ref = actual_manifest.get("previous_generation_ref")
        if not isinstance(previous_ref, str) or not previous_ref:
            raise RuntimeError("PREVIOUS_GENERATION_REF_MISSING")
        expected_transition = builder.build_transition(root, previous_ref, manifest, units)
        actual_transition_bytes = (root / args.transition).read_bytes()
        if actual_transition_bytes != builder.json_bytes(expected_transition):
            raise RuntimeError("TRANSITION_NOT_CANONICAL_GENERATOR_OUTPUT")
        transition = json.loads(actual_transition_bytes.decode("utf-8"))
        previous_count = transition.get("previous", {}).get("unit_count")
        if transition.get("mapping_remainder") != 0 or transition.get("mapping_count") != previous_count:
            raise RuntimeError("TRANSITION_MAPPING_INCOMPLETE")
        old_ids = [str(row.get("old_id")) for row in transition.get("mappings", [])]
        if type(previous_count) is not int or old_ids != [f"KC-{index:06d}" for index in range(1, previous_count + 1)]:
            raise RuntimeError("TRANSITION_OLD_ID_DENOMINATOR_INVALID")
        target_set = set(ids)
        for row in transition["mappings"]:
            if not set(row.get("target_ids", [])) <= target_set:
                raise RuntimeError(f"TRANSITION_TARGET_UNKNOWN:{row.get('old_id')}")

        counts = actual_manifest["counts"]
        print(json.dumps({
            "status": "PASS_WITH_SCOPE",
            "generation": actual_manifest["generation"],
            "core_units": len(ids),
            "messages": len(dispositions),
            "included_messages": counts["messages_included"],
            "source_files": len(actual_manifest["files"]),
            "core_sha256": actual_manifest["core_document_sha256"],
            "transition_mapping_count": transition["mapping_count"],
            "transition_remainder": transition["mapping_remainder"],
            "model_context": "NOT_CERTIFIED_BY_TOOL",
            "mathematics": "NOT_CERTIFIED"
        }, ensure_ascii=False))
        return 0
    except Exception as exc:
        print(json.dumps({"status": "FAIL", "error": str(exc)}, ensure_ascii=False), file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
