#!/usr/bin/env python3
"""Checkpoint P28's CFTT audit and route P29's object-provability audit."""
from __future__ import annotations
import argparse, hashlib, importlib.util, json, re, sys
from pathlib import Path

ROOT=Path(__file__).resolve().parents[2];OUT=Path(__file__).resolve().parent
SID='S-RES-20260921-ASTRA-P28-CFTT-CORPUS';BASE=f'.codex/research/hott/sessions/{SID}/';PLAN='R-HOTT-FOUR-TRACK-PLAN-20260921';P27='R-P27-REFLECTION-CONSUMER-DISCOVERY-2026-001';P28='R-P28-CFTT-STAGED-QUOTATION-SPLICE-UNSTAGING-CORPUS-20260921';DIR='audit/p28-cftt-staged-quotation-splice-unstaging-corpus-20260921'
SOURCES=(f'{DIR}/P28-CFTT-STAGED-QUOTATION-SPLICE-UNSTAGING-CORPUS-REPORT.md',f'{DIR}/P28-CFTT-SOURCE-FREEZE.json',f'{DIR}/verify_p28_cftt_staged_quotation_splice_unstaging_corpus.py',f'{DIR}/P28-CFTT-STAGED-QUOTATION-SPLICE-UNSTAGING-CORPUS-VERIFICATION.json')
def h(p:Path)->str:return hashlib.sha256(p.read_bytes()).hexdigest()
def load_runtime():
 s=importlib.util.spec_from_file_location('r',ROOT/'.codex/tools/cognition_runtime.py');assert s and s.loader;m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return m
def load_edit():
 sys.path.insert(0,str(ROOT/'scripts/audit'));import projection_edit;return projection_edit
def audit(core):
 rows=re.findall(r'^### (KC-\d+) · .*? · (.+)$',(ROOT/'核心认知.md').read_text(),re.M);assert len(rows)==46
 text=f'# {SID} 核心认知回评\n\n{core["generation"]}；46 条；兼容单文件审计登记 `G-V5-SESSION-AUDIT-SHARD-WRITE-GAP-001`。\n\n- core_change: NO\n- direction_change: P28 CFTT scoped; P29 object provability audit next.\n- panorama_change: staged operation, HOAS/postulate and generativity boundaries recorded.\n- essay_change: NO\n- update_decision: close P28 fixed source and select distinct object-provability candidate.\n- cross_conflicts: no HoTT defect or same-layer global self-validation established.\n- unresolved: P29 source audit; actual K/reality bridges remain open.\n- writer_compatibility: G-V5-SESSION-AUDIT-SHARD-WRITE-GAP-001.\n\n| KC | 主题 | relation | 本单元判断 | 证据、反证条件 |\n|---|---|---|---|---|\n'
 for kc,title in rows:
  rel='DEEPENED' if kc in {'KC-000025','KC-000026','KC-000028','KC-000029','KC-000036','KC-000041','KC-000043','KC-000045','KC-000046'} else 'NOT_TOUCHED'
  text+=f'| `{kc}` | {title} | `{rel}` | '+('P28区分staging、HOAS与强self-validation。' if rel=='DEEPENED' else '本单元未直接检验该用户原文。')+' | P28 report；P29可反证。 |\n'
 return text+'\n## 波次定位\n\nP28验证实际staged process并发现HOAS/generativity界；P29转入含object provability的不同source。\n'
def main():
 ap=argparse.ArgumentParser();ap.add_argument('--apply',action='store_true');args=ap.parse_args();r=load_runtime();e=load_edit();assert all((ROOT/x).is_file() for x in SOURCES)
 st=json.loads((ROOT/r.STATE).read_text());assert st['revision']==244 and st['latest_session']=='S-RES-20260921-ASTRA-P27-REFLECTION-CONSUMER-DISCOVERY';hd=json.loads((ROOT/r.HEAD).read_text());assert all(h(ROOT/p)==v for p,v in hd['tracked'].items());pl=r.plan(ROOT,profile='research',task_ids=[PLAN]);(OUT/'P28-CHECKPOINT-PLAN.json').write_bytes(r.dump(pl));st['revision']=245;st['latest_session']=SID
 p=st['records'][PLAN];p['related_records']=list(dict.fromkeys(p.get('related_records',[])+[P28,SID]));p['status']='four_track_p3_paused_p1_expression_p4_not_triggered_p22_parked_p29_climber_next';p['evidence_status']='P3_PAUSED_SAME_CLASS / P1_MINIMAL_EXPRESSIBILITY_POSITIVE_CONTROL / P4_NOT_TRIGGERED_BY_TRANSLATION_GAP_ALONE / P22_GUARDED_BRIDGE_PARKED / P28_CFTT_STAGING_SCOPED / P29_CLIMBER_OBJECT_PROVABILITY_NEXT / GOAL_ACTIVE';p['full_sources']=list(dict.fromkeys(p.get('full_sources',[])+list(SOURCES)));p['source_hashes'].update({x:h(ROOT/x) for x in p['full_sources'] if (ROOT/x).is_file()});p['revalidation']=p.get('revalidation','')+' Revision245 records P28 CFTT source audit and selects P29 Climber; P27 discovery scope unchanged.'
 st['records'][P28]={'kind':'result','path':SOURCES[0],'lifecycle_status':'CURRENT','evidence_status':'CLOSE_WITH_SCOPE / ACTUAL_STAGED_QUOTATION_SPLICE_UNSTAGING_CONTRACT_SOURCE_REVIEWED / AGDA_SUPPLEMENT_OBJECT_THEORY_POSTULATED_HOAS / GENERATIVITY_AXIOM_TRUSTME_BOUNDARY / NOT_OBJECT_PROVABILITY_OR_HOTT_SELF_VALIDATION / P29_CLIMBER_OBJECT_PROVABILITY_CANDIDATE_SELECTED / NO_NEW_HOTT_DEFECT_CLAIM','status':'complete_with_scope','depends_on':[],'related_records':[PLAN,P27,SID],'full_sources':list(SOURCES),'source_hashes':{x:h(ROOT/x) for x in SOURCES},'scope':'Fixed CFTT source audit only; no CFTT run, HoTT theorem or defect claim.'}
 st['records'][SID]={'kind':'session','path':BASE+'SESSION.md','lifecycle_status':'HISTORICAL','evidence_status':'P28_CHECKPOINTED_WITH_SCOPE','status':'complete_with_scope','depends_on':[],'related_records':[PLAN,P27,P28],'full_sources':[BASE+x for x in ('SESSION.md','RUNS.json','CORE_COGNITION_AUDIT.md')]}
 st['execution_control'].update({'status':'FOUR_TRACK_P3_PAUSED_P1_EXPRESSIBLE_P4_NOT_TRIGGERED_P22_PARKED_P29_CLIMBER_NEXT','current_phase':'PHASE_2_P28_CFTT_STAGING_SCOPED_P29_CLIMBER_PROVABILITY_AUDIT_NEXT','second_phase_status':'P3_PAUSED_P1_POSITIVE_CONTROL_P4_NOT_TRIGGERED_GUARD_PARKED_P29_NEXT','last_checkpoint_session':SID,'checkpoint_result':f'.codex/cognition/checkpoints/{SID}/result.json','next_minimal_verification':'P29-CLIMBER-OBJECT-PROVABILITY-SOUNDNESS-CORPUS-001. At fixed climber main 6994d29dda860c3a82de207b1f39ea89526f61c9, inspect exact object prov, metalanguage soundness gate, theory construction, self-reference/consistency/global truth claims and relation to HoTT. Freeze Input/Operation/Observation/Done; do not treat an object prov predicate alone as same-theory global self-validation.'})
 st['projection']['status']='FOUR_TRACK_P3_PAUSED_P1_EXPRESSIBLE_P4_NOT_TRIGGERED_GUARD_PARKED / P28_CFTT_STAGING_SCOPED / NEXT_P29_CLIMBER_PROVABILITY / GOAL_ACTIVE / NO_NEW_HOTT_DEFECT_CLAIM'
 mem=e.load(ROOT,'MEMORY.md');dire=e.load(ROOT,'方向追踪.md');pan=e.load(ROOT,'全景视野.md');essay=e.load(ROOT,'扩展认知.md')
 old='P27 已将本地未审 CFTT 题录升级为版本固定 staged quote/splice/unstaging 候选。下一=P28：固定 staged@`9c4e2017669086e2f77df5014f1c215a5a7e07a3` 审计 Agda code supplement 的对象/元层、quotation/splicing/unstaging与任何proof-predicate/self-soundness；P3/P1/P4/Guard继续停放。入口：`audit/p27-reflection-consumer-discovery-20260921/P27-REFLECTION-CONSUMER-DISCOVERY-REPORT.md`；revision244。'
 new='P28 已核对 CFTT staging source：实际quote/splice/unstaging合同存在，但Agda supplement是postulated HOAS，generativity用primTrustMe，不构成对象provability/self-validation。下一=P29：固定 climber@`6994d29dda860c3a82de207b1f39ea89526f61c9`审计object `prov`和soundness gate；P3/P1/P4/Guard继续停放。入口：`audit/p28-cftt-staged-quotation-splice-unstaging-corpus-20260921/P28-CFTT-STAGED-QUOTATION-SPLICE-UNSTAGING-CORPUS-REPORT.md`；revision245。'
 e.replace_in_shard(mem,'MEMORY/001 - 当前执行队列.md',old,new);e.append_to_shard(mem,'MEMORY/003 - 当前验证状态与顺序日志.md','\nS-RES-20260921-ASTRA-P28-CFTT-CORPUS：CFTT staged source的HOAS/postulate/generativity边界已审；P29 Climber object provability audit next；revision245。\n')
 e.replace_in_index(dire,'source_state_revision: 244','source_state_revision: 245');e.replace_in_index(dire,'projection_generation: 20260921-direction-244','projection_generation: 20260921-direction-245');e.replace_in_index(dire,'semantic_status: FOUR_TRACK_P27_CFTT_CANDIDATE_P28_AUDIT_NEXT','semantic_status: FOUR_TRACK_P28_CFTT_STAGING_SCOPED_P29_CLIMBER_NEXT')
 e.replace_in_shard(dire,'方向追踪/002 - 治理与用户方向.md','| `DIR-U-HOTT-FOUR-TRACK` | P27：CFTT反射消费者发现 | P26/P27 | `P28_CFTT_STAGED_AUDIT_NEXT / GOAL_ACTIVE` | `PARADOX_DISCOVERY` | `OUT-HOTT-FOUR-TRACK-PLAN` | 选定quote/splice/unstaging实际consumer | P27 report；revision244 |','| `DIR-U-HOTT-FOUR-TRACK` | P28：CFTT staged quote/splice审计 | P27/P28 | `P29_CLIMBER_PROVABILITY_AUDIT_NEXT / GOAL_ACTIVE` | `PARADOX_DISCOVERY` | `OUT-HOTT-FOUR-TRACK-PLAN` | staging存在但object introspection被界定 | P28 report；revision245 |')
 e.replace_in_shard(dire,'方向追踪/002 - 治理与用户方向.md','| `DIR-U-ABX-ORIGINAL-CIRCLE` | ABX 原圆环 P3 实际消费者分支停放 | P21/P27 | `P3_PAUSED / INDEPENDENT_P28_AUDIT` | `EVIDENCE_DISCIPLINE` | `OUT-ABX-ACTION-INTAKE` | 仅新版本固定实际 K 或强 R 才重开 | P21/P27 reports；revision244 |','| `DIR-U-ABX-ORIGINAL-CIRCLE` | ABX 原圆环 P3 实际消费者分支停放 | P21/P28 | `P3_PAUSED / INDEPENDENT_P29_AUDIT` | `EVIDENCE_DISCIPLINE` | `OUT-ABX-ACTION-INTAKE` | 仅新版本固定实际 K 或强 R 才重开 | P21/P28 reports；revision245 |')
 e.replace_in_index(pan,'source_state_revision: 244','source_state_revision: 245');e.replace_in_index(pan,'projection_generation: 20260921-outcome-244','projection_generation: 20260921-outcome-245');e.replace_in_index(pan,'semantic_status: FOUR_TRACK_P27_CFTT_CANDIDATE_P28_AUDIT_NEXT','semantic_status: FOUR_TRACK_P28_CFTT_STAGING_SCOPED_P29_CLIMBER_NEXT')
 e.replace_in_shard(pan,'全景视野/003 - 当前机器证明包与原生重放.md','| `OUT-HOTT-FOUR-TRACK-PLAN` | P27 CFTT反射消费者发现 | `DIR-U-HOTT-FOUR-TRACK` | P26/P27 | `P27_SELECTED / P28_NEXT` | 版本固定quote/splice/unstaging consumer待审 | 不证明HoTT缺陷 | P27 report；revision244 |','| `OUT-HOTT-FOUR-TRACK-PLAN` | P28 CFTT staged quote/splice审计 | `DIR-U-HOTT-FOUR-TRACK` | P27/P28 | `P28_SCOPED / P29_NEXT` | HOAS/postulate/generativity不等于object provability | 不证明HoTT缺陷 | P28 report；revision245 |')
 e.replace_in_shard(pan,'全景视野/003 - 当前机器证明包与原生重放.md','| `OUT-ABX-ACTION-INTAKE` | ABX P3停放，独立 P27已选 CFTT | `DIR-U-ABX-ORIGINAL-CIRCLE` | P15/P17/P19/P20/P22/P25/P26/P27 | `P3_PAUSED / P28_AUDIT_NEXT` | 避免重复，保留新实际K重开条件 | 不证明原M/N桥 | P21/P27 reports；revision244 |','| `OUT-ABX-ACTION-INTAKE` | ABX P3停放，独立 P28已审CFTT | `DIR-U-ABX-ORIGINAL-CIRCLE` | P15/P17/P19/P20/P22/P25/P26/P27/P28 | `P3_PAUSED / P29_AUDIT_NEXT` | 避免重复，保留新实际K重开条件 | 不证明原M/N桥 | P21/P28 reports；revision245 |')
 e.append_to_shard(pan,'全景视野/006 - ERCF-3 与 T3 脉冲及失败台账.md','\n## P28：CFTT staging source审计（revision245）\n\nCFTT有实际quote/splice/unstaging合同，但Agda supplement以postulated HOAS和primTrustMe generativity实现边界；不是object provability/self-validation。P29转向object `prov` source。\n');e.append_to_shard(pan,'全景视野/008 - 当前未完成.md','\n11. `P29-CLIMBER-OBJECT-PROVABILITY-SOUNDNESS-CORPUS-001`：固定Climber source的object `prov`、soundness gate、self-reference/consistency/global truth资格和HoTT关系审计。\n')
 simple={x:(ROOT/x).read_text() for x in r.MUTABLE if x not in {r.STATE,'MEMORY.md','方向追踪.md','全景视野.md','扩展认知.md'}}
 simple[r.PREFIX+'FRONTIER.md']=simple[r.PREFIX+'FRONTIER.md'].replace('- P27从本地未审CFTT题录与公开source选择staged@`9c4e2017669086e2f77df5014f1c215a5a7e07a3`；P28审计actual quote/splice/unstaging consumer，不预判为HoTT self-validation。入口：`audit/p27-reflection-consumer-discovery-20260921/P27-REFLECTION-CONSUMER-DISCOVERY-REPORT.md`。','- P28确认CFTT有quote/splice/unstaging合同，但Agda supplement是postulated HOAS且generativity用primTrustMe；不构成object provability/self-validation。下一P29审计climber@`6994d29dda860c3a82de207b1f39ea89526f61c9`的object provability/soundness。入口：`audit/p28-cftt-staged-quotation-splice-unstaging-corpus-20260921/P28-CFTT-STAGED-QUOTATION-SPLICE-UNSTAGING-CORPUS-REPORT.md`。',1)
 simple[r.PREFIX+'RESUME.md']=simple[r.PREFIX+'RESUME.md'].replace('当前 active goal 在P27后继续：本地未审CFTT题录已以staged@`9c4e2017669086e2f77df5014f1c215a5a7e07a3`版本固定，P28审计其quote/splice/unstaging和actual object/meta boundary；不重审P3/P1最小接口/跨后端/Guard停放分支。入口：`audit/p27-reflection-consumer-discovery-20260921/P27-REFLECTION-CONSUMER-DISCOVERY-REPORT.md`；revision244。','当前 active goal 在P28后继续：CFTT staged@`9c4e2017669086e2f77df5014f1c215a5a7e07a3` 已审，quote/splice/unstaging合同在postulated HOAS/primTrustMe generativity边界内，非object self-validation。P29审计climber@`6994d29dda860c3a82de207b1f39ea89526f61c9`的object provability/soundness；不重审P3/P1最小接口/跨后端/Guard停放分支。入口：`audit/p28-cftt-staged-quotation-splice-unstaging-corpus-20260921/P28-CFTT-STAGED-QUOTATION-SPLICE-UNSTAGING-CORPUS-REPORT.md`；revision245。',1)
 rows=[]
 for d in (mem,dire,pan,essay):rows+=e.payload_rows(d,ROOT)
 seen={x['path'] for x in rows}
 for rel in r.MUTABLE:
  if rel not in seen:rows.append({'path':rel,'expected_sha256':h(ROOT/rel),'text':r.dump(st).decode() if rel==r.STATE else simple[rel]})
 session=f'# {SID}\n\n- host: codex-desktop\n- model: runtime-model-not-certified-by-tool\n- tier: T3\n- status: `P28_CHECKPOINTED_WITH_SCOPE / P29_CLIMBER_AUDIT_NEXT / NO_NEW_HOTT_DEFECT_CLAIM`\n- load_receipt: research plan snapshot `{pl["snapshot"]}`; P28 fixed staged source and local/public asset checks.\n- authorization: 用户已授权按 goal-3 持续推进、公开/本地侦察和 checkpoint；不启动 Sub Agent、不 push、不发布。\n'
 runs={'schema_version':'hott-session-runs/v1','session_id':SID,'primary_runs':[{'kind':'P28 source verifier','result':'PASS_WITH_SCOPE'},{'kind':'toolchain qualification','result':'CFTT historical Agda 2.6.4.3/stdlib2.0 unavailable; no incompatible run'}],'new_math_claims':[],'new_kernel_replay':False}
 rows += [{'path':BASE+'SESSION.md','expected_sha256':None,'text':session},{'path':BASE+'RUNS.json','expected_sha256':None,'text':r.dump(runs).decode()},{'path':BASE+'CORE_COGNITION_AUDIT.md','expected_sha256':None,'text':audit(st['current_core'])}]
 payload={'schema_version':'cognition-checkpoint/v1','session_id':SID,'load_profile':'research','task_ids':[PLAN],'authorization':'用户已授权按goal-3持续推进、公开/本地侦察和checkpoint；不启动Sub Agent、不push、不发布。','files':rows};(OUT/'P28-CHECKPOINT-PAYLOAD.json').write_bytes(r.dump(payload));result=r.checkpoint(ROOT,pl['snapshot'],payload,apply=args.apply);(OUT/('P28-CHECKPOINT-APPLY.json' if args.apply else 'P28-CHECKPOINT-DRY-RUN.json')).write_bytes(r.dump(result));print(json.dumps({k:v for k,v in result.items() if k!='paths'},ensure_ascii=False,indent=2))
if __name__=='__main__':main()
