{-# OPTIONS --safe --cubical --guardedness #-}
{-
  GENERATED by gen_p4.py -- do not edit by hand.
  (Claude, session 7f138325, 2026-09-26; goal CG-003, gate G1)

  proof id : MP-CG001-WILD-SST-P4-001
  claim    : CG001-C-68 (full statement in CLAIM.md)

  The general second coherence Coh₃ (the permutohedron P₄) of the
  semi-simplicial identities.  Its value on the degenerate structure flat of
  CG001-C-66 is established in WildSSTP4Flat.agda (generated by the same
  script).

  WildSSTᵢ is the definition of CG001-C-64 (WildSST.agda, same Fin, weaken,
  order, face maps and identities) with one change: the order hypothesis
  i ≤F j of the identities is an irrelevant argument.  ≤F is a proposition,
  so this only identifies proof terms that are equal anyway; it lets the
  same edge of P₄, reached through different faces, be the same term.
  toIrr turns every WildSST of CG001-C-64 into a WildSSTᵢ.

  The structure of P₄ used below (words, routes, moves, faces, and the check
  that the two hemispheres use every face exactly once) is listed in
  P4_STRUCTURE.txt, written by the same script.
-}
module WildSSTP4 where

open import Cubical.Foundations.Prelude
open import Cubical.Foundations.GroupoidLaws using (assoc ; congFunct)
open import Cubical.Foundations.Function using (homotopyNatural)
open import Cubical.Data.Nat using (ℕ ; zero ; suc ; _+_)
open import Cubical.Data.Unit using (Unit ; tt)
open import Cubical.Data.Sum using (inl ; inr)
open import Cubical.Data.Int using (ℤ ; pos ; negsuc)
open import Cubical.Data.Int.Properties using (negsucNotpos)
open import Cubical.HITs.S1.Base using (S¹ ; base ; winding)
open import Cubical.HITs.S2.Base using (S²) renaming (base to north)
open import Cubical.Relation.Nullary using (¬_)

open import WildSST using (Fin ; fzero ; fsuc ; weaken ; _≤F_ ; ≤F-trans ; weaken≤ ; weaken≤suc ; WildSST)
open import WildSST2 using (Hopf ; carry ; r ; σr)

------------------------------------------------------------------------
-- Order lemmas used to build the (irrelevant) proofs.

weakenN : (g : ℕ) {s : ℕ} → Fin s → Fin (g + s)
weakenN zero a = a
weakenN (suc g) a = weaken (weakenN g a)

fsucN : (g : ℕ) {s : ℕ} → Fin s → Fin (g + s)
fsucN zero a = a
fsucN (suc g) a = fsuc (fsucN g a)

weaken≤N : (g : ℕ) {s : ℕ} (a b : Fin s) → a ≤F b → weakenN g a ≤F weakenN g b
weaken≤N zero a b h = h
weaken≤N (suc g) a b h = weaken≤ (weakenN g a) (weakenN g b) (weaken≤N g a b h)

wk≤fs : (g : ℕ) {s : ℕ} (a b : Fin s) → a ≤F b → weakenN g a ≤F fsucN g b
wk≤fs zero a b h = h
wk≤fs (suc g) a b h = weaken≤suc (weakenN g a) (fsucN g b) (wk≤fs g a b h)

------------------------------------------------------------------------
-- The definition of CG001-C-64 with an irrelevant order hypothesis.

record WildSSTᵢ : Type₁ where
  field
    X   : ℕ → Type
    d   : (n : ℕ) → Fin (suc (suc n)) → X (suc n) → X n
    sid : (n : ℕ) (i j : Fin (suc (suc n))) → .(i ≤F j) → (x : X (suc (suc n)))
        → d n i (d (suc n) (fsuc j) x) ≡ d n j (d (suc n) (weaken i) x)

toIrr : WildSST → WildSSTᵢ
WildSSTᵢ.X (toIrr S) = WildSST.X S
WildSSTᵢ.d (toIrr S) = WildSST.d S
WildSSTᵢ.sid (toIrr S) n i j h x = WildSST.sid S n i j (recompute i j h) x
  where
  recompute : {n : ℕ} (a b : Fin n) → .(a ≤F b) → a ≤F b
  recompute {suc n} (inl _) b _ = tt
  recompute {suc n} (inr a) (inl _) ()
  recompute {suc n} (inr a) (inr b) h = recompute a b h

module Routesᵢ (S : WildSSTᵢ) where
  open WildSSTᵢ S

  routeA : (m : ℕ) (i j k : Fin (suc (suc m))) .(p : i ≤F j) .(q : j ≤F k)
    (x : X (suc (suc (suc m))))
    → d m i (d (suc m) (fsuc j) (d (suc (suc m)) (fsuc (fsuc k)) x))
      ≡ d m k (d (suc m) (weaken j) (d (suc (suc m)) (weaken (weaken i)) x))
  routeA m i j k p q x =
      cong (d m i) (sid (suc m) (fsuc j) (fsuc k) q x)
    ∙ sid m i k (≤F-trans i j k p q) (d (suc (suc m)) (weaken (fsuc j)) x)
    ∙ cong (d m k) (sid (suc m) (weaken i) (weaken j) (weaken≤ i j p) x)

  routeB : (m : ℕ) (i j k : Fin (suc (suc m))) .(p : i ≤F j) .(q : j ≤F k)
    (x : X (suc (suc (suc m))))
    → d m i (d (suc m) (fsuc j) (d (suc (suc m)) (fsuc (fsuc k)) x))
      ≡ d m k (d (suc m) (weaken j) (d (suc (suc m)) (weaken (weaken i)) x))
  routeB m i j k p q x =
      sid m i j p (d (suc (suc m)) (fsuc (fsuc k)) x)
    ∙ cong (d m j) (sid (suc m) (weaken i) (fsuc k)
                      (weaken≤suc i k (≤F-trans i j k p q)) x)
    ∙ sid m j k q (d (suc (suc m)) (weaken (weaken i)) x)

open Routesᵢ

Coh₂ᵢ : WildSSTᵢ → Type
Coh₂ᵢ S = (m : ℕ) (i j k : Fin (suc (suc m))) .(p : i ≤F j) .(q : j ≤F k)
  (x : WildSSTᵢ.X S (suc (suc (suc m))))
  → routeA S m i j k p q x ≡ routeB S m i j k p q x

record WildSSTᵢ₂ : Type₁ where
  field
    underlying : WildSSTᵢ
    hexagon    : Coh₂ᵢ underlying

------------------------------------------------------------------------
-- Path algebra: replacing a segment of a composite, and pushing a hexagon
-- along a map.

module _ {ℓ : Level} {A : Type ℓ} where
  seg2 : {w x x' z v : A} {a : w ≡ x} {b : x ≡ z} {a' : w ≡ x'} {b' : x' ≡ z}
       → a ∙ b ≡ a' ∙ b' → (T : z ≡ v) → a ∙ b ∙ T ≡ a' ∙ b' ∙ T
  seg2 {a = a} {b} {a' = a'} {b'} Q T = assoc a b T ∙ cong (_∙ T) Q ∙ sym (assoc a' b' T)

  seg3 : {w x y x' y' z v : A} {a : w ≡ x} {b : x ≡ y} {c : y ≡ z}
         {a' : w ≡ x'} {b' : x' ≡ y'} {c' : y' ≡ z}
       → a ∙ b ∙ c ≡ a' ∙ b' ∙ c' → (T : z ≡ v) → a ∙ b ∙ c ∙ T ≡ a' ∙ b' ∙ c' ∙ T
  seg3 {a = a} {b} {c} {a' = a'} {b'} {c'} H T =
      (cong (a ∙_) (assoc b c T) ∙ assoc a (b ∙ c) T)
    ∙ cong (_∙ T) H
    ∙ sym (cong (a' ∙_) (assoc b' c' T) ∙ assoc a' (b' ∙ c') T)

module _ {ℓ ℓ' : Level} {A : Type ℓ} {B : Type ℓ'} where
  congFunct₃ : (f : A → B) {w x y z : A} (a : w ≡ x) (b : x ≡ y) (c : y ≡ z)
             → cong f (a ∙ b ∙ c) ≡ cong f a ∙ cong f b ∙ cong f c
  congFunct₃ f a b c = congFunct f a (b ∙ c) ∙ cong (cong f a ∙_) (congFunct f b c)

  topFace : (f : A → B) {w x y x' y' z : A} {a : w ≡ x} {b : x ≡ y} {c : y ≡ z}
            {a' : w ≡ x'} {b' : x' ≡ y'} {c' : y' ≡ z}
          → a ∙ b ∙ c ≡ a' ∙ b' ∙ c'
          → cong f a ∙ cong f b ∙ cong f c ≡ cong f a' ∙ cong f b' ∙ cong f c'
  topFace f {a = a} {b} {c} {a' = a'} {b'} {c'} H =
    sym (congFunct₃ f a b c) ∙ cong (cong f) H ∙ congFunct₃ f a' b' c'

------------------------------------------------------------------------
-- The two hemispheres of P₄ and the coherence Coh₃.

module P4 (S : WildSSTᵢ₂) where
  open WildSSTᵢ₂ S
  open WildSSTᵢ underlying

  module _ (m : ℕ) (i j k l : Fin (suc (suc m)))
           .(p : i ≤F j) .(q : j ≤F k) .(s : k ≤F l)
           (x : X (suc (suc (suc (suc m))))) where
    e0 : _
    e0 = sid m i j (wk≤fs 0 (weakenN 0 i) (weakenN 0 j) (weaken≤N 0 i j (p))) (d (suc (suc m)) (fsuc (fsuc k)) (d (suc (suc (suc m))) (fsuc (fsuc (fsuc l))) x))
    e1 : _
    e1 = cong (d m j) (sid (suc m) (weaken i) (fsuc k) (wk≤fs 1 (weakenN 0 i) (weakenN 0 k) (weaken≤N 0 i k (≤F-trans i j k p q))) (d (suc (suc (suc m))) (fsuc (fsuc (fsuc l))) x))
    e2 : _
    e2 = sid m j k (wk≤fs 0 (weakenN 0 j) (weakenN 0 k) (weaken≤N 0 j k (q))) (d (suc (suc m)) (weaken (weaken i)) (d (suc (suc (suc m))) (fsuc (fsuc (fsuc l))) x))
    e3 : _
    e3 = cong (λ z → d m k (d (suc m) (weaken j) z)) (sid (suc (suc m)) (weaken (weaken i)) (fsuc (fsuc l)) (wk≤fs 2 (weakenN 0 i) (weakenN 0 l) (weaken≤N 0 i l (≤F-trans i k l (≤F-trans i j k p q) s))) x)
    e4 : _
    e4 = cong (d m k) (sid (suc m) (weaken j) (fsuc l) (wk≤fs 1 (weakenN 0 j) (weakenN 0 l) (weaken≤N 0 j l (≤F-trans j k l q s))) (d (suc (suc (suc m))) (weaken (weaken (weaken i))) x))
    e5 : _
    e5 = sid m k l (wk≤fs 0 (weakenN 0 k) (weakenN 0 l) (weaken≤N 0 k l (s))) (d (suc (suc m)) (weaken (weaken j)) (d (suc (suc (suc m))) (weaken (weaken (weaken i))) x))
    e6 : _
    e6 = cong (d m i) (sid (suc m) (fsuc j) (fsuc k) (wk≤fs 0 (weakenN 0 j) (weakenN 0 k) (weaken≤N 0 j k (q))) (d (suc (suc (suc m))) (fsuc (fsuc (fsuc l))) x))
    e7 : _
    e7 = sid m i k (wk≤fs 0 (weakenN 0 i) (weakenN 0 k) (weaken≤N 0 i k (≤F-trans i j k p q))) (d (suc (suc m)) (fsuc (weaken j)) (d (suc (suc (suc m))) (fsuc (fsuc (fsuc l))) x))
    e8 : _
    e8 = cong (d m k) (sid (suc m) (weaken i) (weaken j) (wk≤fs 0 (weakenN 1 i) (weakenN 1 j) (weaken≤N 1 i j (p))) (d (suc (suc (suc m))) (fsuc (fsuc (fsuc l))) x))
    e9 : _
    e9 = cong (λ z → d m k (d (suc m) (weaken i) z)) (sid (suc (suc m)) (fsuc (weaken j)) (fsuc (fsuc l)) (wk≤fs 1 (weakenN 0 j) (weakenN 0 l) (weaken≤N 0 j l (≤F-trans j k l q s))) x)
    e10 : _
    e10 = cong (d m k) (sid (suc m) (weaken i) (fsuc l) (wk≤fs 1 (weakenN 0 i) (weakenN 0 l) (weaken≤N 0 i l (≤F-trans i k l (≤F-trans i j k p q) s))) (d (suc (suc (suc m))) (fsuc (weaken (weaken j))) x))
    e11 : _
    e11 = cong (λ z → d m k (d (suc m) (fsuc l) z)) (sid (suc (suc m)) (weaken (weaken i)) (weaken (weaken j)) (wk≤fs 0 (weakenN 2 i) (weakenN 2 j) (weaken≤N 2 i j (p))) x)
    e12 : _
    e12 = cong (λ z → d m i (d (suc m) (fsuc k) z)) (sid (suc (suc m)) (fsuc (weaken j)) (fsuc (fsuc l)) (wk≤fs 1 (weakenN 0 j) (weakenN 0 l) (weaken≤N 0 j l (≤F-trans j k l q s))) x)
    e13 : _
    e13 = sid m i k (wk≤fs 0 (weakenN 0 i) (weakenN 0 k) (weaken≤N 0 i k (≤F-trans i j k p q))) (d (suc (suc m)) (fsuc (fsuc l)) (d (suc (suc (suc m))) (fsuc (weaken (weaken j))) x))
    e14 : _
    e14 = sid m k l (wk≤fs 0 (weakenN 0 k) (weakenN 0 l) (weaken≤N 0 k l (s))) (d (suc (suc m)) (weaken (weaken i)) (d (suc (suc (suc m))) (fsuc (weaken (weaken j))) x))
    e15 : _
    e15 = cong (λ z → d m l (d (suc m) (weaken k) z)) (sid (suc (suc m)) (weaken (weaken i)) (weaken (weaken j)) (wk≤fs 0 (weakenN 2 i) (weakenN 2 j) (weaken≤N 2 i j (p))) x)
    e16 : _
    e16 = cong (d m i) (sid (suc m) (fsuc k) (fsuc l) (wk≤fs 0 (weakenN 0 k) (weakenN 0 l) (weaken≤N 0 k l (s))) (d (suc (suc (suc m))) (fsuc (weaken (weaken j))) x))
    e17 : _
    e17 = sid m i l (wk≤fs 0 (weakenN 0 i) (weakenN 0 l) (weaken≤N 0 i l (≤F-trans i k l (≤F-trans i j k p q) s))) (d (suc (suc m)) (fsuc (weaken k)) (d (suc (suc (suc m))) (fsuc (weaken (weaken j))) x))
    e18 : _
    e18 = cong (d m l) (sid (suc m) (weaken i) (weaken k) (wk≤fs 0 (weakenN 1 i) (weakenN 1 k) (weaken≤N 1 i k (≤F-trans i j k p q))) (d (suc (suc (suc m))) (fsuc (weaken (weaken j))) x))
    e19 : _
    e19 = cong (λ z → d m i (d (suc m) (fsuc j) z)) (sid (suc (suc m)) (fsuc (fsuc k)) (fsuc (fsuc l)) (wk≤fs 0 (weakenN 0 k) (weakenN 0 l) (weaken≤N 0 k l (s))) x)
    e20 : _
    e20 = cong (d m i) (sid (suc m) (fsuc j) (fsuc l) (wk≤fs 0 (weakenN 0 j) (weakenN 0 l) (weaken≤N 0 j l (≤F-trans j k l q s))) (d (suc (suc (suc m))) (fsuc (fsuc (weaken k))) x))
    e21 : _
    e21 = cong (λ z → d m i (d (suc m) (fsuc l) z)) (sid (suc (suc m)) (fsuc (weaken j)) (fsuc (weaken k)) (wk≤fs 0 (weakenN 1 j) (weakenN 1 k) (weaken≤N 1 j k (q))) x)
    e22 : _
    e22 = cong (λ z → d m j (d (suc m) (fsuc k) z)) (sid (suc (suc m)) (weaken (weaken i)) (fsuc (fsuc l)) (wk≤fs 2 (weakenN 0 i) (weakenN 0 l) (weaken≤N 0 i l (≤F-trans i k l (≤F-trans i j k p q) s))) x)
    e23 : _
    e23 = sid m j k (wk≤fs 0 (weakenN 0 j) (weakenN 0 k) (weaken≤N 0 j k (q))) (d (suc (suc m)) (fsuc (fsuc l)) (d (suc (suc (suc m))) (weaken (weaken (weaken i))) x))
    e24 : _
    e24 = cong (d m j) (sid (suc m) (fsuc k) (fsuc l) (wk≤fs 0 (weakenN 0 k) (weakenN 0 l) (weaken≤N 0 k l (s))) (d (suc (suc (suc m))) (weaken (weaken (weaken i))) x))
    e25 : _
    e25 = sid m j l (wk≤fs 0 (weakenN 0 j) (weakenN 0 l) (weaken≤N 0 j l (≤F-trans j k l q s))) (d (suc (suc m)) (fsuc (weaken k)) (d (suc (suc (suc m))) (weaken (weaken (weaken i))) x))
    e26 : _
    e26 = cong (d m l) (sid (suc m) (weaken j) (weaken k) (wk≤fs 0 (weakenN 1 j) (weakenN 1 k) (weaken≤N 1 j k (q))) (d (suc (suc (suc m))) (weaken (weaken (weaken i))) x))
    e27 : _
    e27 = cong (λ z → d m j (d (suc m) (weaken i) z)) (sid (suc (suc m)) (fsuc (fsuc k)) (fsuc (fsuc l)) (wk≤fs 0 (weakenN 0 k) (weakenN 0 l) (weaken≤N 0 k l (s))) x)
    e28 : _
    e28 = cong (d m j) (sid (suc m) (weaken i) (fsuc l) (wk≤fs 1 (weakenN 0 i) (weakenN 0 l) (weaken≤N 0 i l (≤F-trans i k l (≤F-trans i j k p q) s))) (d (suc (suc (suc m))) (fsuc (fsuc (weaken k))) x))
    e29 : _
    e29 = cong (λ z → d m j (d (suc m) (fsuc l) z)) (sid (suc (suc m)) (weaken (weaken i)) (fsuc (weaken k)) (wk≤fs 1 (weakenN 1 i) (weakenN 1 k) (weaken≤N 1 i k (≤F-trans i j k p q))) x)
    e30 : _
    e30 = sid m i j (wk≤fs 0 (weakenN 0 i) (weakenN 0 j) (weaken≤N 0 i j (p))) (d (suc (suc m)) (fsuc (fsuc l)) (d (suc (suc (suc m))) (fsuc (fsuc (weaken k))) x))
    e31 : _
    e31 = sid m j l (wk≤fs 0 (weakenN 0 j) (weakenN 0 l) (weaken≤N 0 j l (≤F-trans j k l q s))) (d (suc (suc m)) (weaken (weaken i)) (d (suc (suc (suc m))) (fsuc (fsuc (weaken k))) x))
    e32 : _
    e32 = cong (λ z → d m l (d (suc m) (weaken j) z)) (sid (suc (suc m)) (weaken (weaken i)) (fsuc (weaken k)) (wk≤fs 1 (weakenN 1 i) (weakenN 1 k) (weaken≤N 1 i k (≤F-trans i j k p q))) x)
    e33 : _
    e33 = sid m i l (wk≤fs 0 (weakenN 0 i) (weakenN 0 l) (weaken≤N 0 i l (≤F-trans i k l (≤F-trans i j k p q) s))) (d (suc (suc m)) (fsuc (weaken j)) (d (suc (suc (suc m))) (fsuc (fsuc (weaken k))) x))
    e34 : _
    e34 = cong (d m l) (sid (suc m) (weaken i) (weaken j) (wk≤fs 0 (weakenN 1 i) (weakenN 1 j) (weaken≤N 1 i j (p))) (d (suc (suc (suc m))) (fsuc (fsuc (weaken k))) x))
    e35 : _
    e35 = cong (λ z → d m l (d (suc m) (weaken i) z)) (sid (suc (suc m)) (fsuc (weaken j)) (fsuc (weaken k)) (wk≤fs 0 (weakenN 1 j) (weakenN 1 k) (weaken≤N 1 j k (q))) x)
    hem₁-1 : _
    hem₁-1 = seg3 (sym (hexagon m i j k (wk≤fs 0 (weakenN 0 i) (weakenN 0 j) (weaken≤N 0 i j (p))) (wk≤fs 0 (weakenN 0 j) (weakenN 0 k) (weaken≤N 0 j k (q))) (d (suc (suc (suc m))) (fsuc (fsuc (fsuc l))) x))) (e3 ∙ e4 ∙ e5 ∙ refl)
    hem₁-2 : _
    hem₁-2 = cong (λ z → e6 ∙ e7 ∙ z) (seg3 (sym (topFace (d m k) (hexagon (suc m) (weaken i) (weaken j) (fsuc l) (wk≤fs 0 (weakenN 1 i) (weakenN 1 j) (weaken≤N 1 i j (p))) (wk≤fs 1 (weakenN 0 j) (weakenN 0 l) (weaken≤N 0 j l (≤F-trans j k l q s))) x))) (e5 ∙ refl))
    hem₁-3 : _
    hem₁-3 = cong (λ z → e6 ∙ z) (seg2 (homotopyNatural {f = (λ y → d m i (d (suc m) (fsuc k) y))} {g = (λ y → d m k (d (suc m) (weaken i) y))} (λ y → sid m i k (wk≤fs 0 (weakenN 0 i) (weakenN 0 k) (weaken≤N 0 i k (≤F-trans i j k p q))) y) (sid (suc (suc m)) (fsuc (weaken j)) (fsuc (fsuc l)) (wk≤fs 1 (weakenN 0 j) (weakenN 0 l) (weaken≤N 0 j l (≤F-trans j k l q s))) x)) (e10 ∙ e11 ∙ e5 ∙ refl))
    hem₁-4 : _
    hem₁-4 = cong (λ z → e6 ∙ e12 ∙ e13 ∙ e10 ∙ z) (seg2 (sym (homotopyNatural {f = (λ y → d m k (d (suc m) (fsuc l) y))} {g = (λ y → d m l (d (suc m) (weaken k) y))} (λ y → sid m k l (wk≤fs 0 (weakenN 0 k) (weakenN 0 l) (weaken≤N 0 k l (s))) y) (sid (suc (suc m)) (weaken (weaken i)) (weaken (weaken j)) (wk≤fs 0 (weakenN 2 i) (weakenN 2 j) (weaken≤N 2 i j (p))) x))) (refl))
    hem₁-5 : _
    hem₁-5 = cong (λ z → e6 ∙ e12 ∙ z) (seg3 (sym (hexagon m i k l (wk≤fs 0 (weakenN 0 i) (weakenN 0 k) (weaken≤N 0 i k (≤F-trans i j k p q))) (wk≤fs 0 (weakenN 0 k) (weakenN 0 l) (weaken≤N 0 k l (s))) (d (suc (suc (suc m))) (fsuc (weaken (weaken j))) x))) (e15 ∙ refl))
    hem₁-6 : _
    hem₁-6 = seg3 (sym (topFace (d m i) (hexagon (suc m) (fsuc j) (fsuc k) (fsuc l) (wk≤fs 0 (weakenN 0 j) (weakenN 0 k) (weaken≤N 0 j k (q))) (wk≤fs 0 (weakenN 0 k) (weakenN 0 l) (weaken≤N 0 k l (s))) x))) (e17 ∙ e18 ∙ e15 ∙ refl)
    hem₁ : _
    hem₁ = hem₁-1 ∙ hem₁-2 ∙ hem₁-3 ∙ hem₁-4 ∙ hem₁-5 ∙ hem₁-6
    hem₂-1 : _
    hem₂-1 = cong (λ z → e0 ∙ e1 ∙ z) (seg2 (homotopyNatural {f = (λ y → d m j (d (suc m) (fsuc k) y))} {g = (λ y → d m k (d (suc m) (weaken j) y))} (λ y → sid m j k (wk≤fs 0 (weakenN 0 j) (weakenN 0 k) (weaken≤N 0 j k (q))) y) (sid (suc (suc m)) (weaken (weaken i)) (fsuc (fsuc l)) (wk≤fs 2 (weakenN 0 i) (weakenN 0 l) (weaken≤N 0 i l (≤F-trans i k l (≤F-trans i j k p q) s))) x)) (e4 ∙ e5 ∙ refl))
    hem₂-2 : _
    hem₂-2 = cong (λ z → e0 ∙ e1 ∙ e22 ∙ z) (seg3 (sym (hexagon m j k l (wk≤fs 0 (weakenN 0 j) (weakenN 0 k) (weaken≤N 0 j k (q))) (wk≤fs 0 (weakenN 0 k) (weakenN 0 l) (weaken≤N 0 k l (s))) (d (suc (suc (suc m))) (weaken (weaken (weaken i))) x))) (refl))
    hem₂-3 : _
    hem₂-3 = cong (λ z → e0 ∙ z) (seg3 (sym (topFace (d m j) (hexagon (suc m) (weaken i) (fsuc k) (fsuc l) (wk≤fs 1 (weakenN 0 i) (weakenN 0 k) (weaken≤N 0 i k (≤F-trans i j k p q))) (wk≤fs 0 (weakenN 0 k) (weakenN 0 l) (weaken≤N 0 k l (s))) x))) (e25 ∙ e26 ∙ refl))
    hem₂-4 : _
    hem₂-4 = seg2 (homotopyNatural {f = (λ y → d m i (d (suc m) (fsuc j) y))} {g = (λ y → d m j (d (suc m) (weaken i) y))} (λ y → sid m i j (wk≤fs 0 (weakenN 0 i) (weakenN 0 j) (weaken≤N 0 i j (p))) y) (sid (suc (suc m)) (fsuc (fsuc k)) (fsuc (fsuc l)) (wk≤fs 0 (weakenN 0 k) (weakenN 0 l) (weaken≤N 0 k l (s))) x)) (e28 ∙ e29 ∙ e25 ∙ e26 ∙ refl)
    hem₂-5 : _
    hem₂-5 = cong (λ z → e19 ∙ e30 ∙ e28 ∙ z) (seg2 (sym (homotopyNatural {f = (λ y → d m j (d (suc m) (fsuc l) y))} {g = (λ y → d m l (d (suc m) (weaken j) y))} (λ y → sid m j l (wk≤fs 0 (weakenN 0 j) (weakenN 0 l) (weaken≤N 0 j l (≤F-trans j k l q s))) y) (sid (suc (suc m)) (weaken (weaken i)) (fsuc (weaken k)) (wk≤fs 1 (weakenN 1 i) (weakenN 1 k) (weaken≤N 1 i k (≤F-trans i j k p q))) x))) (e26 ∙ refl))
    hem₂-6 : _
    hem₂-6 = cong (λ z → e19 ∙ z) (seg3 (sym (hexagon m i j l (wk≤fs 0 (weakenN 0 i) (weakenN 0 j) (weaken≤N 0 i j (p))) (wk≤fs 0 (weakenN 0 j) (weakenN 0 l) (weaken≤N 0 j l (≤F-trans j k l q s))) (d (suc (suc (suc m))) (fsuc (fsuc (weaken k))) x))) (e32 ∙ e26 ∙ refl))
    hem₂-7 : _
    hem₂-7 = cong (λ z → e19 ∙ e20 ∙ e33 ∙ z) (seg3 (sym (topFace (d m l) (hexagon (suc m) (weaken i) (weaken j) (weaken k) (wk≤fs 0 (weakenN 1 i) (weakenN 1 j) (weaken≤N 1 i j (p))) (wk≤fs 0 (weakenN 1 j) (weakenN 1 k) (weaken≤N 1 j k (q))) x))) (refl))
    hem₂-8 : _
    hem₂-8 = cong (λ z → e19 ∙ e20 ∙ z) (seg2 (homotopyNatural {f = (λ y → d m i (d (suc m) (fsuc l) y))} {g = (λ y → d m l (d (suc m) (weaken i) y))} (λ y → sid m i l (wk≤fs 0 (weakenN 0 i) (weakenN 0 l) (weaken≤N 0 i l (≤F-trans i k l (≤F-trans i j k p q) s))) y) (sid (suc (suc m)) (fsuc (weaken j)) (fsuc (weaken k)) (wk≤fs 0 (weakenN 1 j) (weakenN 1 k) (weaken≤N 1 j k (q))) x)) (e18 ∙ e15 ∙ refl))
    hem₂ : _
    hem₂ = hem₂-1 ∙ hem₂-2 ∙ hem₂-3 ∙ hem₂-4 ∙ hem₂-5 ∙ hem₂-6 ∙ hem₂-7 ∙ hem₂-8

Coh₃ : WildSSTᵢ₂ → Type
Coh₃ S = (m : ℕ) (i j k l : Fin (suc (suc m)))
  .(p : i ≤F j) .(q : j ≤F k) .(s : k ≤F l)
  (x : WildSSTᵢ.X (WildSSTᵢ₂.underlying S) (suc (suc (suc (suc m)))))
  → P4.hem₁ S m i j k l p q s x ≡ P4.hem₂ S m i j k l p q s x
