{-# OPTIONS --safe --cubical --guardedness #-}
{-
  GENERATED by gen_p4.py -- do not edit by hand.
  (Claude, session 7f138325, 2026-09-26; goal CG-003, gate G1)

  proof id : MP-CG001-WILD-SST-P4-001 (together with WildSSTP4.agda)
  claim    : CG001-C-68 (full statement in CLAIM-C68.md)

  The general second coherence Coh₃ of WildSSTP4.agda, evaluated on the
  degenerate structure flat of CG001-C-66 (points of S² in dimension 0,
  Unit above, every identity refl), with the two hexagon data of C-66:

  (a) notCoh₃   : ¬ Coh₃ flatSurfᵢ   (level-0 hexagon filler σr at (0,0,0))
  (b) coh₃Trivial : Coh₃ flatTrivialᵢ (every hexagon filler refl)

  This replaces the hand step of CLAIM-C66.md ("P₄ reduces to Deg₃ on
  flat"): the violation is now read off the general coherence itself.

  How the proof goes.  On flat at level 0 every edge of P₄ is refl, so every
  route is the same composite of refl's and every move is a loop.  Each move
  is  cong P (seg₂/₃ F T)  for a prefix P, a tail T and a face F; a move whose
  face is refl (after computation), topFace f refl, or homotopyNatural on
  constant maps is refl (natConst, seg-refl, topFace-refl).  At the instance
  m = 0, (i, j, k, l) = (0, 0, 0, 1) exactly one face carries a non-trivial
  filler: the level-0 hexagon at (i, j, k) = (0, 0, 0), in the first move of
  hem₁, which is  seg₃ (sym σr) T.  So Coh₃ gives  seg₃ (sym σr) T ≡ refl, and
  seg₃ is injective in its face (seg3-inj), hence σr ≡ refl, which C-66
  refutes (σr≢refl).
-}
module WildSSTP4Flat where

open import Cubical.Foundations.Prelude
open import Cubical.Foundations.GroupoidLaws using (lUnit ; rUnit ; lCancel ; rCancel ; assoc)
open import Cubical.Foundations.Function using (homotopyNatural)
open import Cubical.Foundations.Path using (compPathr-isEquiv)
open import Cubical.Functions.Embedding using (isEquiv→isEmbedding ; isEmbedding→Inj)
open import Cubical.Data.Nat using (ℕ ; zero ; suc)
open import Cubical.Data.Unit using (Unit ; tt)
open import Cubical.Data.Unit.Properties using (isOfHLevelUnit)
open import Cubical.Data.Sum using (inl ; inr)
open import Cubical.HITs.S2.Base using (S²) renaming (base to north)
open import Cubical.Relation.Nullary using (¬_)

open import WildSST using (Fin ; fzero ; fsuc ; _≤F_)
open import WildSST2 using (σr ; σr≢refl)
open import WildSSTP4

------------------------------------------------------------------------
-- Lemmas: trivial faces give trivial moves; seg₃ is injective in its face.

natConst : ∀ {ℓ ℓ'} {A : Type ℓ} {B : Type ℓ'} (b : B) {x y : A} (p : x ≡ y)
  → homotopyNatural {f = λ _ → b} {g = λ _ → b} (λ _ → refl) p ≡ refl
natConst b p t i j =
  hcomp (λ k → λ { (i = i0) → compPath-filler (refl {x = b}) refl k j
                 ; (i = i1) → compPath-filler' (refl {x = b}) refl k j
                 ; (j = i0) → b
                 ; (j = i1) → b
                 ; (t = i1) → compPath-filler (refl {x = b}) refl k j })
        b

module _ {ℓ : Level} {A : Type ℓ} where
  conj-triv : {u v : A} {Y : u ≡ u} (α : v ≡ u) → α ∙ Y ∙ sym α ≡ refl → Y ≡ refl
  conj-triv {Y = Y} α h =
    Y                                  ≡⟨ lUnit Y ⟩
    refl ∙ Y                           ≡⟨ cong (_∙ Y) (sym (lCancel α)) ⟩
    (sym α ∙ α) ∙ Y                    ≡⟨ sym (assoc (sym α) α Y) ⟩
    sym α ∙ α ∙ Y                      ≡⟨ cong (λ Z → sym α ∙ α ∙ Z) (rUnit Y) ⟩
    sym α ∙ α ∙ Y ∙ refl               ≡⟨ cong (λ Z → sym α ∙ α ∙ Y ∙ Z) (sym (lCancel α)) ⟩
    sym α ∙ α ∙ Y ∙ sym α ∙ α          ≡⟨ cong (λ Z → sym α ∙ α ∙ Z) (assoc Y (sym α) α) ⟩
    sym α ∙ α ∙ (Y ∙ sym α) ∙ α        ≡⟨ cong (sym α ∙_) (assoc α (Y ∙ sym α) α) ⟩
    sym α ∙ (α ∙ Y ∙ sym α) ∙ α        ≡⟨ cong (λ Z → sym α ∙ Z ∙ α) h ⟩
    sym α ∙ refl ∙ α                   ≡⟨ cong (sym α ∙_) (sym (lUnit α)) ⟩
    sym α ∙ α                          ≡⟨ lCancel α ⟩
    refl                               ∎


module _ {ℓ : Level} {A : Type ℓ} where
  seg2-refl : {w x z v : A} {a : w ≡ x} {b : x ≡ z} (T : z ≡ v)
            → seg2 {a = a} {b} {a' = a} {b' = b} refl T ≡ refl
  seg2-refl {a = a} {b} T =
    cong (assoc a b T ∙_) (sym (lUnit (sym (assoc a b T)))) ∙ rCancel (assoc a b T)

  seg3-refl : {w x y z v : A} {a : w ≡ x} {b : x ≡ y} {c : y ≡ z} (T : z ≡ v)
            → seg3 {a = a} {b} {c} {a' = a} {b' = b} {c' = c} refl T ≡ refl
  seg3-refl {a = a} {b} {c} T = cong (α ∙_) (sym (lUnit (sym α))) ∙ rCancel α
    where
    α = cong (a ∙_) (assoc b c T) ∙ assoc a (b ∙ c) T

  seg3-inj : {w x y z v : A} {a : w ≡ x} {b : x ≡ y} {c : y ≡ z} (T : z ≡ v)
             (F : a ∙ b ∙ c ≡ a ∙ b ∙ c) → seg3 F T ≡ refl → F ≡ refl
  seg3-inj {a = a} {b} {c} T F h =
    isEmbedding→Inj
      (isEquiv→isEmbedding (isEquiv→isEmbedding (compPathr-isEquiv T) (a ∙ b ∙ c) (a ∙ b ∙ c)))
      F refl (conj-triv α h)
    where
    α = cong (a ∙_) (assoc b c T) ∙ assoc a (b ∙ c) T

  ∙-triv : {u : A} {p q : u ≡ u} → p ≡ refl → q ≡ refl → p ∙ q ≡ refl
  ∙-triv ep eq = cong₂ _∙_ ep eq ∙ sym (rUnit refl)

module _ {ℓ ℓ' : Level} {A : Type ℓ} {C : Type ℓ'} where
  mv2-triv : {w x z v : A} {a : w ≡ x} {b : x ≡ z} (P : (w ≡ v) → C) (T : z ≡ v)
             {F : a ∙ b ≡ a ∙ b} → F ≡ refl → cong P (seg2 F T) ≡ refl
  mv2-triv P T e = cong (λ Y → cong P (seg2 Y T)) e ∙ cong (cong P) (seg2-refl T)

  mv3-triv : {w x y z v : A} {a : w ≡ x} {b : x ≡ y} {c : y ≡ z} (P : (w ≡ v) → C) (T : z ≡ v)
             {F : a ∙ b ∙ c ≡ a ∙ b ∙ c} → F ≡ refl → cong P (seg3 F T) ≡ refl
  mv3-triv P T e = cong (λ Y → cong P (seg3 Y T)) e ∙ cong (cong P) (seg3-refl T)

module _ {ℓ ℓ' : Level} {A : Type ℓ} {B : Type ℓ'} where
  topFace-refl : (f : A → B) {w x y z : A} {a : w ≡ x} {b : x ≡ y} {c : y ≡ z}
    → topFace f {a = a} {b} {c} {a' = a} {b' = b} {c' = c} refl ≡ refl
  topFace-refl f {a = a} {b} {c} = cong (sym C ∙_) (sym (lUnit C)) ∙ lCancel C
    where
    C = congFunct₃ f a b c

------------------------------------------------------------------------
-- flat (the same clauses as WildSST2.flat) and its two hexagon data.

flatᵢ : WildSSTᵢ
WildSSTᵢ.X flatᵢ zero = S²
WildSSTᵢ.X flatᵢ (suc n) = Unit
WildSSTᵢ.d flatᵢ zero _ _ = north
WildSSTᵢ.d flatᵢ (suc n) _ _ = tt
WildSSTᵢ.sid flatᵢ zero _ _ _ _ = refl
WildSSTᵢ.sid flatᵢ (suc n) _ _ _ _ = refl

cohTrivialᵢ : Coh₂ᵢ flatᵢ
cohTrivialᵢ zero i j k _ _ x = refl
cohTrivialᵢ (suc m) i j k _ _ x = refl

cohSurfᵢ : Coh₂ᵢ flatᵢ
cohSurfᵢ zero (inl _) (inl _) (inl _) _ _ x = σr
cohSurfᵢ zero i j k _ _ x = refl
cohSurfᵢ (suc m) i j k _ _ x = refl

flatTrivialᵢ flatSurfᵢ : WildSSTᵢ₂
flatTrivialᵢ = record { underlying = flatᵢ ; hexagon = cohTrivialᵢ }
flatSurfᵢ    = record { underlying = flatᵢ ; hexagon = cohSurfᵢ }

------------------------------------------------------------------------
-- (a) The instance m = 0, (i, j, k, l) = (0, 0, 0, 1) on flatSurfᵢ.

module AtSurf where
  triv-hem₁-2 : P4.hem₁-2 flatSurfᵢ zero fzero fzero fzero (fsuc fzero) tt tt tt tt ≡ refl
  triv-hem₁-2 = mv3-triv (λ (z : north ≡ north) → refl ∙ refl ∙ z) (refl {x = north} ∙ refl) (cong sym (topFace-refl (λ (_ : Unit) → north) {a = refl} {b = refl} {c = refl}))
  triv-hem₁-3 : P4.hem₁-3 flatSurfᵢ zero fzero fzero fzero (fsuc fzero) tt tt tt tt ≡ refl
  triv-hem₁-3 = mv2-triv (λ (z : north ≡ north) → refl ∙ z) (refl {x = north} ∙ refl ∙ refl ∙ refl) (natConst north {x = tt} {y = tt} refl)
  triv-hem₁-4 : P4.hem₁-4 flatSurfᵢ zero fzero fzero fzero (fsuc fzero) tt tt tt tt ≡ refl
  triv-hem₁-4 = mv2-triv (λ (z : north ≡ north) → refl ∙ refl ∙ refl ∙ refl ∙ z) (refl {x = north}) (cong sym (natConst north {x = tt} {y = tt} refl))
  triv-hem₁-5 : P4.hem₁-5 flatSurfᵢ zero fzero fzero fzero (fsuc fzero) tt tt tt tt ≡ refl
  triv-hem₁-5 = mv3-triv (λ (z : north ≡ north) → refl ∙ refl ∙ z) (refl {x = north} ∙ refl) refl
  triv-hem₁-6 : P4.hem₁-6 flatSurfᵢ zero fzero fzero fzero (fsuc fzero) tt tt tt tt ≡ refl
  triv-hem₁-6 = mv3-triv (λ (z : north ≡ north) → z) (refl {x = north} ∙ refl ∙ refl ∙ refl) (cong sym (topFace-refl (λ (_ : Unit) → north) {a = refl} {b = refl} {c = refl}))
  triv-hem₂-1 : P4.hem₂-1 flatSurfᵢ zero fzero fzero fzero (fsuc fzero) tt tt tt tt ≡ refl
  triv-hem₂-1 = mv2-triv (λ (z : north ≡ north) → refl ∙ refl ∙ z) (refl {x = north} ∙ refl ∙ refl) (natConst north {x = tt} {y = tt} refl)
  triv-hem₂-2 : P4.hem₂-2 flatSurfᵢ zero fzero fzero fzero (fsuc fzero) tt tt tt tt ≡ refl
  triv-hem₂-2 = mv3-triv (λ (z : north ≡ north) → refl ∙ refl ∙ refl ∙ z) (refl {x = north}) refl
  triv-hem₂-3 : P4.hem₂-3 flatSurfᵢ zero fzero fzero fzero (fsuc fzero) tt tt tt tt ≡ refl
  triv-hem₂-3 = mv3-triv (λ (z : north ≡ north) → refl ∙ z) (refl {x = north} ∙ refl ∙ refl) (cong sym (topFace-refl (λ (_ : Unit) → north) {a = refl} {b = refl} {c = refl}))
  triv-hem₂-4 : P4.hem₂-4 flatSurfᵢ zero fzero fzero fzero (fsuc fzero) tt tt tt tt ≡ refl
  triv-hem₂-4 = mv2-triv (λ (z : north ≡ north) → z) (refl {x = north} ∙ refl ∙ refl ∙ refl ∙ refl) (natConst north {x = tt} {y = tt} refl)
  triv-hem₂-5 : P4.hem₂-5 flatSurfᵢ zero fzero fzero fzero (fsuc fzero) tt tt tt tt ≡ refl
  triv-hem₂-5 = mv2-triv (λ (z : north ≡ north) → refl ∙ refl ∙ refl ∙ z) (refl {x = north} ∙ refl) (cong sym (natConst north {x = tt} {y = tt} refl))
  triv-hem₂-6 : P4.hem₂-6 flatSurfᵢ zero fzero fzero fzero (fsuc fzero) tt tt tt tt ≡ refl
  triv-hem₂-6 = mv3-triv (λ (z : north ≡ north) → refl ∙ z) (refl {x = north} ∙ refl ∙ refl) refl
  triv-hem₂-7 : P4.hem₂-7 flatSurfᵢ zero fzero fzero fzero (fsuc fzero) tt tt tt tt ≡ refl
  triv-hem₂-7 = mv3-triv (λ (z : north ≡ north) → refl ∙ refl ∙ refl ∙ z) (refl {x = north}) (cong sym (topFace-refl (λ (_ : Unit) → north) {a = refl} {b = refl} {c = refl}))
  triv-hem₂-8 : P4.hem₂-8 flatSurfᵢ zero fzero fzero fzero (fsuc fzero) tt tt tt tt ≡ refl
  triv-hem₂-8 = mv2-triv (λ (z : north ≡ north) → refl ∙ refl ∙ z) (refl {x = north} ∙ refl ∙ refl) (natConst north {x = tt} {y = tt} refl)

  rest₁ : _
  rest₁ = ∙-triv triv-hem₁-2 (∙-triv triv-hem₁-3 (∙-triv triv-hem₁-4 (∙-triv triv-hem₁-5 (triv-hem₁-6))))

  all₂ : P4.hem₂ flatSurfᵢ zero fzero fzero fzero (fsuc fzero) tt tt tt tt ≡ refl
  all₂ = ∙-triv triv-hem₂-1 (∙-triv triv-hem₂-2 (∙-triv triv-hem₂-3 (∙-triv triv-hem₂-4 (∙-triv triv-hem₂-5 (∙-triv triv-hem₂-6 (∙-triv triv-hem₂-7 (triv-hem₂-8)))))))

notCoh₃ : ¬ Coh₃ flatSurfᵢ
notCoh₃ h = σr≢refl (cong sym (seg3-inj (refl {x = north} ∙ refl ∙ refl ∙ refl) (sym σr) key))
  where
  open AtSurf
  key : P4.hem₁-1 flatSurfᵢ zero fzero fzero fzero (fsuc fzero) tt tt tt tt ≡ refl
  key = rUnit _ ∙ cong (P4.hem₁-1 flatSurfᵢ zero fzero fzero fzero (fsuc fzero) tt tt tt tt ∙_) (sym rest₁)
      ∙ h zero fzero fzero fzero (fsuc fzero) tt tt tt tt ∙ all₂

------------------------------------------------------------------------
-- (b) flatTrivialᵢ satisfies Coh₃: at level 0 every move is refl (for all
-- indices); above level 0 the simplices form Unit, a groupoid.

module AtTrivial (i j k l : Fin 2) .(p : i ≤F j) .(q : j ≤F k) .(s : k ≤F l) (x : Unit) where
  triv-hem₁-1 : P4.hem₁-1 flatTrivialᵢ zero i j k l p q s x ≡ refl
  triv-hem₁-1 = mv3-triv (λ (z : north ≡ north) → z) (refl {x = north} ∙ refl ∙ refl ∙ refl) refl
  triv-hem₁-2 : P4.hem₁-2 flatTrivialᵢ zero i j k l p q s x ≡ refl
  triv-hem₁-2 = mv3-triv (λ (z : north ≡ north) → refl ∙ refl ∙ z) (refl {x = north} ∙ refl) (cong sym (topFace-refl (λ (_ : Unit) → north) {a = refl} {b = refl} {c = refl}))
  triv-hem₁-3 : P4.hem₁-3 flatTrivialᵢ zero i j k l p q s x ≡ refl
  triv-hem₁-3 = mv2-triv (λ (z : north ≡ north) → refl ∙ z) (refl {x = north} ∙ refl ∙ refl ∙ refl) (natConst north {x = tt} {y = tt} refl)
  triv-hem₁-4 : P4.hem₁-4 flatTrivialᵢ zero i j k l p q s x ≡ refl
  triv-hem₁-4 = mv2-triv (λ (z : north ≡ north) → refl ∙ refl ∙ refl ∙ refl ∙ z) (refl {x = north}) (cong sym (natConst north {x = tt} {y = tt} refl))
  triv-hem₁-5 : P4.hem₁-5 flatTrivialᵢ zero i j k l p q s x ≡ refl
  triv-hem₁-5 = mv3-triv (λ (z : north ≡ north) → refl ∙ refl ∙ z) (refl {x = north} ∙ refl) refl
  triv-hem₁-6 : P4.hem₁-6 flatTrivialᵢ zero i j k l p q s x ≡ refl
  triv-hem₁-6 = mv3-triv (λ (z : north ≡ north) → z) (refl {x = north} ∙ refl ∙ refl ∙ refl) (cong sym (topFace-refl (λ (_ : Unit) → north) {a = refl} {b = refl} {c = refl}))
  triv-hem₂-1 : P4.hem₂-1 flatTrivialᵢ zero i j k l p q s x ≡ refl
  triv-hem₂-1 = mv2-triv (λ (z : north ≡ north) → refl ∙ refl ∙ z) (refl {x = north} ∙ refl ∙ refl) (natConst north {x = tt} {y = tt} refl)
  triv-hem₂-2 : P4.hem₂-2 flatTrivialᵢ zero i j k l p q s x ≡ refl
  triv-hem₂-2 = mv3-triv (λ (z : north ≡ north) → refl ∙ refl ∙ refl ∙ z) (refl {x = north}) refl
  triv-hem₂-3 : P4.hem₂-3 flatTrivialᵢ zero i j k l p q s x ≡ refl
  triv-hem₂-3 = mv3-triv (λ (z : north ≡ north) → refl ∙ z) (refl {x = north} ∙ refl ∙ refl) (cong sym (topFace-refl (λ (_ : Unit) → north) {a = refl} {b = refl} {c = refl}))
  triv-hem₂-4 : P4.hem₂-4 flatTrivialᵢ zero i j k l p q s x ≡ refl
  triv-hem₂-4 = mv2-triv (λ (z : north ≡ north) → z) (refl {x = north} ∙ refl ∙ refl ∙ refl ∙ refl) (natConst north {x = tt} {y = tt} refl)
  triv-hem₂-5 : P4.hem₂-5 flatTrivialᵢ zero i j k l p q s x ≡ refl
  triv-hem₂-5 = mv2-triv (λ (z : north ≡ north) → refl ∙ refl ∙ refl ∙ z) (refl {x = north} ∙ refl) (cong sym (natConst north {x = tt} {y = tt} refl))
  triv-hem₂-6 : P4.hem₂-6 flatTrivialᵢ zero i j k l p q s x ≡ refl
  triv-hem₂-6 = mv3-triv (λ (z : north ≡ north) → refl ∙ z) (refl {x = north} ∙ refl ∙ refl) refl
  triv-hem₂-7 : P4.hem₂-7 flatTrivialᵢ zero i j k l p q s x ≡ refl
  triv-hem₂-7 = mv3-triv (λ (z : north ≡ north) → refl ∙ refl ∙ refl ∙ z) (refl {x = north}) (cong sym (topFace-refl (λ (_ : Unit) → north) {a = refl} {b = refl} {c = refl}))
  triv-hem₂-8 : P4.hem₂-8 flatTrivialᵢ zero i j k l p q s x ≡ refl
  triv-hem₂-8 = mv2-triv (λ (z : north ≡ north) → refl ∙ refl ∙ z) (refl {x = north} ∙ refl ∙ refl) (natConst north {x = tt} {y = tt} refl)

  all₁ : P4.hem₁ flatTrivialᵢ zero i j k l p q s x ≡ refl
  all₁ = ∙-triv triv-hem₁-1 (∙-triv triv-hem₁-2 (∙-triv triv-hem₁-3 (∙-triv triv-hem₁-4 (∙-triv triv-hem₁-5 (triv-hem₁-6)))))

  all₂ : P4.hem₂ flatTrivialᵢ zero i j k l p q s x ≡ refl
  all₂ = ∙-triv triv-hem₂-1 (∙-triv triv-hem₂-2 (∙-triv triv-hem₂-3 (∙-triv triv-hem₂-4 (∙-triv triv-hem₂-5 (∙-triv triv-hem₂-6 (∙-triv triv-hem₂-7 (triv-hem₂-8)))))))

coh₃Trivial : Coh₃ flatTrivialᵢ
coh₃Trivial zero i j k l p q s x = AtTrivial.all₁ i j k l p q s x ∙ sym (AtTrivial.all₂ i j k l p q s x)
coh₃Trivial (suc m) i j k l p q s x = isOfHLevelUnit 3 _ _ _ _ _ _
