#!/usr/bin/env python3
"""Checkpoint P32 bounded discovery and route the 2LTT v5 boundary audit."""
from __future__ import annotations
import argparse, hashlib, importlib.util, json, re, sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]; OUT=Path(__file__).resolve().parent
SID='S-RES-20260921-ASTRA-P32-HOTT-SPECIFIC-DISCOVERY'; BASE=f'.codex/research/hott/sessions/{SID}/'; PLAN='R-HOTT-FOUR-TRACK-PLAN-20260921'; P31='R-P31-TT-PROVABILITY-TYPE-THEORY-CORPUS-20260921'; P32='R-P32-HOTT-SPECIFIC-REFLECTION-CONSUMER-DISCOVERY-20260921'; DIR='audit/p32-hott-specific-reflection-consumer-discovery-20260921'
SOURCES=(f'{DIR}/P32-HOTT-SPECIFIC-REFLECTION-CONSUMER-DISCOVERY-REPORT.md',f'{DIR}/P32-HOTT-SPECIFIC-REFLECTION-SOURCE-FREEZE.json',f'{DIR}/verify_p32_hott_specific_reflection_consumer_discovery.py',f'{DIR}/P32-HOTT-SPECIFIC-REFLECTION-CONSUMER-DISCOVERY-VERIFICATION.json')
def h(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def rt():
 s=importlib.util.spec_from_file_location('r',ROOT/'.codex/tools/cognition_runtime.py'); assert s and s.loader; m=importlib.util.module_from_spec(s); s.loader.exec_module(m); return m
def ed():
 sys.path.insert(0,str(ROOT/'scripts/audit')); import projection_edit; return projection_edit
def audit(core):
 rows=re.findall(r'^### (KC-\d+) · .*? · (.+)$',(ROOT/'核心认知.md').read_text(),re.M); assert len(rows)==46
 deep={'KC-000025','KC-000026','KC-000027','KC-000028','KC-000029','KC-000035','KC-000036','KC-000041','KC-000043','KC-000044','KC-000045','KC-000046'}
 x=f'# {SID} 核心认知回评\n\n{core["generation"]}；46 条；兼容单文件审计登记 `G-V5-SESSION-AUDIT-SHARD-WRITE-GAP-001`。\n\n- core_change: NO\n- direction_change: P32 double-condition discovery closed; P33 2LTT v5 boundary audit next.\n- panorama_change: source discovery boundary and known defenses recorded.\n- essay_change: NO\n- update_decision: do not confuse h-prop reflection or host reflection with self-metatheory.\n- cross_conflicts: no qualified HoTT actual reflection consumer, defect or O6 bridge established.\n- unresolved: P33 precise 2LTT v5 scope and future source ingress.\n- writer_compatibility: G-V5-SESSION-AUDIT-SHARD-WRITE-GAP-001.\n\n| KC | 主题 | relation | 本单元判断 | 证据、反证条件 |\n|---|---|---|---|---|\n'
 for kc,title in rows:
  rel='DEEPENED' if kc in deep else 'NOT_TOUCHED'; a='P32分离HoTT self-metatheory、h-prop reflection与actual consumer。' if rel=='DEEPENED' else '本单元未直接检验该用户原文。'; x+=f'| `{kc}` | {title} | `{rel}` | {a} | P32 report；P33可修正边界。 |\n'
 return x+'\n## 波次定位\n\nP32关闭严格discovery分母；P33审计当前2LTT v5一手边界，不把outer layer写成同层缺陷。\n'
def main():
 ap=argparse.ArgumentParser(); ap.add_argument('--apply',action='store_true'); a=ap.parse_args(); r=rt(); e=ed(); assert all((ROOT/x).is_file() for x in SOURCES); assert json.loads((ROOT/SOURCES[-1]).read_text())['status']=='PASS_WITH_SCOPE'
 st=json.loads((ROOT/r.STATE).read_text()); assert st['revision']==248 and st['latest_session']=='S-RES-20260921-ASTRA-P31-TT-PROVABILITY-CORPUS'; hd=json.loads((ROOT/r.HEAD).read_text()); assert all(h(ROOT/p)==v for p,v in hd['tracked'].items()); pl=r.plan(ROOT,profile='research',task_ids=[PLAN]); (OUT/'P32-CHECKPOINT-PLAN.json').write_bytes(r.dump(pl)); st['revision']=249; st['latest_session']=SID
 p=st['records'][PLAN]; p['related_records']=list(dict.fromkeys(p.get('related_records',[])+[P32,SID])); p['status']='four_track_p3_paused_p1_expression_p4_not_triggered_p22_parked_p33_2ltt_v5_boundary_audit_next'; p['evidence_status']='P3_PAUSED_SAME_CLASS / P1_MINIMAL_EXPRESSIBILITY_POSITIVE_CONTROL / P4_NOT_TRIGGERED_BY_TRANSLATION_GAP_ALONE / P22_GUARDED_BRIDGE_PARKED / P32_HOTT_SPECIFIC_DISCOVERY_NO_QUALIFIED_CONSUMER / P33_2LTT_V5_BOUNDARY_AUDIT_NEXT / GOAL_ACTIVE'; p['full_sources']=list(dict.fromkeys(p.get('full_sources',[])+list(SOURCES))); p['source_hashes'].update({x:h(ROOT/x) for x in p['full_sources'] if (ROOT/x).is_file()}); p['revalidation']=p.get('revalidation','')+' Revision249 records P32 bounded HoTT-specific discovery and selects P33 2LTT v5 boundary audit; P31 scope unchanged.'
 st['records'][P32]={'kind':'result','path':SOURCES[0],'lifecycle_status':'CURRENT','evidence_status':'CLOSE_WITH_SCOPE / NO_QUALIFIED_DOUBLE_CONDITION_SOURCE_WITHIN_DECLARED_DENOMINATOR / KNOWN_SELF_METATHEORY_BOUNDARIES_RECONFIRMED / P33_2LTT_V5_BOUNDARY_AUDIT_SELECTED / NO_NEW_HOTT_DEFECT_CLAIM','status':'complete_with_scope','depends_on':[],'related_records':[PLAN,P31,SID],'full_sources':list(SOURCES),'source_hashes':{x:h(ROOT/x) for x in SOURCES},'scope':'Bounded local/public discovery; no full source audit, global absence claim, or HoTT theorem.'}; st['records'][SID]={'kind':'session','path':BASE+'SESSION.md','lifecycle_status':'HISTORICAL','evidence_status':'P32_CHECKPOINTED_WITH_SCOPE','status':'complete_with_scope','depends_on':[],'related_records':[PLAN,P31,P32],'full_sources':[BASE+x for x in ('SESSION.md','RUNS.json','CORE_COGNITION_AUDIT.md')]}
 st['execution_control'].update({'status':'FOUR_TRACK_P3_PAUSED_P1_EXPRESSIBLE_P4_NOT_TRIGGERED_P22_PARKED_P33_2LTT_V5_BOUNDARY_AUDIT_NEXT','current_phase':'PHASE_2_P32_HOTT_SPECIFIC_DISCOVERY_P33_2LTT_V5_BOUNDARY_AUDIT_NEXT','second_phase_status':'P3_PAUSED_P1_POSITIVE_CONTROL_P4_NOT_TRIGGERED_GUARD_PARKED_P33_NEXT','last_checkpoint_session':SID,'checkpoint_result':f'.codex/cognition/checkpoints/{SID}/result.json','next_minimal_verification':'P33-2LTT-V5-SELF-METATHEORY-BOUNDARY-AUDIT-2026-001. Read current arXiv 1705.03307v5 full text and locate the corresponding official code/artifact if available. Freeze exact inner/outer calculi, statements claimed not expressible in bare HoTT, proof/evidence status, and any relation to O1–O6, actual consumer K, and original X. Do not turn the use of an outer strict layer into a HoTT defect or reality-task result.'}); st['projection']['status']='FOUR_TRACK_P3_PAUSED_P1_EXPRESSIBLE_P4_NOT_TRIGGERED_GUARD_PARKED / P32_NO_QUALIFIED_HOTT_CONSUMER_IN_SCOPE / NEXT_P33_2LTT_V5_BOUNDARY_AUDIT / GOAL_ACTIVE / NO_NEW_HOTT_DEFECT_CLAIM'
 mem=e.load(ROOT,'MEMORY.md'); dire=e.load(ROOT,'方向追踪.md'); pan=e.load(ROOT,'全景视野.md'); essay=e.load(ROOT,'扩展认知.md')
 e.replace_in_shard(mem,'MEMORY/001 - 当前执行队列.md','P31 已审 `tt-provability@69de798`：有modal box/quotation/Löb syntax，但非HoTT、无可信object-provability/soundness/O6链，且Agda toolchain不可用。下一=P32：仅寻找同时具HoTT feature与实际reflection consumer的版本固定来源。P3/P1/P4/Guard继续停放。入口：`audit/p31-tt-provability-type-theory-corpus-20260921/P31-TT-PROVABILITY-TYPE-THEORY-CORPUS-REPORT.md`；revision248。','P32 已完成双条件HoTT-specific来源发现：官方问题、2LTT、HoTT-Agda/Cubical与h-prop reflection均未给同层actual consumer；下一=P33审计2LTT v5严格outer-layer边界。P3/P1/P4/Guard继续停放。入口：`audit/p32-hott-specific-reflection-consumer-discovery-20260921/P32-HOTT-SPECIFIC-REFLECTION-CONSUMER-DISCOVERY-REPORT.md`；revision249。'); e.append_to_shard(mem,'MEMORY/003 - 当前验证状态与顺序日志.md','\nS-RES-20260921-ASTRA-P32-HOTT-SPECIFIC-DISCOVERY：双条件来源发现无合格consumer，2LTT v5 P33 boundary audit next；revision249。\n')
 e.replace_in_index(dire,'source_state_revision: 248','source_state_revision: 249'); e.replace_in_index(dire,'projection_generation: 20260921-direction-248','projection_generation: 20260921-direction-249'); e.replace_in_index(dire,'semantic_status: FOUR_TRACK_P31_NON_HOTT_MODAL_LOB_P32_HOTT_DISCOVERY_NEXT','semantic_status: FOUR_TRACK_P32_NO_QUALIFIED_CONSUMER_P33_2LTT_V5_NEXT'); e.replace_in_shard(dire,'方向追踪/002 - 治理与用户方向.md','| `DIR-U-HOTT-FOUR-TRACK` | P31：非HoTT modal/Löb源码审计 | P30/P31 | `P32_HOTT_SPECIFIC_DISCOVERY_NEXT / GOAL_ACTIVE` | `PARADOX_DISCOVERY` | `OUT-HOTT-FOUR-TRACK-PLAN` | modal语法存在但非可信HoTT链；转向严格来源发现 | P31 report；revision248 |','| `DIR-U-HOTT-FOUR-TRACK` | P32：HoTT-specific双条件来源发现 | P31/P32 | `P33_2LTT_V5_BOUNDARY_AUDIT_NEXT / GOAL_ACTIVE` | `PARADOX_DISCOVERY` | `OUT-HOTT-FOUR-TRACK-PLAN` | scope内无合格consumer；审计2LTT outer-layer边界 | P32 report；revision249 |'); e.replace_in_shard(dire,'方向追踪/002 - 治理与用户方向.md','| `DIR-U-ABX-ORIGINAL-CIRCLE` | ABX 原圆环 P3 实际消费者分支停放 | P21/P31 | `P3_PAUSED / P32_HOTT_DISCOVERY` | `EVIDENCE_DISCIPLINE` | `OUT-ABX-ACTION-INTAKE` | 仅新版本固定实际 K 或强 R 才重开 | P21/P31 reports；revision248 |','| `DIR-U-ABX-ORIGINAL-CIRCLE` | ABX 原圆环 P3 实际消费者分支停放 | P21/P32 | `P3_PAUSED / P33_2LTT_BOUNDARY` | `EVIDENCE_DISCIPLINE` | `OUT-ABX-ACTION-INTAKE` | 仅新版本固定实际 K 或强 R 才重开 | P21/P32 reports；revision249 |')
 e.replace_in_index(pan,'source_state_revision: 248','source_state_revision: 249'); e.replace_in_index(pan,'projection_generation: 20260921-outcome-248','projection_generation: 20260921-outcome-249'); e.replace_in_index(pan,'semantic_status: FOUR_TRACK_P31_NON_HOTT_MODAL_LOB_P32_HOTT_DISCOVERY_NEXT','semantic_status: FOUR_TRACK_P32_NO_QUALIFIED_CONSUMER_P33_2LTT_V5_NEXT'); e.replace_in_shard(pan,'全景视野/003 - 当前机器证明包与原生重放.md','| `OUT-HOTT-FOUR-TRACK-PLAN` | P31 非HoTT modal/Löb source审计 | `DIR-U-HOTT-FOUR-TRACK` | P30/P31 | `P31_SCOPED / P32_NEXT` | modal syntax/trust boundary不等于HoTT self-validation | 不证明HoTT缺陷 | P31 report；revision248 |','| `OUT-HOTT-FOUR-TRACK-PLAN` | P32 HoTT-specific双条件来源发现 | `DIR-U-HOTT-FOUR-TRACK` | P31/P32 | `P32_SCOPED / P33_NEXT` | scope内无actual consumer；2LTT是边界而非命中 | 不证明HoTT缺陷 | P32 report；revision249 |'); e.replace_in_shard(pan,'全景视野/003 - 当前机器证明包与原生重放.md','| `OUT-ABX-ACTION-INTAKE` | ABX P3停放，独立 P31已审modal source | `DIR-U-ABX-ORIGINAL-CIRCLE` | P15/P17/P19/P20/P22/P25/P26/P27/P28/P29/P30/P31 | `P3_PAUSED / P32_HOTT_DISCOVERY` | 避免重复，保留新实际K重开条件 | 不证明原M/N桥 | P21/P31 reports；revision248 |','| `OUT-ABX-ACTION-INTAKE` | ABX P3停放，独立 P32已完成来源发现 | `DIR-U-ABX-ORIGINAL-CIRCLE` | P15/P17/P19/P20/P22/P25/P26/P27/P28/P29/P30/P31/P32 | `P3_PAUSED / P33_2LTT_BOUNDARY` | 避免重复，保留新实际K重开条件 | 不证明原M/N桥 | P21/P32 reports；revision249 |'); e.append_to_shard(pan,'全景视野/006 - ERCF-3 与 T3 脉冲及失败台账.md','\n## P32：HoTT-specific双条件来源发现（revision249）\n\n官方self-metatheory问题、2LTT、HoTT-Agda/Cubical与h-prop reflection均非同层actual consumer；P33核对2LTT v5边界。\n'); e.append_to_shard(pan,'全景视野/008 - 当前未完成.md','\n15. `P33-2LTT-V5-SELF-METATHEORY-BOUNDARY-AUDIT-2026-001`：审计2LTT v5关于bare HoTT可表达性、outer layer与实际consumer/O1–O6的精确边界。\n')
 simple={x:(ROOT/x).read_text() for x in r.MUTABLE if x not in {r.STATE,'MEMORY.md','方向追踪.md','全景视野.md','扩展认知.md'}}; simple[r.PREFIX+'FRONTIER.md']=simple[r.PREFIX+'FRONTIER.md'].replace('- P31确认`tt-provability@69de798`有modal/Löb syntax，但source的TODO/postulate/关闭检查/semantic hole使其不是可信HoTT self-validation；P32只搜HoTT-specific实际consumer。入口：`audit/p31-tt-provability-type-theory-corpus-20260921/P31-TT-PROVABILITY-TYPE-THEORY-CORPUS-REPORT.md`。','- P32严格来源发现没有找到同时具HoTT身份与actual self-reflection consumer的资产；2LTT v5提供outer-layer边界，P33需全文核对。入口：`audit/p32-hott-specific-reflection-consumer-discovery-20260921/P32-HOTT-SPECIFIC-REFLECTION-CONSUMER-DISCOVERY-REPORT.md`。',1); simple[r.PREFIX+'RESUME.md']=simple[r.PREFIX+'RESUME.md'].replace('当前 active goal 在P31后继续：`tt-provability@69de798`提供modal/Löb syntax但非HoTT，且其可信soundness未由可运行内核建立。P32按双维条件寻找版本固定HoTT-specific reflection consumer；不要重审P3/P1最小接口/跨后端/Guard停放分支。入口：`audit/p31-tt-provability-type-theory-corpus-20260921/P31-TT-PROVABILITY-TYPE-THEORY-CORPUS-REPORT.md`；revision248。','当前 active goal 在P32后继续：严格双条件来源发现没有得到actual HoTT self-reflection consumer；P33全文审计2LTT v5的inner/outer边界及其与O1–O6的关系。不要重审P3/P1最小接口/跨后端/Guard停放分支。入口：`audit/p32-hott-specific-reflection-consumer-discovery-20260921/P32-HOTT-SPECIFIC-REFLECTION-CONSUMER-DISCOVERY-REPORT.md`；revision249。',1)
 rows=[]
 for d in (mem,dire,pan,essay): rows+=e.payload_rows(d,ROOT)
 seen={x['path'] for x in rows}
 for rel in r.MUTABLE:
  if rel not in seen: rows.append({'path':rel,'expected_sha256':h(ROOT/rel),'text':r.dump(st).decode() if rel==r.STATE else simple[rel]})
 session=f'# {SID}\n\n- host: codex-desktop\n- model: runtime-model-not-certified-by-tool\n- tier: T3\n- status: `P32_CHECKPOINTED_WITH_SCOPE / P33_2LTT_V5_BOUNDARY_AUDIT_NEXT / NO_NEW_HOTT_DEFECT_CLAIM`\n- load_receipt: research plan snapshot `{pl["snapshot"]}`; local historic reflection investigation and bounded primary sources reviewed.\n- authorization: 用户已授权按 goal-3 持续推进、公开/本地侦察和 checkpoint；不启动 Sub Agent、不 push、不发布。\n'; runs={'schema_version':'hott-session-runs/v1','session_id':SID,'primary_runs':[{'kind':'P32 source-discovery verifier','result':'PASS_WITH_SCOPE'}],'new_math_claims':[],'new_kernel_replay':False}; rows += [{'path':BASE+'SESSION.md','expected_sha256':None,'text':session},{'path':BASE+'RUNS.json','expected_sha256':None,'text':r.dump(runs).decode()},{'path':BASE+'CORE_COGNITION_AUDIT.md','expected_sha256':None,'text':audit(st['current_core'])}]
 payload={'schema_version':'cognition-checkpoint/v1','session_id':SID,'load_profile':'research','task_ids':[PLAN],'authorization':'用户已授权按goal-3持续推进、公开/本地侦察和checkpoint；不启动Sub Agent、不push、不发布。','files':rows}; (OUT/'P32-CHECKPOINT-PAYLOAD.json').write_bytes(r.dump(payload)); res=r.checkpoint(ROOT,pl['snapshot'],payload,apply=a.apply); (OUT/('P32-CHECKPOINT-APPLY.json' if a.apply else 'P32-CHECKPOINT-DRY-RUN.json')).write_bytes(r.dump(res)); print(json.dumps({k:v for k,v in res.items() if k!='paths'},ensure_ascii=False,indent=2))
if __name__=='__main__': main()
