#!/usr/bin/env python3
"""Consolidate P19--P22 evidence into canonical current state."""
from __future__ import annotations
import argparse,hashlib,importlib.util,json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];OUT=Path(__file__).resolve().parent;SID='S-RES-20260921-ASTRA-P21-CROSS-BRANCH-SYNTHESIS';BASE=f'.codex/research/hott/sessions/{SID}/';PLAN='R-HOTT-FOUR-TRACK-PLAN-20260921';ABX='R-ABX-ACTION-20260921';P18='R-P18-FIFTH-SUCCESSOR-DISCOVERY-20260921';P19='R-P19-ORIGIN-DIRECTED-DIAGRAM-KERNELIZATION-20260921';P20='R-P20-CROSS-BACKEND-ORIGIN-INTERFACE-FIDELITY-20260921';P21='R-P21-CROSS-BRANCH-SYNTHESIS-20260921';P22='R-P22-GUARDED-CUBICAL-TRANSLATION-AUDIT-20260921'
R19='audit/p19-origin-directed-diagram-kernelization-20260921/P19-ORIGIN-DIRECTED-DIAGRAM-KERNELIZATION-REPORT.md';R20='audit/p20-cross-backend-origin-interface-fidelity-20260921/P20-CROSS-BACKEND-ORIGIN-INTERFACE-FIDELITY-REPORT.md';R21='audit/p21-cross-branch-synthesis-20260921/P21-CROSS-BRANCH-SYNTHESIS-REPORT.md';R22='audit/p22-guarded-cubical-translation-audit-20260921/P22-GUARDED-CUBICAL-TRANSLATION-AUDIT-REPORT.md';S=(R19,R20,R21,R22,'goal.md','goal-3.md','feature-list.md','rulings.md','HoTT后续研究总体方案.md','HoTT/formal/astra-breakpoint-check/OriginDirectedDiagram.agda','HoTT/verification/runs/20260921-MP-ASTRA-ORIGIN-DIRECTED-DIAGRAM-001-03/RUN.json','HoTT/CLAIM_EVIDENCE_MATRIX.md','HoTT/verification/PROOF_VERSION_CLOSURE.json','HoTT/formal/partiality-race-timeout/GuardErasure.agda')
def h(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def rw(t,p,v):
 a=t.splitlines()
 for i,x in enumerate(a):
  if x.startswith(p):a[i]=v;return '\n'.join(a)+'\n'
 raise AssertionError(p)
def audit(c):
 hs=re.findall(r'^### (KC-\d+) · .*? · (.+)$',(ROOT/'核心认知.md').read_text(),re.M);assert len(hs)==46;s=f'# {SID} 核心认知回评\n\n{c["generation"]}；46 条。\n\n- core_change: NO\n- direction_change: P3_PAUSED_P1_EXPRESSIBILITY_P4_NOT_TRIGGERED_P22_PARKED\n- panorama_change: C325_REGISTERED_AND_CROSS_BACKEND_GAP_SCOPED\n- essay_change: NO\n- update_decision: consolidate P19--P22 and select the next independent ingress rather than repeat parked branches.\n- cross_conflicts: no actual K/HoTT defect established.\n- unresolved: P23 independent ingress selection, actual K and theory defect remain open.\n- writer_compatibility: G-V5-SESSION-AUDIT-SHARD-WRITE-GAP-001.\n\n| KC | 主题 | relation | 本单元判断 | 证据、反证条件 |\n|---|---|---|---|---|\n'
 for k,t in hs:s+=f'| `{k}` | {t} | NOT_TOUCHED | P21 consolidation. | P19--P22 reports；new direct evidence可改变。 |\n'
 return s+'\n## 波次定位\n\nP21把P3停放、P1正控制、P4门槛和P22停放写回当前真值；P23需选独立入口。\n'
def main():
 a=argparse.ArgumentParser();a.add_argument('--apply',action='store_true');x=a.parse_args();assert all((ROOT/q).is_file()for q in S);sp=importlib.util.spec_from_file_location('r',ROOT/'.codex/tools/cognition_runtime.py');r=importlib.util.module_from_spec(sp);sp.loader.exec_module(r);st=json.loads((ROOT/r.STATE).read_text());assert st['revision']==238 and st['latest_session']=='S-RES-20260921-ASTRA-P18-FIFTH-SUCCESSOR-DISCOVERY';head=json.loads((ROOT/r.HEAD).read_text());assert all(h(ROOT/q)==v for q,v in head['tracked'].items());pl=r.plan(ROOT,profile='research',task_ids=[PLAN]);(OUT/'P21-CHECKPOINT-PLAN.json').write_bytes(r.dump(pl));st['revision']=239;st['latest_session']=SID
 for q in(PLAN,ABX,P18):
  v=st['records'][q];v['related_records']=list(dict.fromkeys(v.get('related_records',[])+[P19,P20,P21,P22,SID]));v['revalidation']=v.get('revalidation','')+' Revision239 consolidates P19--P22; prior source scope unchanged.'
 p=st['records'][PLAN];p.update(status='four_track_p3_paused_p1_expression_p4_not_triggered_p22_parked_p23_next',evidence_status='P3_PAUSED_SAME_CLASS / P1_MINIMAL_EXPRESSIBILITY_POSITIVE_CONTROL / P4_NOT_TRIGGERED_BY_TRANSLATION_GAP_ALONE / P22_GUARDED_BRIDGE_PARKED / P23_INDEPENDENT_INGRESS_DISCOVERY_NEXT / GOAL_ACTIVE');p['full_sources']=list(dict.fromkeys(p.get('full_sources',[])+list(S)));p['source_hashes'].update({q:h(ROOT/q)for q in p['full_sources']if(ROOT/q).is_file()})
 specs=[(P19,R19,'MINIMAL_ORIGIN_STRUCTURE_EXPRESSIBLE_WITH_SCOPE / P20_CROSS_BACKEND_FIDELITY_NEXT'),(P20,R20,'NO_REGISTERED_FIELD_PRESERVING_TRANSLATION_WITHIN_DECLARED_DENOMINATOR / P21_SYNTHESIS_NEXT'),(P21,R21,'P3_PAUSED_SAME_CLASS / GUARDED_CUBICAL_TRANSLATION_CANDIDATE_SELECTED / P22_COMPLETE'),(P22,R22,'NO_EXPLICIT_GCTT_TO_BARE_HOTT_FORGETFUL_ROUTE_WITHIN_FIXED_SOURCE / PARK_PENDING_CONCRETE_STANDARD_TRANSLATION_TARGET')]
 for ident,path,status in specs:st['records'][ident]={'kind':'result','path':path,'lifecycle_status':'CURRENT','evidence_status':status,'status':'complete_with_scope','depends_on':[],'related_records':[PLAN,ABX,P18],'full_sources':[path],'source_hashes':{path:h(ROOT/path)},'scope':'See fixed audit report; no general HoTT defect claim.'}
 st['records'][SID]={'kind':'session','path':BASE+'SESSION.md','lifecycle_status':'HISTORICAL','evidence_status':'P19_TO_P22_CONSOLIDATION_CHECKPOINTED_WITH_SCOPE','status':'complete_with_scope','depends_on':[],'related_records':[P19,P20,P21,P22,PLAN,ABX],'full_sources':[BASE+n for n in('SESSION.md','RUNS.json','CORE_COGNITION_AUDIT.md')]}
 st['execution_control'].update(status='FOUR_TRACK_P3_PAUSED_P1_EXPRESSIBLE_P4_NOT_TRIGGERED_P22_PARKED_P23_NEXT',current_phase='PHASE_2_P21_CONSOLIDATED_P23_INDEPENDENT_INGRESS_DISCOVERY_NEXT',second_phase_status='P3_PAUSED_P1_POSITIVE_CONTROL_P4_NOT_TRIGGERED_GUARD_PARKED_P23_NEXT',last_checkpoint_session=SID,checkpoint_result=f'.codex/cognition/checkpoints/{SID}/result.json',next_minimal_verification='P23-INDEPENDENT-INGRESS-DISCOVERY-001. Select one independent, version-pinned ingress outside P3 repeated consumers, minimal P1 interface expression, cross-backend gap, and guarded-to-bare bridge. Perform fresh public/community and local/historical reconnaissance; freeze Input/Operation/Observation/Done and the reason it can change the final witness chain. Do not re-audit parked branches.')
 st['projection']['status']='FOUR_TRACK_P3_PAUSED_P1_EXPRESSIBLE_P4_NOT_TRIGGERED_GUARD_PARKED / NEXT_P23_INDEPENDENT_INGRESS_DISCOVERY / GOAL_ACTIVE / NO_NEW_HOTT_DEFECT_CLAIM'
 dr='| `DIR-U-HOTT-FOUR-TRACK` | P21综合：P3停放/P1正控制/P4未触发/Guard停放 | 反漂移综合 | `P23_INDEPENDENT_INGRESS_NEXT / GOAL_ACTIVE` | `PARADOX_DISCOVERY` | P19–P22 | P23选独立入口 | P21 report；revision239 |';ar='| `DIR-U-ABX-ORIGINAL-CIRCLE` | ABX P21停放消费者扫描 | P21 | `P3_PAUSED / P23_NEXT` | `EVIDENCE_DISCIPLINE` | P15/P17 | 等待新实际K | P21 report；revision239 |';pr='| `OUT-HOTT-FOUR-TRACK-PLAN` | P21跨支综合 | `DIR-U-HOTT-FOUR-TRACK` | P19–P22 | `P3_PAUSED / P23_NEXT` | 表达性/桥缺口/guard分层 | 不证明缺陷 | P21 report；revision239 |';ap='| `OUT-ABX-ACTION-INTAKE` | ABX P21综合停放 | `DIR-U-ABX-ORIGINAL-CIRCLE` | P15/P17/P19/P20/P22 | `P3_PAUSED / P23_NEXT` | 避免重复 | 不证明原M/N桥 | P21 report；revision239 |';mem='P21已将P19–P22同步：P1最小结构可表达，P3同类consumer暂停，P4不因缺翻译触发，Guarded→bare桥停放待实际target。当前P23需选独立新入口并做公开/本地侦察；不重审停放分支。入口：`audit/p21-cross-branch-synthesis-20260921/P21-CROSS-BRANCH-SYNTHESIS-REPORT.md`；revision239。';fr='- P21已同步：P3暂停、P1表达性正控制、P4未触发、Guard桥停放。P23选择独立新入口；不重审停放分支。入口：`audit/p21-cross-branch-synthesis-20260921/P21-CROSS-BRANCH-SYNTHESIS-REPORT.md`。';rs='当前 active goal 在P21后继续：P23选择一个独立版本冻结入口，做公开/本地侦察并固定Input/Operation/Observation/Done；不重审P3/P1最小接口/跨后端/Guard停放分支。入口：`audit/p21-cross-branch-synthesis-20260921/P21-CROSS-BRANCH-SYNTHESIS-REPORT.md`；revision239。'
 fs=[]
 for rel in list(r.MUTABLE)+list(r.mutable_shard_paths(ROOT)):
  raw=(ROOT/rel).read_bytes();t=raw.decode()
  if rel==r.STATE:t=r.dump(st).decode()
  elif rel==r.DIRECTION:t=t.replace('source_state_revision: 238','source_state_revision: 239',1).replace('projection_generation: 20260921-direction-238','projection_generation: 20260921-direction-239',1).replace('semantic_status: FOUR_TRACK_P18_SWITCH_TO_P1_OBJECT_THEORY_P19_NEXT','semantic_status: FOUR_TRACK_P21_CONSOLIDATED_P23_NEXT',1)
  elif rel==r.PANORAMA:t=t.replace('source_state_revision: 238','source_state_revision: 239',1).replace('projection_generation: 20260921-outcome-238','projection_generation: 20260921-outcome-239',1).replace('semantic_status: FOUR_TRACK_P18_SWITCH_TO_P1_OBJECT_THEORY_P19_NEXT','semantic_status: FOUR_TRACK_P21_CONSOLIDATED_P23_NEXT',1)
  elif rel=='方向追踪/002 - 治理与用户方向.md':t=rw(rw(t,'| `DIR-U-HOTT-FOUR-TRACK` |',dr),'| `DIR-U-ABX-ORIGINAL-CIRCLE` |',ar)
  elif rel=='全景视野/003 - 当前机器证明包与原生重放.md':t=rw(rw(t,'| `OUT-HOTT-FOUR-TRACK-PLAN` |',pr),'| `OUT-ABX-ACTION-INTAKE` |',ap)
  elif rel=='MEMORY/001 - 当前执行队列.md':t=rw(t,'P18已完成：',mem)
  elif rel=='MEMORY/003 - 当前验证状态与顺序日志.md':t+='\nS-RES-20260921-ASTRA-P21-CROSS-BRANCH-SYNTHESIS：P19–P22综合，P23独立入口；revision239。\n'
  elif rel==r.PREFIX+'FRONTIER.md':t=rw(t,'- P18已完成：',fr)
  elif rel==r.PREFIX+'RESUME.md':t=rw(t,'当前 active goal 在P18后继续：',rs)
  fs.append({'path':rel,'expected_sha256':r.sha(raw),'text':t})
 ses=f'# {SID}\n\n- tier: T3 P19--P22 consolidation\n- status: COMPLETED_WITH_SCOPE / P23_NEXT\n';runs={'schema_version':'hott-session-runs/v1','session_id':SID,'primary_runs':[{'kind':'P21 synthesis and state reconciliation','result':'PASS_WITH_SCOPE','mathematics':'C325_ALREADY_REGISTERED'}],'new_math_claims':[],'new_kernel_replay':False}
 for n,t in(('SESSION.md',ses),('RUNS.json',r.dump(runs).decode()),('CORE_COGNITION_AUDIT.md',audit(st['current_core']))):fs.append({'path':BASE+n,'expected_sha256':None,'text':t})
 pay={'schema_version':'cognition-checkpoint/v1','session_id':SID,'load_profile':'research','task_ids':[PLAN],'authorization':'用户已授权按goal-3持续推进、公开/本地侦察和checkpoint；不启动Sub Agent、不push、不发布。','files':fs};(OUT/'P21-checkpoint-payload.json').write_bytes(r.dump(pay));z=r.checkpoint(ROOT,pl['snapshot'],pay,apply=x.apply);(OUT/('P21-checkpoint-apply.json'if x.apply else 'P21-checkpoint-dry-run.json')).write_bytes(r.dump(z));print(json.dumps({k:v for k,v in z.items()if k!='paths'},ensure_ascii=False))
if __name__=='__main__':main()
