#!/usr/bin/env python3
"""Checkpoint P17 fixed-source audit and route P18."""
from __future__ import annotations
import argparse, hashlib, importlib.util, json, re, subprocess, sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]; OUT=Path(__file__).resolve().parent; SID='S-RES-20260921-ASTRA-P17-CUBICAL-CAUCHY-REALS'; BASE=f'.codex/research/hott/sessions/{SID}/'; PLAN='R-HOTT-FOUR-TRACK-PLAN-20260921'; ABX='R-ABX-ACTION-20260921'; P16='R-P16-FOURTH-SUCCESSOR-DISCOVERY-20260921'; P17='R-P17-CUBICAL-HOTT-CAUCHY-REALS-CORPUS-20260921'
REPORT='audit/p17-cubical-hott-cauchy-reals-corpus-20260921/P17-CUBICAL-HOTT-CAUCHY-REALS-CORPUS-REPORT.md'; FREEZE='audit/p17-cubical-hott-cauchy-reals-corpus-20260921/P17-CUBICAL-HOTT-CAUCHY-REALS-SOURCE-FREEZE.json'; VERIFY='audit/p17-cubical-hott-cauchy-reals-corpus-20260921/verify_p17_cubical_hott_cauchy_reals_corpus.py'; RECEIPT='audit/p17-cubical-hott-cauchy-reals-corpus-20260921/P17-CUBICAL-HOTT-CAUCHY-REALS-CORPUS-VERIFICATION.json'; SCRIPT='audit/p17-cubical-hott-cauchy-reals-corpus-20260921/checkpoint_p17_cubical_hott_cauchy_reals_corpus.py'
S=(REPORT,FREEZE,VERIFY,RECEIPT,SCRIPT,'goal.md','goal-3.md','feature-list.md','rulings.md','HoTT后续研究总体方案.md','HoTT后续研究总体方案/003 - 分支顺序、准入与停止条件.md','HoTT后续研究总体方案/005 - 当前第一步与交接.md','audit/p16-fourth-successor-discovery-20260921/P16-CUBICAL-CAUCHY-REALS-CANDIDATE-FREEZE.json')
def sh(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def rw(t,p,v):
 a=t.splitlines()
 for i,x in enumerate(a):
  if x.startswith(p):a[i]=v;return '\n'.join(a)+'\n'
 raise AssertionError(p)
def au(c):
 hs=re.findall(r'^### (KC-\d+) · .*? · (.+)$',(ROOT/'核心认知.md').read_text(),re.M);assert len(hs)==46
 z=f'# {SID} 核心认知回评\n\n{c["generation"]}；46 条。\n\n- core_change: NO\n- direction_change: P17_EXPLICIT_CAUCHY_APPROXIMATION_DEFENSE_P18_NEXT\n- panorama_change: REAL_LAYER_SOURCE_AUDIT_TASK_DIFFERENT\n- essay_change: NO\n- update_decision: P17 completes only the fixed Cauchy-real source audit and routes a new successor.\n- cross_conflicts: Cauchy limit qualification is not P13 M/N completion.\n- unresolved: P18, actual K and theory defect remain open.\n- writer_compatibility: G-V5-SESSION-AUDIT-SHARD-WRITE-GAP-001.\n\n| KC | 主题 | relation | 本单元判断 | 证据、反证条件 |\n|---|---|---|---|---|\n'
 for k,t in hs:z+=f'| `{k}` | {t} | NOT_TOUCHED | P17固定source audit。 | `{REPORT}`；P18新分母可改变。 |\n'
 return z+'\n## 波次定位\n\nP17关闭固定实数语料，P18选择新分母；Goal仍active。\n'
def main():
 a=argparse.ArgumentParser();a.add_argument('--apply',action='store_true');x=a.parse_args();subprocess.check_call([sys.executable,'-B',VERIFY,'--write'],cwd=ROOT);assert all((ROOT/p).is_file()for p in S)
 sp=importlib.util.spec_from_file_location('r',ROOT/'.codex/tools/cognition_runtime.py');r=importlib.util.module_from_spec(sp);sp.loader.exec_module(r);st=json.loads((ROOT/r.STATE).read_text());assert st['revision']==236 and st['latest_session']=='S-RES-20260921-ASTRA-P16-FOURTH-SUCCESSOR-DISCOVERY';head=json.loads((ROOT/r.HEAD).read_text());assert all(sh(ROOT/p)==v for p,v in head['tracked'].items());pl=r.plan(ROOT,profile='research',task_ids=[PLAN]);(OUT/'P17-CHECKPOINT-PLAN.json').write_bytes(r.dump(pl));st['revision']=237;st['latest_session']=SID
 for q in (PLAN,ABX,P16):
  v=st['records'][q];v['related_records']=list(dict.fromkeys(v.get('related_records',[])+[P17,SID]));v['revalidation']=v.get('revalidation','')+' Revision237 records P17 fixed-source audit; previous scope unchanged.'
 p=st['records'][PLAN];p.update(status='four_track_p17_explicit_cauchy_approximation_defense_p18_next',evidence_status='P17_EXPLICIT_CAUCHY_APPROXIMATION_DEFENSE / P18_FIFTH_SUCCESSOR_DISCOVERY_NEXT / GOAL_ACTIVE');p['full_sources']=list(dict.fromkeys(p.get('full_sources',[])+list(S)));p['source_hashes'].update({q:sh(ROOT/q)for q in p['full_sources']if(ROOT/q).is_file()})
 st['records'][P17]={'kind':'result','path':REPORT,'lifecycle_status':'CURRENT','evidence_status':'NOT_A_P13_CONSUMER_WITHIN_FIXED_P17_SOURCES / DEFENSE_EXPLICIT_APPROXIMATION_RELATION_HII_DATA / TASK_DIFFERENT_FROM_P13_MN_DONE / P18_FIFTH_SUCCESSOR_DISCOVERY_NEXT / NO_NEW_HOTT_DEFECT_CLAIM','status':'complete_with_scope_p18_next','depends_on':[],'related_records':[PLAN,ABX,P16],'full_sources':list(S),'source_hashes':{q:sh(ROOT/q)for q in S},'scope':'P17 fixed source audit only, no clone or kernel replay.'};st['records'][SID]={'kind':'session','path':BASE+'SESSION.md','lifecycle_status':'HISTORICAL','evidence_status':'P17_SOURCE_AUDIT_CHECKPOINTED_WITH_SCOPE','status':'complete_with_scope','depends_on':[],'related_records':[P17,PLAN,ABX],'full_sources':[BASE+n for n in ('SESSION.md','RUNS.json','CORE_COGNITION_AUDIT.md')]}
 st['execution_control'].update(status='FOUR_TRACK_P17_EXPLICIT_CAUCHY_APPROXIMATION_DEFENSE_P18_NEXT',current_phase='PHASE_2_P17_COMPLETE_P18_SUCCESSOR_DISCOVERY_NEXT',second_phase_status='P1_TO_P17_COMPLETE_P18_NEXT',last_checkpoint_session=SID,checkpoint_result=f'.codex/cognition/checkpoints/{SID}/result.json',next_minimal_verification='P18-FIFTH-SUCCESSOR-DISCOVERY-001. Perform fresh bounded public/community plus local/historical reconnaissance for one unreviewed version-pinned actual consumer or theory–implementation difference outside P15/P17. Freeze Input/Operation/Observation/Done and P7 rationale; do not re-audit the Cauchy-reals corpus or clone/compile.')
 st['projection']['status']='FOUR_TRACK_P17_EXPLICIT_CAUCHY_APPROXIMATION_DEFENSE / NEXT_P18_FIFTH_SUCCESSOR_DISCOVERY / GOAL_ACTIVE / NO_NEW_HOTT_DEFECT_CLAIM'
 dr='| `DIR-U-HOTT-FOUR-TRACK` | P17实数层审计与P18新分母 | 用户要求双重侦察 | `P17_CAUCHY_APPROXIMATION_DEFENSE / P18_NEXT / GOAL_ACTIVE` | `PARADOX_DISCOVERY` | P1–P17 | P18发现新分母 | P17 report；revision237 |'; ar='| `DIR-U-ABX-ORIGINAL-CIRCLE` | ABX P17实数层任务差异 | P17 | `TASK_DIFFERENT / P18_NEXT` | `PARADOX_DISCOVERY` | P17 | P18新分母 | P17 report；revision237 |'; pr='| `OUT-HOTT-FOUR-TRACK-PLAN` | P17 Cauchy-real固定source审计 | `DIR-U-HOTT-FOUR-TRACK` | arXiv+README+ref | `NOT_A_P13_CONSUMER / P18_NEXT` | 显式Cauchy资格 | 不证明K/HoTT缺陷 | P17 report；revision237 |'; ap='| `OUT-ABX-ACTION-INTAKE` | ABX P17实数层审计 | `DIR-U-ABX-ORIGINAL-CIRCLE` | Cauchy approx/HII | `TASK_DIFFERENT / P18_NEXT` | 结构保留 | 不证明原M/N桥 | P17 report；revision237 |';mem='P17已完成：Cauchy-real构造显式要求IsCauchy、精度、closeness与path，且任务不同于P13 Done；固定分母关闭。P18重新双重侦察选新分母。入口：`audit/p17-cubical-hott-cauchy-reals-corpus-20260921/P17-CUBICAL-HOTT-CAUCHY-REALS-CORPUS-REPORT.md`；revision237。';fr='- P17已完成：固定Cauchy-real语料显式保留approximation/relation/HII数据，非P13 K；P18重选新分母。入口：`audit/p17-cubical-hott-cauchy-reals-corpus-20260921/P17-CUBICAL-HOTT-CAUCHY-REALS-CORPUS-REPORT.md`。';rs='当前 active goal 在P17后继续：P18重新做公开/本地侦察，选未审版本冻结分母；不重审Cauchy-real语料。入口：`audit/p17-cubical-hott-cauchy-reals-corpus-20260921/P17-CUBICAL-HOTT-CAUCHY-REALS-CORPUS-REPORT.md`；revision237。'
 fs=[]
 for rel in list(r.MUTABLE)+list(r.mutable_shard_paths(ROOT)):
  raw=(ROOT/rel).read_bytes();t=raw.decode()
  if rel==r.STATE:t=r.dump(st).decode()
  elif rel==r.DIRECTION:t=t.replace('source_state_revision: 236','source_state_revision: 237',1).replace('projection_generation: 20260921-direction-236','projection_generation: 20260921-direction-237',1).replace('semantic_status: FOUR_TRACK_P16_CUBICAL_CAUCHY_REALS_CANDIDATE_SELECTED_P17_NEXT','semantic_status: FOUR_TRACK_P17_EXPLICIT_CAUCHY_APPROXIMATION_DEFENSE_P18_NEXT',1)
  elif rel==r.PANORAMA:t=t.replace('source_state_revision: 236','source_state_revision: 237',1).replace('projection_generation: 20260921-outcome-236','projection_generation: 20260921-outcome-237',1).replace('semantic_status: FOUR_TRACK_P16_CUBICAL_CAUCHY_REALS_CANDIDATE_SELECTED_P17_NEXT','semantic_status: FOUR_TRACK_P17_EXPLICIT_CAUCHY_APPROXIMATION_DEFENSE_P18_NEXT',1)
  elif rel=='方向追踪/002 - 治理与用户方向.md':t=rw(rw(t,'| `DIR-U-HOTT-FOUR-TRACK` |',dr),'| `DIR-U-ABX-ORIGINAL-CIRCLE` |',ar)
  elif rel=='全景视野/003 - 当前机器证明包与原生重放.md':t=rw(rw(t,'| `OUT-HOTT-FOUR-TRACK-PLAN` |',pr),'| `OUT-ABX-ACTION-INTAKE` |',ap)
  elif rel=='MEMORY/001 - 当前执行队列.md':t=rw(t,'P16已完成：',mem)
  elif rel=='MEMORY/003 - 当前验证状态与顺序日志.md':t+='\nS-RES-20260921-ASTRA-P17-CUBICAL-CAUCHY-REALS：P17显式Cauchy资格防御，P18重选分母；revision237。\n'
  elif rel==r.PREFIX+'FRONTIER.md':t=rw(t,'- P16已完成：',fr)
  elif rel==r.PREFIX+'RESUME.md':t=rw(t,'当前 active goal 在P16后继续：',rs)
  fs.append({'path':rel,'expected_sha256':r.sha(raw),'text':t})
 session=f'# {SID}\n\n- tier: T3 P17 source audit\n- status: COMPLETED_WITH_SCOPE / P18_NEXT\n';runs={'schema_version':'hott-session-runs/v1','session_id':SID,'primary_runs':[{'kind':'P17 fixed source audit','result':'PASS_WITH_SCOPE','mathematics':'NO_NEW_KERNEL_RUN'}],'new_math_claims':[],'new_kernel_replay':False}
 for n,t in (('SESSION.md',session),('RUNS.json',r.dump(runs).decode()),('CORE_COGNITION_AUDIT.md',au(st['current_core']))):fs.append({'path':BASE+n,'expected_sha256':None,'text':t})
 payload={'schema_version':'cognition-checkpoint/v1','session_id':SID,'load_profile':'research','task_ids':[PLAN],'authorization':'用户已授权按goal-3持续推进、公开/本地侦察和checkpoint；不启动Sub Agent、不push、不发布。','files':fs};(OUT/'P17-checkpoint-payload.json').write_bytes(r.dump(payload));z=r.checkpoint(ROOT,pl['snapshot'],payload,apply=x.apply);(OUT/('P17-checkpoint-apply.json'if x.apply else 'P17-checkpoint-dry-run.json')).write_bytes(r.dump(z));print(json.dumps({k:v for k,v in z.items()if k!='paths'},ensure_ascii=False))
if __name__=='__main__':main()
