#!/usr/bin/env python3
"""Checkpoint P37 weak/strong task-fidelity requalification."""
from __future__ import annotations
import argparse, hashlib, importlib.util, json, re, sys
from pathlib import Path

ROOT=Path(__file__).resolve().parents[2]; OUT=Path(__file__).resolve().parent
SID='S-RES-20260922-ASTRA-P37-WEAK-PUNCTURE-FIDELITY'; BASE=f'.codex/research/hott/sessions/{SID}/'
PLAN='R-HOTT-FOUR-TRACK-PLAN-20260921'; P36='R-P36-PROVENANCE-ORIGIN-COVERAGE-20260922'; P37='R-P37-WEAK-PUNCTURE-FIDELITY-20260922'; D='audit/p37-weak-puncture-fidelity-20260922'
S=(f'{D}/P37-WEAK-PUNCTURE-FIDELITY-REPORT.md',f'{D}/P37-WEAK-PUNCTURE-FIDELITY-SOURCE-FREEZE.json',f'{D}/verify_p37_weak_puncture_fidelity.py',f'{D}/P37-WEAK-PUNCTURE-FIDELITY-VERIFICATION.json','HoTT/formal/agda-unimath/hott-z/NativeRealCircleQualification.agda','HoTT/formal/agda-unimath/hott-z/PunctureApartness.agda','HoTT/formal/agda-unimath/hott-z/NativeStereographic.agda','HoTT/formal/agda-unimath/hott-z/NativeOpenInterval.agda','HoTT/formal/agda-unimath/hott-z/WeakLiftPrinciple.agda','HoTT/formal/agda-unimath/hott-z/WeakLiftConsumer.agda','HoTT/formal/agda-unimath/hott-z/NativeMotionComplete.agda','HoTT/formal/agda-unimath/hott-z/NativeRichCurve.agda','HoTT/formal/agda-unimath/hott-z/NativeSourceContract.agda','HoTT/verification/runs/20260920-MP-ASTRA-WEAK-LIFT-PRINCIPLE-001-01/RUN.json','Astra继续尝试/断点与证明机制系统检查/对话原文/007 - 归档交付与指定缺口的新问题.md','ABX行动/003 - 原圆环对象、判据与正反控制.md','goal-3-工作路径树/001 - 原初目标与当前工作树.md')
def h(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def rt():
 s=importlib.util.spec_from_file_location('r',ROOT/'.codex/tools/cognition_runtime.py');m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return m
def ed():sys.path.insert(0,str(ROOT/'scripts/audit'));import projection_edit;return projection_edit
def audit(core):
 rows=re.findall(r'^### (KC-\d+) · .*? · (.+)$',(ROOT/'核心认知.md').read_text(),re.M);assert len(rows)==46
 deep={'KC-000003','KC-000004','KC-000005','KC-000010','KC-000015','KC-000019','KC-000020','KC-000021','KC-000022','KC-000037','KC-000038','KC-000039','KC-000040','KC-000041','KC-000042','KC-000043','KC-000044','KC-000045','KC-000046'}
 x=f'# {SID} 核心认知回评\n\n{core["generation"]}；46 条；兼容单文件审计登记 `G-V5-SESSION-AUDIT-SHARD-WRITE-GAP-001`。\n\n- core_change: NO\n- direction_change: P37 closes existing weak/strong coverage and routes P38 event-bridge discovery.\n- panorama_change: no new theorem; existing C-283–C-290/C-307–C-308 reused.\n- essay_change: NO\n- update_decision: strong-domain results cannot be reported as unconditional ordinary-M results.\n- cross_conflicts: no HoTT defect, K, engine issue, event impossibility, or reality bridge established.\n- unresolved: P38 real origin-event bridge; P2/P3/P4 gates remain.\n- writer_compatibility: G-V5-SESSION-AUDIT-SHARD-WRITE-GAP-001.\n\n| KC | 主题 | relation | 本单元判断 | 证据、反证条件 |\n|---|---|---|---|---|\n'
 for kc,title in rows:
  r='DEEPENED' if kc in deep else 'NOT_TOUCHED';j='P37区分普通弱去点与当前强域，防止规格替代。' if r=='DEEPENED' else '本单元未直接检验该原文。';e='P37 report；若原文明确要求Strong或出现无条件弱结果则重评。' if r=='DEEPENED' else 'P38或新原文可改变判断。';x+=f'| `{kc}` | {title} | `{r}` | {j} | {e} |\n'
 return x+'\n## 波次定位\n\n- 最终目标连接：P1/R_min输入忠实性。\n- 实际价值：既有弱/强条件覆盖阻止把强域替代原M。\n- 裁决：`CLOSE_WITH_SCOPE / SWITCH_BRANCH_TO_P38_REAL_ORIGIN_EVENT_BRIDGE_DISCOVERY`。\n'
def main():
 a=argparse.ArgumentParser();a.add_argument('--apply',action='store_true');a=a.parse_args();r=rt();e=ed();assert all((ROOT/x).is_file() for x in S);assert json.loads((ROOT/S[3]).read_text())['status']=='PASS_WITH_SCOPE';st=json.loads((ROOT/r.STATE).read_text());assert st['revision']==254 and st['latest_session']=='S-RES-20260922-ASTRA-P36-PROVENANCE-ORIGIN-COVERAGE';head=json.loads((ROOT/r.HEAD).read_text());assert all(h(ROOT/p)==v for p,v in head['tracked'].items());pl=r.plan(ROOT,profile='research',task_ids=[PLAN]);(OUT/'P37-CHECKPOINT-PLAN.json').write_bytes(r.dump(pl));st['revision']=255;st['latest_session']=SID
 p=st['records'][PLAN];p['related_records']=list(dict.fromkeys(p.get('related_records',[])+[P37,SID]));p['status']='p1_weak_strong_fidelity_covered_p38_event_bridge_next';p['evidence_status']='P1_PRESENTATION_FIBER_FORMAL_CHECKED_WITH_SCOPE / P1_FIBERWISE_TRACE_EXACT_COVERAGE_WITH_SCOPE / P1_WEAK_STRONG_FIDELITY_COVERED_WITH_EXPLICIT_LIFT / P2_REFLECTION_SUBLINE_CLOSED_BY_EXACT_COVERAGE / P3_PAUSED_SAME_CLASS / P4_NOT_TRIGGERED / P38_REAL_ORIGIN_EVENT_BRIDGE_DISCOVERY_NEXT / GOAL_ACTIVE';p['full_sources']=list(dict.fromkeys(p.get('full_sources',[])+list(S)));p.setdefault('source_hashes',{}).update({x:h(ROOT/x) for x in p['full_sources'] if (ROOT/x).is_file()});p['revalidation']=p.get('revalidation','')+' Revision255 closes P37 with existing weak/strong conditional coverage and selects P38 real origin-event bridge discovery.'
 st['records'][P37]={'kind':'result','path':S[0],'lifecycle_status':'CURRENT','evidence_status':'EXACT_COVERAGE_BY_EXISTING_C283_C290_C307_C308 / ORIGINAL_WEAK_M_NOT_UNCONDITIONALLY_MODELED_BY_STRONG_SOURCE / SPEC_REFINEMENT_NOT_JUSTIFIED_BY_ORIGINAL_TEXT / P38_REAL_ORIGIN_EVENT_BRIDGE_DISCOVERY_SELECTED / NO_HOTT_DEFECT_OR_ACTUAL_K_CLAIM','status':'complete_with_scope','depends_on':[],'related_records':[PLAN,P36,SID],'full_sources':list(S),'source_hashes':{x:h(ROOT/x) for x in S},'scope':'Existing local weak/strong results exactly cover P37. Current strong-domain source is not an unconditional model of ordinary weak M; this is a task-fidelity boundary, not a general no-equivalence theorem, HoTT defect, K, engine issue, or reality bridge.'}
 st['records'][SID]={'kind':'session','path':BASE+'SESSION.md','lifecycle_status':'HISTORICAL','evidence_status':'P37_WEAK_PUNCTURE_FIDELITY_CHECKPOINTED_WITH_SCOPE','status':'complete_with_scope','depends_on':[],'related_records':[PLAN,P36,P37],'full_sources':[BASE+x for x in ('SESSION.md','RUNS.json','CORE_COGNITION_AUDIT.md')]}
 st['execution_control'].update({'status':'FOUR_TRACK_P1_WEAK_STRONG_FIDELITY_COVERED_P38_EVENT_BRIDGE_NEXT','current_phase':'PHASE_2_P37_WEAK_STRONG_FIDELITY_COVERED_P38_EVENT_BRIDGE_NEXT','second_phase_status':'P1_ACTIVE_P38_EVENT_BRIDGE_P2_REFLECTION_CLOSED_P3_PAUSED_P4_NOT_TRIGGERED','last_checkpoint_session':SID,'checkpoint_result':f'.codex/cognition/checkpoints/{SID}/result.json','next_minimal_verification':'P38-P1-REAL-ORIGIN-EVENT-BRIDGE-DISCOVERY-001. Starting from fixed original X, P36/P37, OriginDirectedDiagram and SourceContract, inspect whether existing local assets jointly preserve full circle, designated point, weak/strong puncture source, an explicit operation, observations and a consumable Done/source relation. Classify exact coverage, partial reuse or one precise missing field before designing any record. Do not assert HoTT defect, actual K, engine issue, historical-event impossibility or reality bridge.'});st['projection']['status']='FOUR_TRACK_P1_WEAK_STRONG_FIDELITY_COVERED / P38_EVENT_BRIDGE_DISCOVERY_NEXT / P2_CLOSED / P3_PAUSED / P4_NOT_TRIGGERED / GOAL_ACTIVE / NO_NEW_HOTT_DEFECT_CLAIM'
 mem=e.load(ROOT,'MEMORY.md');dire=e.load(ROOT,'方向追踪.md');pan=e.load(ROOT,'全景视野.md');essay=e.load(ROOT,'扩展认知.md')
 e.replace_in_shard(mem,'MEMORY/001 - 当前执行队列.md','P36 已确认实际圆的静态指定点去除已定义，但当前 `mRich` 使用 `StrongPuncture` 而普通弱去点到强域需 `Lift`；`Input.source` 也没有历史provenance event。下一=P37复资格化原弱M与强域模型。P3仍等待实际K，P4未触发。入口：`audit/p36-provenance-origin-coverage-20260922/P36-PROVENANCE-ORIGIN-COVERAGE-REPORT.md`；revision254。','P37 已由C-283–C-290/C-307–C-308确认：普通弱M到开区间的相关正构造显式带`Lift`，强域结果不能无条件替代原M。下一=P38审计现有资产是否已共同给出真实来源event bridge。P3仍等待实际K，P4未触发。入口：`audit/p37-weak-puncture-fidelity-20260922/P37-WEAK-PUNCTURE-FIDELITY-REPORT.md`；revision255。');e.append_to_shard(mem,'MEMORY/003 - 当前验证状态与顺序日志.md','\nS-RES-20260922-ASTRA-P37-WEAK-PUNCTURE-FIDELITY：弱/强M关系已由既有C283–C290/C307–C308覆盖；强域不替代无条件弱M；P38来源event bridge discovery next；revision255。\n')
 e.replace_in_index(dire,'source_state_revision: 254','source_state_revision: 255');e.replace_in_index(dire,'projection_generation: 20260922-direction-254','projection_generation: 20260922-direction-255');e.replace_in_index(dire,'semantic_status: FOUR_TRACK_P36_STATIC_PUNCTURE_REFINEMENT_P37_WEAK_FIDELITY_NEXT','semantic_status: FOUR_TRACK_P37_WEAK_STRONG_FIDELITY_COVERED_P38_EVENT_BRIDGE_NEXT');e.replace_in_shard(dire,'方向追踪/002 - 治理与用户方向.md','| `DIR-U-HOTT-FOUR-TRACK` | P36：静态去点与强域来源细化 | P35/P36 | `P37_WEAK_PUNCTURE_FIDELITY_REQUALIFICATION_NEXT / GOAL_ACTIVE` | `PARADOX_DISCOVERY` | `OUT-HOTT-FOUR-TRACK-PLAN`、C-283–C-290 | mRich为StrongPuncture；复资格化原弱M | P36 report；revision254 |','| `DIR-U-HOTT-FOUR-TRACK` | P37：弱/强M任务忠实性复资格化 | P36/P37 | `P38_REAL_ORIGIN_EVENT_BRIDGE_DISCOVERY_NEXT / GOAL_ACTIVE` | `PARADOX_DISCOVERY` | `OUT-HOTT-FOUR-TRACK-PLAN`、C-283–C-290/C-307–C-308 | 条件性已覆盖，审计是否有真实来源event桥 | P37 report；revision255 |');e.replace_in_shard(dire,'方向追踪/002 - 治理与用户方向.md','| `DIR-U-ABX-ORIGINAL-CIRCLE` | ABX 原圆环 P3 实际消费者分支停放 | P21/P36 | `P3_PAUSED / P37_P1_WEAK_FIDELITY` | `EVIDENCE_DISCIPLINE` | `OUT-ABX-ACTION-INTAKE` | 仅新版本固定实际 K 或强 R 才重开 | P21/P36 reports；revision254 |','| `DIR-U-ABX-ORIGINAL-CIRCLE` | ABX 原圆环 P3 实际消费者分支停放 | P21/P37 | `P3_PAUSED / P38_P1_EVENT_BRIDGE` | `EVIDENCE_DISCIPLINE` | `OUT-ABX-ACTION-INTAKE` | 仅新版本固定实际 K 或强 R 才重开 | P21/P37 reports；revision255 |')
 e.replace_in_index(pan,'source_state_revision: 254','source_state_revision: 255');e.replace_in_index(pan,'projection_generation: 20260922-outcome-254','projection_generation: 20260922-outcome-255');e.replace_in_index(pan,'semantic_status: FOUR_TRACK_P36_STATIC_PUNCTURE_REFINEMENT_P37_WEAK_FIDELITY_NEXT','semantic_status: FOUR_TRACK_P37_WEAK_STRONG_FIDELITY_COVERED_P38_EVENT_BRIDGE_NEXT');e.replace_in_shard(pan,'全景视野/003 - 当前机器证明包与原生重放.md','| `OUT-P36-PROVENANCE-ORIGIN-COVERAGE` | 静态固定点去点与当前强域source审计 | `DIR-U-HOTT-FOUR-TRACK` | fixed local definitions plus C-283–C-290 receipts | `PARTIAL_REUSE / STRONG_REFINEMENT / P37_NEXT` | `PuncturedRealCircle`已定义；mRich使用StrongPuncture，source事件未记载 | 不证明历史事件不可能、HoTT缺陷、actual K或现实桥 | P36 report/verification；revision254 |','| `OUT-P36-PROVENANCE-ORIGIN-COVERAGE` | 静态固定点去点与当前强域source审计 | `DIR-U-HOTT-FOUR-TRACK` | fixed local definitions plus C-283–C-290 receipts | `PARTIAL_REUSE / STRONG_REFINEMENT / P37_COMPLETED` | `PuncturedRealCircle`已定义；mRich使用StrongPuncture，source事件未记载 | 不证明历史事件不可能、HoTT缺陷、actual K或现实桥 | P36 report/verification；revision254 |\n| `OUT-P37-WEAK-PUNCTURE-FIDELITY` | 原弱M与强域模型的任务忠实性复资格化 | `DIR-U-HOTT-FOUR-TRACK` | existing C-283–C-290/C-307–C-308 sources/runs | `EXACT_COVERAGE_WITH_SCOPE / P38_NEXT` | 强域到N无条件、弱域正构造显式带Lift；不许强域替代原弱M | 不证明任何无条件弱同胚不可能、HoTT缺陷或现实桥 | P37 report/verification；revision255 |');e.replace_in_shard(pan,'全景视野/003 - 当前机器证明包与原生重放.md','| `OUT-ABX-ACTION-INTAKE` | ABX P3停放，P36转入P37弱域复资格化 | `DIR-U-ABX-ORIGINAL-CIRCLE` | P15/P17/P19/P20/P22/P25/P26/P27/P28/P29/P30/P31/P32/P33/P34/P35/P36 | `P3_PAUSED / P37_P1_WEAK_FIDELITY` | 避免重复，保留新实际K重开条件 | 不证明原M/N桥 | P21/P36 reports；revision254 |','| `OUT-ABX-ACTION-INTAKE` | ABX P3停放，P37转入P38事件桥审计 | `DIR-U-ABX-ORIGINAL-CIRCLE` | P15/P17/P19/P20/P22/P25/P26/P27/P28/P29/P30/P31/P32/P33/P34/P35/P36/P37 | `P3_PAUSED / P38_P1_EVENT_BRIDGE` | 避免重复，保留新实际K重开条件 | 不证明原M/N桥 | P21/P37 reports；revision255 |');e.replace_in_shard(pan,'全景视野/008 - 当前未完成.md','16. `P37-P1-WEAK-PUNCTURE-FIDELITY-REQUALIFICATION-001`：以普通`PuncturedRealCircle`重审强域`mRich`、`Lift`与原M的任务忠实性；不让强域结论替代弱域。','16. `P38-P1-REAL-ORIGIN-EVENT-BRIDGE-DISCOVERY-001`：审计完整圆、点、去点source、operation、观察和Done是否已有真实origin-event bridge；全覆盖即停止。')
 simple={x:(ROOT/x).read_text() for x in r.MUTABLE if x not in {r.STATE,'MEMORY.md','方向追踪.md','全景视野.md','扩展认知.md'}};simple[r.PREFIX+'FRONTIER.md']=simple[r.PREFIX+'FRONTIER.md'].replace('- P36确认静态circle-minus-east已定义但mRich为StrongPuncture细化、source event未记；P37以普通弱去点重新资格化任务。入口：`audit/p36-provenance-origin-coverage-20260922/P36-PROVENANCE-ORIGIN-COVERAGE-REPORT.md`。','- P37确认弱/强关系已有条件性机器覆盖，强域不替代无条件原M；P38审计是否存在真实origin-event bridge。入口：`audit/p37-weak-puncture-fidelity-20260922/P37-WEAK-PUNCTURE-FIDELITY-REPORT.md`。',1);simple[r.PREFIX+'RESUME.md']=simple[r.PREFIX+'RESUME.md'].replace('当前 active goal 已完成P36：实际圆的弱静态去点已定义，但mRich是StrongPuncture，弱→强有Lift条件，Input也未保存历史来源event。P37复资格化原弱M与强域结论；P3仍等待实际K、P4未触发。入口：`audit/p36-provenance-origin-coverage-20260922/P36-PROVENANCE-ORIGIN-COVERAGE-REPORT.md`；revision254。','当前 active goal 已完成P37：既有C-283–C-290/C-307–C-308已覆盖弱/强边界，强域结果不能无条件替代原弱M。P38审计现有资产是否已共同形成真实来源event bridge；P3仍等待实际K、P4未触发。入口：`audit/p37-weak-puncture-fidelity-20260922/P37-WEAK-PUNCTURE-FIDELITY-REPORT.md`；revision255。',1)
 rows=[]
 for d in (mem,dire,pan,essay):rows+=e.payload_rows(d,ROOT)
 seen={x['path'] for x in rows}
 for rel in r.MUTABLE:
  if rel not in seen:rows.append({'path':rel,'expected_sha256':h(ROOT/rel),'text':r.dump(st).decode() if rel==r.STATE else simple[rel]})
 session=f'# {SID}\n\n- host: codex-desktop\n- model: runtime-model-not-certified-by-tool\n- tier: T3\n- status: `P37_WEAK_STRONG_FIDELITY_COVERED / P38_EVENT_BRIDGE_NEXT / NO_HOTT_DEFECT_OR_ACTUAL_K_CLAIM`\n- load_receipt: research plan snapshot `{pl["snapshot"]}`; P37 local/history sources, existing kernel receipts, source freeze and verifier reviewed.\n- authorization: 用户已授权按 goal-3 持续推进、公开/本地侦察和 checkpoint；不启动 Sub Agent、不 push、不发布。\n';runs={'schema_version':'hott-session-runs/v1','session_id':SID,'primary_runs':[{'kind':'P37 source/domain verifier','result':'PASS_WITH_SCOPE','receipt':S[3]}],'new_math_claims':[],'new_kernel_replay':False,'scope':'P37 reuses existing results; no new kernel proof claim.'};rows += [{'path':BASE+'SESSION.md','expected_sha256':None,'text':session},{'path':BASE+'RUNS.json','expected_sha256':None,'text':r.dump(runs).decode()},{'path':BASE+'CORE_COGNITION_AUDIT.md','expected_sha256':None,'text':audit(st['current_core'])}]
 payload={'schema_version':'cognition-checkpoint/v1','session_id':SID,'load_profile':'research','task_ids':[PLAN],'authorization':'用户已授权按goal-3持续推进、公开/本地侦察和checkpoint；不启动Sub Agent、不push、不发布。','files':rows};(OUT/'P37-CHECKPOINT-PAYLOAD.json').write_bytes(r.dump(payload));res=r.checkpoint(ROOT,pl['snapshot'],payload,apply=a.apply);(OUT/('P37-CHECKPOINT-APPLY.json' if a.apply else 'P37-CHECKPOINT-DRY-RUN.json')).write_bytes(r.dump(res));print(json.dumps({k:v for k,v in res.items() if k!='paths'},ensure_ascii=False,indent=2))
if __name__=='__main__':main()
