#!/usr/bin/env python3
"""Persist the C02 interface result without dropping producer/non-leaf obligations."""
from pathlib import Path
import argparse,hashlib,importlib.util,json,re,sys
ROOT=Path(__file__).resolve().parents[4];HERE=Path(__file__).resolve().parent
OWN='第三轮机器统观/Session-A/';TASK='MO3-GOVERNED-A';RID='R-MO3-C02-FINITE-COVER-20260924'
SID='S-RES-20260924-MO3-A-C02';BASE=f'.codex/research/hott/sessions/{SID}/'
REPORT=OWN+'执行记录/009 - 有限覆盖交付的生成与证明义务.md';PROCESS=OWN+'过程与结果/003 - 有理区间覆盖与原索引交付.md';AUDIT=OWN+'审计/W3-C02/CORE_COGNITION_AUDIT.md'
RUN='HoTT/verification/runs/20260924-MO3-FINITE-COVER-001-08/';FORMAL='HoTT/formal/mo3/finite-cover/'
def sha(p):return hashlib.sha256((ROOT/p).read_bytes()).hexdigest()
def main():
    ap=argparse.ArgumentParser();ap.add_argument('--apply',action='store_true');args=ap.parse_args()
    sp=importlib.util.spec_from_file_location('rt',ROOT/'.codex/tools/cognition_runtime.py');rt=importlib.util.module_from_spec(sp);sp.loader.exec_module(rt)
    sys.path.insert(0,str(ROOT/'scripts/audit'));import projection_edit as edit
    s=json.loads((ROOT/rt.STATE).read_text());assert s['revision']==275 and SID not in s['records'] and RID not in s['records']
    h=json.loads((ROOT/rt.HEAD).read_text());assert all(sha(p)==v for p,v in h['tracked'].items())
    methods=json.loads((HERE.parent/'MS01/method-inputs/MANIFEST.json').read_text());assert all(sha(x['source'])==x['sha256'] for x in methods['rows'])
    v=json.loads((HERE/'version-check/RESULT.json').read_text());assert v['subject_commit']=='094b7216758842b37670228d8e6244177f5c9896' and v['checks'][0]['exit']==0
    checks=json.loads((HERE/'validation-001/RESULT.json').read_text());assert all(x['exit']==0 for x in checks['commands'][:2]) and not checks['builtin_drift'] and checks['wrong_touching_expected_rejection']
    rt.query_record(ROOT,TASK);plan=rt.plan(ROOT,profile='research',task_ids=[TASK]);assert set(plan['review_required'])<={TASK} and not plan['hydration_diagnostics']['query_first_promoted'];(HERE/'checkpoint-plan.json').write_bytes(rt.dump(plan))
    source_names=['GenericFiniteCover.agda','FiniteSubcover.agda','FiniteCoverSearch.agda','IntervalCover.agda','RationalCuts.agda','CutRealLayer.agda','CutInfra.agda','NoCanonicalPoint.agda','README.md','DEPENDENCY-AUDIT.json']
    evidence=[PROCESS]+[FORMAL+n for n in source_names]+[RUN+n for n in ['RUN.json','source-manifest.json','index-row-manifest.json']]+[OWN+'证据/W3-C02/version-check/RESULT.json']
    s['records'][RID]=dict(kind='result',path=PROCESS,lifecycle_status='CLOSED',status='C02_NATIVE_INTERFACE_COMPLETE_PRODUCER_SCOPE_PRESERVED',evidence_status='FORMAL_CHECKED_WITH_SCOPE / SELECTED_PACKAGES_VERSION_CLOSED / COMPUTATION_LIMIT_DOCUMENTED / REALITY_MISMATCH_NOT_ESTABLISHED',depends_on=[],related_records=[TASK],full_sources=evidence,source_hashes={p:sha(p) for p in evidence},proof_id='MP-MO3-FINITE-COVER-001',claim_ids=[f'C-{i}' for i in range(335,340)],subject_commit=v['subject_commit'],scope='Actual Dedekind cut unit interval; finite pointwise-cover/chain adequacy and Nat original-index extraction from mere finite-subcover existence, generator completeness, concrete controls, no uniform selector over every Type0 index. Does not supply Book compactness producers, recover a hidden chosen list, or certify general computation on transported indexed proofs. R13 producer conditions remain in parent MS05.')
    r=s['records'][TASK];r['depends_on'].append(RID);r['dependency_semantics']='verification_staleness'
    r.update(status='C02_NATIVE_INTERFACE_COMPLETE_R09_R13_MS05_NEXT',evidence_status='C01_C04_C02_EXACT_NATIVE_RESULTS / MS04_EXECUTED / NONLEAF_AND_BIAS_REMAINDER / ROUND_INCOMPLETE',full_sources=['goal-6.md','goal-5.md',REPORT,AUDIT])
    pins=[REPORT,AUDIT,OWN+'覆盖与关系/001 - 理论范围与五尺度首遍.md',OWN+'覆盖与关系/002 - 全景重新呈现与过程关系.md',OWN+'覆盖与关系/003 - 首遍语义裁决与实际验证选择.md',OWN+'覆盖与关系/004 - 语义单元与联合条件.md',OWN+'证据/W3-C02/source-read.json']
    r['source_hashes'].update({p:sha(p) for p in pins});r['revalidation']='C02 actual source-generated task after full Highest Directive/KC47-48 reload; native real-cover/certificate/search/output chain completed and exact general-index contrast checked. Own coverage pins updated to actual results; source compactness producers and strict-interior side conditions remain source-scoped MS05 obligations, not silently upgraded or dropped. Three indexed-match computation limits and legacy global registry failure retained.'
    r['scope']='Full Goal5 v1.2/Goal6. C01, C04 and C02 interface results complete with explicit hypotheses; real C01 regrouping and finite controls executed. R09/R13 source/composition adjudication, all remaining accepted non-leaf questions, dedicated bias regression and MS06 seal still mandatory.'
    rev=s['revision']+1;s['revision']=rev;s['latest_session']=SID
    message=f'MO3 C02已在094b7216版本闭合C335–339：真实RD有限覆盖与链之间的双向构造（反向mere另选）、Nat原索引交付、列表生成覆盖及一般I统一接口边界；保Book compactness producer/计算警告范围。三主题均无合格现实相对命中。下一R09/R13与全部MS02/MS05非叶对账，再专门偏差回归和MS06。ROUND_INCOMPLETE；revision{rev}。'
    nxt='Adjudicate R09 directed/QTT substitution and R13 strict-interior/compactness-producer side conditions from exact sources; use a bounded native discriminating process if making new mathematical claims. Complete all remaining MS02/MS05 accepted non-leaf questions individually, preserve pointwise/inductive/mere-finite/data-finite and implementation-computation distinctions, then dedicated bias regression and full Goal5/6 completion audit before MS06 seal. Do not repeat the three completed native interfaces without new premises/consumers.'
    s['execution_control'].update(current_phase='MO3_W3_R09_R13_NONLEAF_ADJUDICATION',status='MO3_ACTIVE_ROUND_INCOMPLETE',next_minimal_verification=nxt,last_checkpoint_session=SID,checkpoint_result=f'.codex/cognition/checkpoints/{SID}/result.json',app_goal_completion_eligible=False,app_goal_status_observed='active')
    s['projection']['status']='MO3_C02_NATIVE_INTERFACE_COMPLETE / R09_R13_MS05_NEXT / ROUND_INCOMPLETE'
    s['records'][SID]=dict(kind='session',path=BASE+'SESSION.md',lifecycle_status='HISTORICAL',status='complete_with_scope',evidence_status='C02_EXACT_NATIVE_AND_REAL_TASK_INTERFACE_CHECKED',depends_on=[],related_records=[TASK,RID],full_sources=[BASE+n for n in ['SESSION.md','RUNS.json','CORE_COGNITION_AUDIT.md']])
    docs={p:edit.load(ROOT,p) for p in ['MEMORY.md','方向追踪.md','全景视野.md','扩展认知.md']};mp='MEMORY/001 - 当前执行队列.md';old=docs['MEMORY.md']['shards'][mp].split('## 用户当前专题（2026-09-19）\n\n',1)[1].split('\n\n## 既有项目队列',1)[0];edit.replace_in_shard(docs['MEMORY.md'],mp,old,message)
    edit.append_to_shard(docs['MEMORY.md'],'MEMORY/003 - 当前验证状态与顺序日志.md',f'\n{SID}：C335–339源/run08/index及subject094b7216闭合；实际有限原索引交付、真实cut/链桥、一般I边界。Book producer仍SOURCE，R13内缩条件入MS05；R09/全部非叶/偏差/封存未完。revision{rev}。\n')
    for p,kind,rid in [('方向追踪.md','direction','I-DIRECTION-PORTFOLIO-20260912'),('全景视野.md','outcome','I-OUTCOME-PANORAMA-20260912')]:
        edit.replace_in_index(docs[p],'source_state_revision: 275',f'source_state_revision: {rev}');edit.replace_in_index(docs[p],f'projection_generation: 20260924-{kind}-275',f'projection_generation: 20260924-{kind}-{rev}');docs[p]['index_text']=docs[p]['index_text'].replace('MO3_C04_NATIVE_COMPLETE_WITH_SCOPE_ROUND_INCOMPLETE','MO3_C02_NATIVE_INTERFACE_COMPLETE_ROUND_INCOMPLETE');s['records'][rid].update(projection_generation=f'20260924-{kind}-{rev}',semantic_status='MO3_C02_NATIVE_INTERFACE_COMPLETE_ROUND_INCOMPLETE',scope='C02 exact real-cover output interface; Book producer source scope and R13 retained; R09/non-leaf/bias/seal obligations remain.')
    dp='方向追踪/002 - 治理与用户方向.md';docs['方向追踪.md']['shards'][dp]=re.sub(r'^\| `DIR-U-MO3-GOVERNED` .*$',f'| `DIR-U-MO3-GOVERNED` | 第三轮递归多尺度与针对性过程 | 用户Goal1.2、Goal6-MS01–06、KC2/40/44–48 | `ACTIVE / R09_R13_MS05_NEXT` | `THEORY_SCHEMA`, `THEORY_ECONOMY`, `PARADOX_DISCOVERY` | `OUT-MO3-C01-STAGE-COLIMIT`, `OUT-MO3-MS04-CONTROLS`, `OUT-MO3-C04-BOUQUET-ORDER`, `OUT-MO3-C02-FINITE-COVER` | 组合侧条件/全部非叶、偏差回归、封存 | {REPORT}；revision{rev} |',docs['方向追踪.md']['shards'][dp],flags=re.M)
    edit.append_to_shard(docs['全景视野.md'],'全景视野/002 - 治理、门禁与骨架结果.md',f'\n| `OUT-MO3-C02-FINITE-COVER` | 真实覆盖到有限原索引 | `DIR-U-MO3-GOVERNED` | C335–339/source/run08/index及subject094b7216 | `FORMAL_CHECKED_WITH_SCOPE / NATIVE_INTERFACE_NORMAL_AND_BOUNDARY` | Nat可另找列表，一般I强统一接口另有边界；真cut/链桥已核 | 不是无条件compactness/物理或HoTT失配；保计算警告、R13及producer来源身份 | {PROCESS}；{REPORT}；revision{rev} |\n')
    pp='全景视野/008 - 当前未完成.md';docs['全景视野.md']['shards'][pp]=re.sub(r'^17\. MO3-GOVERNED-A.*$','17. MO3-GOVERNED-A：MS01、C01、MS04指定控制、C04及C02输出接口有各自范围结果；R09/R13组合及producer条件、MS02其余语义单元、MS05全部非叶独立结案、专门偏差回归和MS06最终封存未完。三包不抵全域，不删Book输入条件或计算边界。',docs['全景视野.md']['shards'][pp],flags=re.M)
    rows=[]
    for d in docs.values():rows+=edit.payload_rows(d,ROOT)
    seen={x['path'] for x in rows}
    for p in rt.MUTABLE:
        if p in seen:continue
        content=(ROOT/p).read_text()
        if p==rt.STATE:content=rt.dump(s).decode()
        elif p.endswith(('FRONTIER.md','RESUME.md')):assert old in content;content=content.replace(old,message,1)
        rows.append(dict(path=p,expected_sha256=sha(p),text=content))
    a=edit.load(ROOT,AUDIT);legacy=['# '+SID+' 兼容完整审计','- identity: '+s['current_core']['generation']+' / 48 KC']+[l for l in a['index_text'].splitlines() if re.match(r'^- (core_change|direction_change|panorama_change|essay_change|update_decision|cross_conflicts|unresolved):',l)]+['分片语义原件：'+AUDIT+'；嵌套writer缺口保留。']+list(a['shards'].values());audit='\n\n'.join(legacy).rstrip()+'\n';assert rt._audit_v1_kc_rows(audit)==[f'KC-{i:06d}' for i in range(1,49)]
    session=f'# {SID}\n\n- host: codex-desktop\n- model: Astra（用户选择，不认证后端指纹）\n- tier: T3\n- role: RESEARCH_GENERATION / sole canonical integrator\n- load_receipt: {OWN}证据/W3-C02/source-read.json；新单元最高指示503行/KC47–48全文；STATE268全文及自身269–275已读差分，275受管后像无漂移。\n- status: C02_INTERFACE_COMPLETE_WITH_SCOPE / ROUND_INCOMPLETE\n- report: {REPORT}\n- semantic_audit: {AUDIT}\n- subject_commit: {v["subject_commit"]}\n- next: {nxt}\n- known_gap: G-V5-SESSION-AUDIT-SHARD-WRITE-GAP-001；旧Coq全registry错配非本包依赖。\n\n|element_usage|实际用途/边界|\n|---|---|\n|原文/最高指示|发现态先行，未以截断口号结束|\n|native几何/枚举/提取|原任务的真实列表与点覆盖，非仅泛P/采样|\n|source/runtime分层|保Book producer及indexed-match计算边界|\n|审计/原子writer|48KC和真实余项，嵌套分片原子缺口仍在|\n\nreflection=no-plan-change；实现细化保持原Done，R13为既有遗漏入口纳入下一对账。T01/04/11/13/22/24/26更新实物与状态；需求/全局方法/配置/schema/运维不改，其余组无变化。无Sub Agent、新Session、push/tag、core或历史原件修改。\n'
    runs=dict(schema_version='hott-session-runs/v1',session_id=SID,new_math_claims=[f'C-{i}' for i in range(335,340)],proof_id='MP-MO3-FINITE-COVER-001',primary_run=RUN+'RUN.json',native_run_scope='Main attempts01-08, rational-cut BRIDGE-01 and WrongTouching CONTROL-01; exact files retained in formal run root.',validation=OWN+'证据/W3-C02/validation-001/RESULT.json',version_check=OWN+'证据/W3-C02/version-check/RESULT.json',software_run=OWN+'证据/W3-C02/software-replay-001/RUN.json',scope='Exact output interface and controls; source compactness producers not replayed; no qualified HoTT mismatch.')
    rows += [dict(path=BASE+n,expected_sha256=None,text=t) for n,t in [('SESSION.md',session),('RUNS.json',rt.dump(runs).decode()),('CORE_COGNITION_AUDIT.md',audit)]]
    payload=dict(schema_version='cognition-checkpoint/v1',session_id=SID,load_profile='research',task_ids=[TASK],authorization='沿用户已恢复MO3唯一integrator、研究proof与精确checkpoint授权，保存C02实际范围并保R09/R13/非叶/偏差/封存全部义务。',files=rows);(HERE/'checkpoint-payload.json').write_bytes(rt.dump(payload));res=rt.checkpoint(ROOT,plan['snapshot'],payload,apply=args.apply);(HERE/('checkpoint-apply.json' if args.apply else 'checkpoint-dry-run.json')).write_bytes(rt.dump(res));print(json.dumps({k:v for k,v in res.items() if k!='paths'},ensure_ascii=False))
if __name__=='__main__':main()
