#!/usr/bin/env python3
"""Canonical R13 write-back; preserve source-proof and parent-work boundaries."""
from pathlib import Path
import argparse,hashlib,importlib.util,json,re,sys
ROOT=Path(__file__).resolve().parents[4];HERE=Path(__file__).resolve().parent
OWN='第三轮机器统观/Session-A/';TASK='MO3-GOVERNED-A';RID='R-MO3-R13-OPEN-MARGIN-20260924'
SID='S-RES-20260924-MO3-A-R13';BASE=f'.codex/research/hott/sessions/{SID}/'
REPORT=OWN+'执行记录/010 - 开区间余量的生成与核证.md';PROCESS=OWN+'过程与结果/004 - 开区间整体与严格内缩覆盖.md';AUDIT=OWN+'审计/W3-R13/CORE_COGNITION_AUDIT.md'
RUN='HoTT/verification/runs/20260924-MO3-OPEN-COVER-MARGIN-001-01/';F='HoTT/formal/mo3/finite-cover/'
def sha(p):return hashlib.sha256((ROOT/p).read_bytes()).hexdigest()
def main():
    ap=argparse.ArgumentParser();ap.add_argument('--apply',action='store_true');args=ap.parse_args()
    spec=importlib.util.spec_from_file_location('rt',ROOT/'.codex/tools/cognition_runtime.py');rt=importlib.util.module_from_spec(spec);spec.loader.exec_module(rt);sys.path.insert(0,str(ROOT/'scripts/audit'));import projection_edit as edit
    s=json.loads((ROOT/rt.STATE).read_text());assert s['revision']==276 and SID not in s['records'] and RID not in s['records']
    h=json.loads((ROOT/rt.HEAD).read_text());assert all(sha(p)==v for p,v in h['tracked'].items())
    methods=json.loads((HERE.parent/'MS01/method-inputs/MANIFEST.json').read_text());assert all(sha(x['source'])==x['sha256'] for x in methods['rows'])
    v=json.loads((HERE/'version-check/RESULT.json').read_text());assert v['subject_commit']=='9a367c48eb31be2e1a2e187d1eb41a3a38bdb9d8' and v['checks'][0]['exit']==0
    checks=json.loads((HERE/'validation-001/RESULT.json').read_text());assert all(x['exit']==0 for x in checks['commands'][:2]) and not checks['builtin_drift'] and checks['wrong_margin_expected_rejection']
    rt.query_record(ROOT,TASK);plan=rt.plan(ROOT,profile='research',task_ids=[TASK]);assert set(plan['review_required'])<={TASK} and not plan['hydration_diagnostics']['query_first_promoted'];(HERE/'checkpoint-plan.json').write_bytes(rt.dump(plan))
    ev=[PROCESS]+[F+n for n in ['OpenCoverMargins.agda','OpenCoverMargins.md','OPEN-MARGINS-DEPENDENCY-AUDIT.json','IntervalCover.agda','RationalCuts.agda','CutRealLayer.agda','CutInfra.agda']]+[RUN+n for n in ['RUN.json','source-manifest.json','index-row-manifest.json']]+[OWN+'证据/W3-R13/version-check/RESULT.json']
    s['records'][RID]=dict(kind='result',path=PROCESS,lifecycle_status='CLOSED',status='R13_MARGIN_BOUNDARY_COMPLETE_WITH_SOURCE_SCOPE',evidence_status='FORMAL_CHECKED_WITH_SCOPE / SELECTED_PACKAGES_VERSION_CLOSED / BOOK_PROOF_NOT_REPLAYED / REALITY_MISMATCH_NOT_ESTABLISHED',depends_on=[],related_records=[TASK,'R-MO3-C02-FINITE-COVER-20260924'],full_sources=ev,source_hashes={p:sha(p) for p in ev},proof_id='MP-MO3-OPEN-COVER-MARGIN-001',claim_ids=['C-340','C-341'],subject_commit=v['subject_commit'],scope='Exact Inner family on actual Dedekind cuts: pointwise open coverage without any finite subcover, and one-member strict-inner closed-target control. Not a full Book inductive-cover HIT replay/refutation or a same-task repair/physical mismatch. Source proof detail remains qualified in MS05.')
    r=s['records'][TASK];r['depends_on'].append(RID);r['dependency_semantics']='verification_staleness';r.update(status='R13_SCOPED_BOUNDARY_COMPLETE_R09_MS05_NEXT',evidence_status='C327_TO_C341_SCOPED_NATIVE_RESULTS / MS04_EXECUTED / NONLEAF_BIAS_SEAL_REMAINDER / ROUND_INCOMPLETE',full_sources=['goal-6.md','goal-5.md',REPORT,AUDIT])
    pins=[REPORT,AUDIT,OWN+'覆盖与关系/004 - 语义单元与联合条件.md',OWN+'证据/W3-R13/source-read.json'];r['source_hashes'].update({p:sha(p) for p in pins});r['revalidation']='R13 newly consumed after full503-line Highest Directive/KC47-48 reload. Actual Inner whole-open negative and strict-inner positive native results with source/target distinctions; source compactness proof not upgraded. Own coverage004 updated, remaining R09/all non-leaf/bias/seal obligations preserved.'
    r['scope']='Full Goal5 v1.2/Goal6: C01/C04/C02 interfaces plus R13 margin boundary checked with scope; MS04 real regrouping and finite controls executed. R09 and every remaining MS02/MS05 non-leaf question, source-producer qualification, dedicated bias regression and MS06 final seal remain.'
    rev=s['revision']+1;s['revision']=rev;s['latest_session']=SID
    message=f'MO3 R13已在9a367c48版本闭合C340–341：同一严格内区间族逐点覆盖整个开区间但无有限全覆盖；预给严格内缩闭目标有单成员正控制。保目标变化、Book HIT/一般证明未重放，不报HoTT现实失配。下一R09与全部MS02/MS05非叶，再专门偏差回归/MS06。ROUND_INCOMPLETE；revision{rev}。'
    nxt='Review exact directed/QTT substitution side conditions for R09, then complete every accepted MS02/MS05 non-leaf question with its own evidence/scope/remainder/parent impact. Preserve R13 strict-margin/whole-open distinction and Book proof-detail limit, C02 producer versus consumer, and uninstantiated R05 feedback. Execute dedicated bias regression, full Goal5/6 completion audit and MS06 seal only after all mandatory work; do not extend already answered interval families.'
    s['execution_control'].update(current_phase='MO3_W3_R09_AND_MS05',status='MO3_ACTIVE_ROUND_INCOMPLETE',next_minimal_verification=nxt,last_checkpoint_session=SID,checkpoint_result=f'.codex/cognition/checkpoints/{SID}/result.json',app_goal_completion_eligible=False,app_goal_status_observed='active');s['projection']['status']='MO3_R13_MARGIN_BOUNDARY / R09_MS05_NEXT / ROUND_INCOMPLETE'
    s['records'][SID]=dict(kind='session',path=BASE+'SESSION.md',lifecycle_status='HISTORICAL',status='complete_with_scope',evidence_status='R13_EXACT_POINTWISE_MARGIN_BOUNDARY',depends_on=[],related_records=[TASK,RID],full_sources=[BASE+n for n in ['SESSION.md','RUNS.json','CORE_COGNITION_AUDIT.md']])
    docs={p:edit.load(ROOT,p) for p in ['MEMORY.md','方向追踪.md','全景视野.md','扩展认知.md']};mp='MEMORY/001 - 当前执行队列.md';old=docs['MEMORY.md']['shards'][mp].split('## 用户当前专题（2026-09-19）\n\n',1)[1].split('\n\n## 既有项目队列',1)[0];edit.replace_in_shard(docs['MEMORY.md'],mp,old,message)
    edit.append_to_shard(docs['MEMORY.md'],'MEMORY/003 - 当前验证状态与顺序日志.md',f'\n{SID}：R13严格余量边界C340–341/source/primary01/index及9a367c48版本闭合；Book lemma保条件，pointwise反对照不推翻全定理。R09/全部非叶/偏差/封存继续；revision{rev}。\n')
    for p,kind,rid in [('方向追踪.md','direction','I-DIRECTION-PORTFOLIO-20260912'),('全景视野.md','outcome','I-OUTCOME-PANORAMA-20260912')]:
        edit.replace_in_index(docs[p],'source_state_revision: 276',f'source_state_revision: {rev}');edit.replace_in_index(docs[p],f'projection_generation: 20260924-{kind}-276',f'projection_generation: 20260924-{kind}-{rev}');docs[p]['index_text']=docs[p]['index_text'].replace('MO3_C02_NATIVE_INTERFACE_COMPLETE_ROUND_INCOMPLETE','MO3_R13_MARGIN_BOUNDARY_ROUND_INCOMPLETE');s['records'][rid].update(projection_generation=f'20260924-{kind}-{rev}',semantic_status='MO3_R13_MARGIN_BOUNDARY_ROUND_INCOMPLETE',scope='R13 exact pointwise margin control, source proof remains qualified; R09/non-leaf/bias/seal incomplete.')
    dp='方向追踪/002 - 治理与用户方向.md';docs['方向追踪.md']['shards'][dp]=re.sub(r'^\| `DIR-U-MO3-GOVERNED` .*$',f'| `DIR-U-MO3-GOVERNED` | 第三轮递归多尺度与针对性过程 | 用户Goal1.2、Goal6-MS01–06、KC2/40/44–48 | `ACTIVE / R09_MS05_NEXT` | `THEORY_SCHEMA`, `THEORY_ECONOMY`, `PARADOX_DISCOVERY` | `OUT-MO3-C01-STAGE-COLIMIT`, `OUT-MO3-MS04-CONTROLS`, `OUT-MO3-C04-BOUQUET-ORDER`, `OUT-MO3-C02-FINITE-COVER`, `OUT-MO3-R13-MARGIN` | 替换条件/全部非叶，偏差回归与封存 | {REPORT}；revision{rev} |',docs['方向追踪.md']['shards'][dp],flags=re.M)
    edit.append_to_shard(docs['全景视野.md'],'全景视野/002 - 治理、门禁与骨架结果.md',f'\n| `OUT-MO3-R13-MARGIN` | 整开区间与严格内缩覆盖 | `DIR-U-MO3-GOVERNED` | C340–341/primary01及subject9a367c48 | `FORMAL_CHECKED_WITH_SCOPE / MARGIN_BOUNDARY` | 有限表与目标余量需共同保留，正常控制不替whole-open | 非Book全HIT或定理反证，非物理/HoTT失配；R09及非叶未全结 | {PROCESS}；{REPORT}；revision{rev} |\n')
    pp='全景视野/008 - 当前未完成.md';docs['全景视野.md']['shards'][pp]=re.sub(r'^17\. MO3-GOVERNED-A.*$','17. MO3-GOVERNED-A：MS01、三主题native接口、MS04指定控制及R13余量边界完成各自范围；R09替换合同、MS02/MS05全部非叶独立对账、专门偏差回归及MS06未完。保Book producer/HIT未重放、计算边界和R05未实例化反馈，不用局部结果抵全轮。',docs['全景视野.md']['shards'][pp],flags=re.M)
    rows=[]
    for d in docs.values():rows+=edit.payload_rows(d,ROOT)
    seen={x['path'] for x in rows}
    for p in rt.MUTABLE:
        if p in seen:continue
        content=(ROOT/p).read_text()
        if p==rt.STATE:content=rt.dump(s).decode()
        elif p.endswith(('FRONTIER.md','RESUME.md')):assert old in content;content=content.replace(old,message,1)
        rows.append(dict(path=p,expected_sha256=sha(p),text=content))
    a=edit.load(ROOT,AUDIT);audit='\n\n'.join(['# '+SID+' 兼容完整审计','- identity: '+s['current_core']['generation']+' / 48 KC']+[l for l in a['index_text'].splitlines() if re.match(r'^- (core_change|direction_change|panorama_change|essay_change|update_decision|cross_conflicts|unresolved):',l)]+['分片语义原件：'+AUDIT+'；嵌套writer缺口保留。']+list(a['shards'].values())).rstrip()+'\n';assert rt._audit_v1_kc_rows(audit)==[f'KC-{i:06d}' for i in range(1,49)]
    session=f'# {SID}\n\n- host: codex-desktop\n- model: Astra（用户选择，不认证后端指纹）\n- tier: T3\n- role: RESEARCH_GENERATION / sole canonical integrator\n- load_receipt: {OWN}证据/W3-R13/source-read.json；最高指示503行/KC47–48本单元全文；STATE268全文及自身269–276差分，276受管后像无漂移。\n- status: R13_COMPLETE_WITH_SCOPE / ROUND_INCOMPLETE\n- report: {REPORT}\n- semantic_audit: {AUDIT}\n- subject_commit: {v["subject_commit"]}\n- next: {nxt}\n- known_gap: G-V5-SESSION-AUDIT-SHARD-WRITE-GAP-001；旧Coq全registry错配非本包依赖。\n\n|element_usage|实际用途/边界|\n|---|---|\n|原文/最高指示|源组合条件生成，非先判理论错误|\n|native真实cut|任意有限表漏点与保余量控制，非有限采样|\n|source/native分层|Book全HIT/证明未重放，不以局部升级|\n|canonical审计|48KC/current queue，不伪造嵌套原子化|\n\nreflection=no-plan-change。T01/04/11/13/22/24/26更新实物/状态；需求、全局方法、配置、schema、运维不改，其余组无差分。无Sub Agent、新Session、push/tag、core或历史原件改写。\n'
    runs=dict(schema_version='hott-session-runs/v1',session_id=SID,new_math_claims=['C-340','C-341'],proof_id='MP-MO3-OPEN-COVER-MARGIN-001',primary_run=RUN+'RUN.json',control='HoTT/verification/runs/20260924-MO3-OPEN-COVER-MARGIN-CONTROL-01/RUN.json',validation=OWN+'证据/W3-R13/validation-001/RESULT.json',version_check=OWN+'证据/W3-R13/version-check/RESULT.json',scope='Pointwise margin boundary; Book proof not replayed; no reality mismatch.')
    rows += [dict(path=BASE+n,expected_sha256=None,text=t) for n,t in [('SESSION.md',session),('RUNS.json',rt.dump(runs).decode()),('CORE_COGNITION_AUDIT.md',audit)]]
    payload=dict(schema_version='cognition-checkpoint/v1',session_id=SID,load_profile='research',task_ids=[TASK],authorization='沿用户已恢复MO3唯一integrator和本轮精确写回授权，记录R13真实结果并保全部余项。',files=rows);(HERE/'checkpoint-payload.json').write_bytes(rt.dump(payload));res=rt.checkpoint(ROOT,plan['snapshot'],payload,apply=args.apply);(HERE/('checkpoint-apply.json' if args.apply else 'checkpoint-dry-run.json')).write_bytes(rt.dump(res));print(json.dumps({k:v for k,v in res.items() if k!='paths'},ensure_ascii=False))
if __name__=='__main__':main()
