#!/usr/bin/env python3
"""Generate the types of n-truncated semi-simplicial types, one closed Agda
term per level n (Claude, session 7f138325, 2026-09-26; CG001-C-62).

Why this exists: the open problem of homotopy type theory is to define, inside
the theory, one family  F : N -> U  with F(n) the type of tuples (A0, ..., An)
of semi-simplicial types (Kraus 2021, sec. 4; Annenkov-Capriotti-Kraus-Sattler,
MSCS; Kolomatskaia-Shulman, MSCS 2025, who describe every attempt as leading
"once again to an infinite regress").  For every *externally fixed* n the type
is writable.  This program is such an external generator: an ordinary program
that, for each concrete n, prints the level-n type as Agda text.  Agda then
checks each printed level.  The generator runs outside the theory; that is the
point of the contrast, and nothing here claims the internal family exists or
does not exist.

Indexed presentation.  A face of the standard m-simplex is a nonempty proper
subset U of {0..m}; its variable is x<digits of U>.  The family A_m takes one
argument per proper nonempty subset of {0..m}, in canonical order (by size,
then lexicographic), and the variable for U has type A_{|U|-1} applied to the
variables of the proper nonempty subsets of U in the same canonical order.
Level m therefore has 2^(m+1) - 2 face arguments.

Usage:
  python3 -B gen_sst.py <max_level> > SSTLevels.agda
The output is deterministic.
"""
from __future__ import annotations

import sys
from itertools import combinations


def proper_nonempty_subsets(vertices: tuple[int, ...]) -> list[tuple[int, ...]]:
    return [c for size in range(1, len(vertices)) for c in combinations(vertices, size)]


def var(subset: tuple[int, ...]) -> str:
    return "x" + "".join(str(i) for i in subset)


def face_type(subset: tuple[int, ...]) -> str:
    level = len(subset) - 1
    args = [var(v) for v in proper_nonempty_subsets(subset)]
    return " ".join([f"A{level}", *args])


def family_type(m: int) -> str:
    """The type of A_m, written with A_0 .. A_{m-1} in scope."""
    faces = proper_nonempty_subsets(tuple(range(m + 1)))
    if not faces:
        return "Type"
    binders = " ".join(f"({var(u)} : {face_type(u)})" for u in faces)
    return f"{binders} → Type"


def face_count(m: int) -> int:
    return len(proper_nonempty_subsets(tuple(range(m + 1))))


def level_type(n: int) -> str:
    parts = [f"Σ[ A{m} ∈ ({family_type(m)}) ]" for m in range(n + 1)]
    return " ".join(parts) + " Unit"


def main() -> int:
    if len(sys.argv) != 2 or not sys.argv[1].isdigit():
        print(__doc__, file=sys.stderr)
        return 2
    top = int(sys.argv[1])
    out = [
        "{-# OPTIONS --safe --cubical --guardedness #-}",
        "{-",
        "  GENERATED by gen_sst.py (CG001-C-62).  Do not edit by hand.",
        "",
        "  proof id : MP-CG001-SST-FINITE-LEVELS-001",
        "  claim    : CG001-C-62 (full statement in CLAIM.md)",
        "",
        f"  For each n from 0 to {top}, SST≤n is the type of n-truncated",
        "  semi-simplicial types in the indexed presentation.  Each level is one",
        "  closed term written out by an external program for that concrete n.",
        "  Kernel acceptance shows every printed level is a well-formed type; it",
        "  says nothing about a single internal family over all n.",
        "",
        "  Face arguments of the level-m family (2^(m+1) - 2):",
        *[f"    level {m}: {face_count(m)}" for m in range(top + 1)],
        "-}",
        "module SSTLevels where",
        "",
        "open import Cubical.Foundations.Prelude",
        "open import Cubical.Data.Sigma",
        "open import Cubical.Data.Unit",
        "",
    ]
    for n in range(top + 1):
        out += [f"SST≤{n} : Type₁", f"SST≤{n} = {level_type(n)}", ""]
    out += [
        "-- A trivial inhabitant at every level, so each type is shown nonempty:",
        "-- the terminal semi-simplicial type, all of whose levels are Unit.",
        "",
    ]
    for n in range(top + 1):
        fields = []
        for m in range(n + 1):
            k = face_count(m)
            fields.append("Unit" if k == 0 else "(λ " + " ".join(["_"] * k) + " → Unit)")
        term = " , ".join(fields) + " , tt"
        out += [f"terminal≤{n} : SST≤{n}", f"terminal≤{n} = {term}", ""]
    sys.stdout.write("\n".join(out))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
