#!/usr/bin/env bash
# Linux replays of the Opus runs behind the "ghost of Zeno" line (A7, infinite coherence),
# captured 2026-09-27 for the community-audit document
# docs/社区审计提交/01-芝诺悖论的幽灵.md.  Proof ids and claim ids are Opus's (CG-001 goal
# index); the original macOS receipts 20260926-CG001-* are left untouched.
# Idempotent per run id (the capture tools refuse an existing run directory).
set -u
cd "$(dirname "$0")/../.."
C="python3 -B Cloud-Opus审计并补完GLM/tools/capture_copus_run.py"
L="python3 -B Cloud-Opus审计并补完GLM/tools/capture_copus_lean_run.py"
O=HoTT/formal/claude-cg001
W=$O/wild-sst
NOTE="Linux replay (Agda v2.8.0 Linux asset, cubical v0.9 byte-identical) of the Opus run of 2026-09-26 with the same include root; the original receipt is left untouched."
LNOTE="Linux replay (Lean 4.34.0 Linux release asset, same source commit 293d5d0c as the macOS toolchain) of the Opus run of 2026-09-26; the CG-001 driver lean_check.py is used unchanged."

$C --run-id 20260927-COPUS-REPLAY-CG001-SST-FINITE-LEVELS-01 --proof-id MP-CG001-SST-FINITE-LEVELS-001 --claim-id CG001-C-62 \
  --source $O/sst-finite-levels/SSTLevels.agda --manifest-file $O/sst-finite-levels/gen_sst.py --manifest-file $O/sst-finite-levels/CLAIM.md --expect ACCEPT \
  --scope "Replay of 20260926-CG001-SST-FINITE-LEVELS-01: SST≤0 … SST≤5 (types of n-truncated semi-simplicial types in indexed form, printed by the external generator gen_sst.py) and their terminal inhabitants are accepted." \
  --non-goal "Neither proves nor refutes an internal family F : ℕ → U (open problem); the generator runs outside the theory" --audit-note "$NOTE"
$C --run-id 20260927-COPUS-REPLAY-CG001-SST-FINITE-LEVELS-NEG-01 --proof-id MP-CG001-SST-FINITE-LEVELS-NEG-001 --claim-id CG001-C-62 \
  --source $O/sst-finite-levels/WrongFace.agda --manifest-file $O/sst-finite-levels/CLAIM.md --expect REJECT \
  --scope "Replay of 20260926-CG001-SST-FINITE-LEVELS-NEG-01: a face x013 built from the wrong edge x12 is rejected." --audit-note "$NOTE"

$C --run-id 20260927-COPUS-REPLAY-CG001-WILD-SST-01 --proof-id MP-CG001-WILD-SST-001 --claim-id CG001-C-64 \
  --source $W/WildSST.agda --manifest-file $W/CLAIM.md --expect ACCEPT \
  --scope "Replay of 20260926-CG001-WILD-SST-01: WildSST (points, face maps, semi-simplicial identities) and the hexagon Coh₂; setsCohere; the circle instance spin satisfies every face identity but routeA winds once and routeB twice (by refl), hence spinIncoherent : ¬ Coh₂ spin." \
  --non-goal "Does not prove semi-simplicial types undefinable; one instance, one index triple" --audit-note "$NOTE"
$C --run-id 20260927-COPUS-REPLAY-CG001-WILD-SST-NEG-01 --proof-id MP-CG001-WILD-SST-NEG-001 --claim-id CG001-C-64 \
  --source $W/WrongSpinCoherent.agda --manifest-file $W/WildSST.agda --manifest-file $W/CLAIM.md --expect REJECT \
  --scope "Replay of 20260926-CG001-WILD-SST-NEG-01: claiming that routeA also winds twice is rejected." --audit-note "$NOTE"

$C --run-id 20260927-COPUS-REPLAY-CG001-WILD-SST2-01 --proof-id MP-CG001-WILD-SST2-001 --claim-id CG001-C-66 \
  --source $W/WildSST2.agda --manifest-file $W/WildSST.agda --manifest-file $W/CLAIM-C66.md --manifest-file $W/p4_faces.py --manifest-file $W/p4_faces.out.txt --expect ACCEPT \
  --scope "Replay of 20260926-CG001-WILD-SST2-01: surf ≢ refl via the Hopf family (winding −1 by refl); on flat the all-refl and the σr hexagon fillings differ (twoFillings); Deg₃ holds for the first and fails for the second." \
  --non-goal "The reduction of the general P₄ coherence to Deg₃ is hand-derived (later replaced by C-68)" --audit-note "$NOTE"
$C --run-id 20260927-COPUS-REPLAY-CG001-WILD-SST2-NEG-01 --proof-id MP-CG001-WILD-SST2-NEG-001 --claim-id CG001-C-66 \
  --source $W/WrongSurfTrivial.agda --manifest-file $W/WildSST2.agda --manifest-file $W/WildSST.agda --manifest-file $W/CLAIM-C66.md --expect REJECT \
  --scope "Replay of 20260926-CG001-WILD-SST2-NEG-01: claiming that transport along surf has winding 0 is rejected." --audit-note "$NOTE"

$C --run-id 20260927-COPUS-REPLAY-CG001-WILD-SST-P4-01 --proof-id MP-CG001-WILD-SST-P4-001 --claim-id CG001-C-68 \
  --source $W/WildSSTP4Flat.agda --manifest-file $W/WildSSTP4.agda --manifest-file $W/WildSST.agda --manifest-file $W/WildSST2.agda --manifest-file $W/gen_p4.py --manifest-file $W/P4_STRUCTURE.txt --manifest-file $W/CLAIM-C68.md --expect ACCEPT \
  --scope "Replay of 20260926-CG001-WILD-SST-P4-01: the general second-level coherence Coh₃ (permutohedron P₄, generated by gen_p4.py); on flat, notCoh₃ : ¬ Coh₃ flatSurfᵢ and coh₃Trivial : Coh₃ flatTrivialᵢ." \
  --non-goal "Equivalence of Coh₃ with other formulations is not machine-checked; does not prove semi-simplicial types undefinable" --audit-note "$NOTE"
$C --run-id 20260927-COPUS-REPLAY-CG001-WILD-SST-P4-NEG-01 --proof-id MP-CG001-WILD-SST-P4-NEG-001 --claim-id CG001-C-68 \
  --source $W/WrongSurfMoveTrivial.agda --manifest-file $W/WildSSTP4Flat.agda --manifest-file $W/WildSSTP4.agda --manifest-file $W/WildSST.agda --manifest-file $W/WildSST2.agda --manifest-file $W/CLAIM-C68.md --expect REJECT \
  --scope "Replay of 20260926-CG001-WILD-SST-P4-NEG-01: treating the first step (the σr face) as trivial is rejected." --audit-note "$NOTE"

$C --run-id 20260927-COPUS-REPLAY-CG001-WINDING-COCYCLE-01 --proof-id MP-CG001-WINDING-COCYCLE-001 --claim-id CG001-C-69 \
  --source $W/WindingCocycle.agda --manifest-file $W/WildSST.agda --manifest-file $W/p3_routes.py --manifest-file $W/p3_routes.out.txt --manifest-file $W/CLAIM-C69.md --expect ACCEPT \
  --scope "Replay of 20260926-CG001-WINDING-COCYCLE-01: on circle-valued structures windingSST w, Coh₂ ⇔ the winding cocycle equation (coh₂→cocycle, cocycle→coh₂); spinW and levelW incoherent, uniformW coherent." \
  --non-goal "Only for this family of structures; p3_routes.py is a combinatorial check, not a proof" --audit-note "$NOTE"
$C --run-id 20260927-COPUS-REPLAY-CG001-WINDING-COCYCLE-NEG-01 --proof-id MP-CG001-WINDING-COCYCLE-NEG-001 --claim-id CG001-C-69 \
  --source $W/WrongSpinWCocycle.agda --manifest-file $W/WindingCocycle.agda --manifest-file $W/WildSST.agda --manifest-file $W/CLAIM-C69.md --expect REJECT \
  --scope "Replay of 20260926-CG001-WINDING-COCYCLE-NEG-01: the cocycle equation for spinW at (0,0,0) is rejected (1 != 2)." --audit-note "$NOTE"

$C --run-id 20260927-COPUS-REPLAY-CG001-WILD-SST-LEVELS-01 --proof-id MP-CG001-WILD-SST-LEVELS-001 --claim-id CG001-C-70 \
  --source $W/WildSSTP4Levels.agda --manifest-file $W/WildSSTP4.agda --manifest-file $W/WildSST.agda --manifest-file $W/WildSST2.agda --manifest-file $W/CLAIM-C70.md --expect ACCEPT \
  --scope "Replay of 20260926-CG001-WILD-SST-LEVELS-01: sets ⇒ Coh₂ᵢ; groupoids ⇒ Coh₂ᵢ is a proposition and Coh₃ holds for every hexagon datum; on the circle-valued flat shape the hexagon datum is unique and satisfies Coh₃." \
  --non-goal "The general 't+1' law is a meta-level argument, not machine-checked" --audit-note "$NOTE"
$C --run-id 20260927-COPUS-REPLAY-CG001-WILD-SST-LEVELS-NEG-01 --proof-id MP-CG001-WILD-SST-LEVELS-NEG-001 --claim-id CG001-C-70 \
  --source $W/WrongS2Groupoid.agda --manifest-file $W/WildSSTP4Levels.agda --manifest-file $W/WildSSTP4Flat.agda --manifest-file $W/WildSSTP4.agda --manifest-file $W/WildSST.agda --manifest-file $W/WildSST2.agda --manifest-file $W/CLAIM-C70.md --expect REJECT \
  --scope "Replay of 20260926-CG001-WILD-SST-LEVELS-NEG-01: using the groupoid proof for S¹ on S² is rejected." --audit-note "$NOTE"

$C --run-id 20260927-COPUS-REPLAY-CG001-SELF-INTERPRETATION-01 --proof-id MP-CG001-SELF-INTERPRETATION-001 --claim-id CG001-C-67 \
  --source $O/self-interpretation/SelfInterpretation.agda --manifest-file $O/self-interpretation/CLAIM.md --expect ACCEPT \
  --scope "Replay of 20260926-CG001-SELF-INTERPRETATION-01: the toy syntax with one equation swap: untruncated, a faithful interpretation into the universe exists (faithful∞) and the syntax is not a set; truncated to a set, it interprets into hProp but noFaithfulForFacts." \
  --non-goal "A miniature of the obstacle, not a model of type theory; see REVISIONS.md for the narrowed reading" --audit-note "$NOTE"
$C --run-id 20260927-COPUS-REPLAY-CG001-SELF-INTERPRETATION-NEG-01 --proof-id MP-CG001-SELF-INTERPRETATION-NEG-001 --claim-id CG001-C-67 \
  --source $O/self-interpretation/WrongFlipIsIdentity.agda --manifest-file $O/self-interpretation/SelfInterpretation.agda --manifest-file $O/self-interpretation/CLAIM.md --expect REJECT \
  --scope "Replay of 20260926-CG001-SELF-INTERPRETATION-NEG-01: claiming that transport along the flip keeps first is rejected." --audit-note "$NOTE"

$L --run-id 20260927-COPUS-REPLAY-CG001-WILD-SST-LEAN-01 --proof-id MP-CG001-WILD-SST-LEAN-001 --claim-id CG001-C-65 \
  --source $O/wild-sst-lean/WildSSTUIP.lean --leanchecker --manifest-file $O/wild-sst-lean/CLAIM.md --expect ACCEPT \
  --scope "Replay of 20260926-CG001-WILD-SST-LEAN-01: the same one-line definition in Lean 4 (UIP): theorem coh2 (S : WildSST) : Coh2 S := fun _ _ _ _ _ _ _ => rfl, no axioms." \
  --non-goal "A statement in a type theory with UIP, used as a contrast; not a HoTT statement" --audit-note "$LNOTE"
$L --run-id 20260927-COPUS-REPLAY-CG001-WILD-SST-LEAN-NEG-01 --proof-id MP-CG001-WILD-SST-LEAN-NEG-001 --claim-id CG001-C-65 \
  --source $O/wild-sst-lean/WildSSTUIP.lean --source $O/wild-sst-lean/WrongRoute.lean --manifest-file $O/wild-sst-lean/CLAIM.md --expect REJECT \
  --scope "Replay of 20260926-CG001-WILD-SST-LEAN-NEG-01: routeA with the order of the last face maps reversed is rejected in the target file." --audit-note "$LNOTE"
