#!/usr/bin/env python3
"""Checkpoint P33 coverage and move the active leaf from P2 to P1."""
from __future__ import annotations
import argparse,hashlib,importlib.util,json,re,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];OUT=Path(__file__).resolve().parent;SID='S-RES-20260922-ASTRA-P33-2LTT-COVERAGE';BASE=f'.codex/research/hott/sessions/{SID}/';PLAN='R-HOTT-FOUR-TRACK-PLAN-20260921';P32='R-P32-HOTT-SPECIFIC-REFLECTION-CONSUMER-DISCOVERY-20260921';P33='R-P33-2LTT-V5-SELF-METATHEORY-BOUNDARY-AUDIT-20260922';DIR='audit/p33-2ltt-v5-self-metatheory-boundary-audit-20260922';SOURCES=(f'{DIR}/P33-2LTT-V5-SELF-METATHEORY-BOUNDARY-AUDIT-REPORT.md',f'{DIR}/P33-2LTT-V5-SOURCE-FREEZE.json',f'{DIR}/verify_p33_2ltt_v5_self_metatheory_boundary_audit.py',f'{DIR}/P33-2LTT-V5-SELF-METATHEORY-BOUNDARY-AUDIT-VERIFICATION.json')
def h(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def rt():
 s=importlib.util.spec_from_file_location('r',ROOT/'.codex/tools/cognition_runtime.py');assert s and s.loader;m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return m
def ed():sys.path.insert(0,str(ROOT/'scripts/audit'));import projection_edit;return projection_edit
def audit(core):
 rows=re.findall(r'^### (KC-\d+) · .*? · (.+)$',(ROOT/'核心认知.md').read_text(),re.M);assert len(rows)==46;deep={'KC-000004','KC-000005','KC-000010','KC-000014','KC-000015','KC-000019','KC-000021','KC-000022','KC-000031','KC-000034','KC-000035','KC-000037','KC-000038','KC-000039','KC-000040','KC-000041','KC-000042','KC-000043','KC-000044','KC-000045','KC-000046'};x=f'# {SID} 核心认知回评\n\n{core["generation"]}；46 条；兼容单文件审计登记 `G-V5-SESSION-AUDIT-SHARD-WRITE-GAP-001`。\n\n- core_change: NO\n- direction_change: P33 existing coverage closed; P34 P1 origin relation discovery next.\n- panorama_change: v5 2LTT boundary reused without rerun.\n- essay_change: NO\n- update_decision: exit P2 reflection source chain; return to original X/P1.\n- cross_conflicts: no HoTT defect, actual K, or reality bridge established.\n- unresolved: P34 relation discovery and P3 actual K ingress.\n- writer_compatibility: G-V5-SESSION-AUDIT-SHARD-WRITE-GAP-001.\n\n| KC | 主题 | relation | 本单元判断 | 证据、反证条件 |\n|---|---|---|---|---|\n';
 for kc,title in rows:
  rel='DEEPENED' if kc in deep else 'NOT_TOUCHED';a='P33按覆盖裁决回到原X/P1，不把2LTT边界当最终命中。' if rel=='DEEPENED' else '本单元未直接检验该用户原文。';x+=f'| `{kc}` | {title} | `{rel}` | {a} | P33 report；P34 relation discovery可更新。 |\n'
 return x+'\n## 波次定位\n\nP33由既有2LTT assets覆盖，P2 gate不通过；当前叶切换P1，避免反射来源路径依赖。\n'
def main():
 ap=argparse.ArgumentParser();ap.add_argument('--apply',action='store_true');a=ap.parse_args();r=rt();e=ed();assert all((ROOT/x).is_file() for x in SOURCES);assert json.loads((ROOT/SOURCES[-1]).read_text())['status']=='PASS_WITH_SCOPE';st=json.loads((ROOT/r.STATE).read_text());assert st['revision']==249 and st['latest_session']=='S-RES-20260921-ASTRA-P32-HOTT-SPECIFIC-DISCOVERY';hd=json.loads((ROOT/r.HEAD).read_text());assert all(h(ROOT/p)==v for p,v in hd['tracked'].items());pl=r.plan(ROOT,profile='research',task_ids=[PLAN]);(OUT/'P33-CHECKPOINT-PLAN.json').write_bytes(r.dump(pl));st['revision']=250;st['latest_session']=SID
 p=st['records'][PLAN];p['related_records']=list(dict.fromkeys(p.get('related_records',[])+[P33,SID]));p['status']='four_track_p2_reflection_coverage_closed_p1_origin_relation_discovery_next';p['evidence_status']='P1_MINIMAL_EXPRESSIBILITY_POSITIVE_CONTROL / P2_REFLECTION_SUBLINE_CLOSED_BY_EXACT_COVERAGE / P3_PAUSED_SAME_CLASS / P4_NOT_TRIGGERED / P33_2LTT_V5_COVERAGE_CLOSED / P34_P1_ORIGIN_RELATION_DISCOVERY_NEXT / GOAL_ACTIVE';p['full_sources']=list(dict.fromkeys(p.get('full_sources',[])+list(SOURCES)));p['source_hashes'].update({x:h(ROOT/x) for x in p['full_sources'] if (ROOT/x).is_file()});p['revalidation']=p.get('revalidation','')+' Revision250 records P33 v5 exact coverage, closes P2 reflection subline and selects P34 P1 relation discovery.'
 st['records'][P33]={'kind':'result','path':SOURCES[0],'lifecycle_status':'CURRENT','evidence_status':'CLOSE_WITH_SCOPE / EXISTING_2LTT_BOUNDARY_AND_KERNEL_CONTROL_REUSED / V5_PRIMARY_RELEVANT_SCOPE_CONFIRMED / P2_GATE_NOT_PASSED / P34_P1_ORIGIN_RELATION_DISCOVERY_SELECTED / NO_NEW_HOTT_DEFECT_CLAIM','status':'complete_with_scope','depends_on':[],'related_records':[PLAN,P32,SID],'full_sources':list(SOURCES),'source_hashes':{x:h(ROOT/x) for x in SOURCES},'scope':'Current primary locator plus exact local coverage; no rerun, 2LTT theorem, HoTT defect, actual consumer or reality-task conclusion.'};st['records'][SID]={'kind':'session','path':BASE+'SESSION.md','lifecycle_status':'HISTORICAL','evidence_status':'P33_CHECKPOINTED_WITH_SCOPE','status':'complete_with_scope','depends_on':[],'related_records':[PLAN,P32,P33],'full_sources':[BASE+x for x in ('SESSION.md','RUNS.json','CORE_COGNITION_AUDIT.md')]}
 st['execution_control'].update({'status':'FOUR_TRACK_P2_REFLECTION_COVERAGE_CLOSED_P1_ORIGIN_RELATION_DISCOVERY_NEXT','current_phase':'PHASE_2_P33_COVERAGE_CLOSED_P34_P1_ORIGIN_RELATION_DISCOVERY_NEXT','second_phase_status':'P1_ACTIVE_P2_REFLECTION_CLOSED_P3_PAUSED_P4_NOT_TRIGGERED_P34_NEXT','last_checkpoint_session':SID,'checkpoint_result':f'.codex/cognition/checkpoints/{SID}/result.json','next_minimal_verification':'P34-P1-ORIGIN-RELATION-DISCOVERY-001. Starting from fixed R_min/P6/P7/P19-P21 assets, conduct local/historical and bounded primary-source reconnaissance for an unreviewed origin-operation-recovery sensitive mathematical relation or invariant. Freeze original X, operations, observation and Done; compare candidate frameworks point-by-point to existing RichCurve/OriginDirectedDiagram coverage. Select only a candidate that can reduce an unclosed P1 obligation; do not call enriched structure itself a HoTT defect or reopen P3 without actual K.'});st['projection']['status']='FOUR_TRACK_P2_REFLECTION_COVERAGE_CLOSED / P1_ORIGIN_RELATION_DISCOVERY_NEXT / P3_PAUSED / P4_NOT_TRIGGERED / GOAL_ACTIVE / NO_NEW_HOTT_DEFECT_CLAIM'
 mem=e.load(ROOT,'MEMORY.md');dire=e.load(ROOT,'方向追踪.md');pan=e.load(ROOT,'全景视野.md');essay=e.load(ROOT,'扩展认知.md')
 e.replace_in_shard(mem,'MEMORY/001 - 当前执行队列.md','P32 已完成双条件HoTT-specific来源发现：官方问题、2LTT、HoTT-Agda/Cubical与h-prop reflection均未给同层actual consumer；下一=P33审计2LTT v5严格outer-layer边界。P3/P1/P4/Guard继续停放。入口：`audit/p32-hott-specific-reflection-consumer-discovery-20260921/P32-HOTT-SPECIFIC-REFLECTION-CONSUMER-DISCOVERY-REPORT.md`；revision249。','P33 已核对当前2LTT v5与既有本地机器/边界资产：相关内容已覆盖且不通过P2 root gate；下一=P34，回到P1寻找未覆盖的来源—操作—复原数学关系。P3仍等待实际K，P4未触发。入口：`audit/p33-2ltt-v5-self-metatheory-boundary-audit-20260922/P33-2LTT-V5-SELF-METATHEORY-BOUNDARY-AUDIT-REPORT.md`；revision250。');e.append_to_shard(mem,'MEMORY/003 - 当前验证状态与顺序日志.md','\nS-RES-20260922-ASTRA-P33-2LTT-COVERAGE：v5 2LTT boundary由既有assets精确覆盖，P2 gate不通过；P34 P1 origin relation discovery next；revision250。\n')
 e.replace_in_index(dire,'source_state_revision: 249','source_state_revision: 250');e.replace_in_index(dire,'projection_generation: 20260921-direction-249','projection_generation: 20260922-direction-250');e.replace_in_index(dire,'semantic_status: FOUR_TRACK_P32_NO_QUALIFIED_CONSUMER_P33_2LTT_V5_NEXT','semantic_status: FOUR_TRACK_P33_COVERAGE_CLOSED_P34_P1_ORIGIN_RELATION_NEXT');e.replace_in_shard(dire,'方向追踪/002 - 治理与用户方向.md','| `DIR-U-HOTT-FOUR-TRACK` | P32：HoTT-specific双条件来源发现 | P31/P32 | `P33_2LTT_V5_BOUNDARY_AUDIT_NEXT / GOAL_ACTIVE` | `PARADOX_DISCOVERY` | `OUT-HOTT-FOUR-TRACK-PLAN` | scope内无合格consumer；审计2LTT outer-layer边界 | P32 report；revision249 |','| `DIR-U-HOTT-FOUR-TRACK` | P33：2LTT v5边界覆盖裁决 | P32/P33 | `P34_P1_ORIGIN_RELATION_DISCOVERY_NEXT / GOAL_ACTIVE` | `PARADOX_DISCOVERY` | `OUT-HOTT-FOUR-TRACK-PLAN` | P2反射边界已覆盖，回到原X/P1 | P33 report；revision250 |');e.replace_in_shard(dire,'方向追踪/002 - 治理与用户方向.md','| `DIR-U-ABX-ORIGINAL-CIRCLE` | ABX 原圆环 P3 实际消费者分支停放 | P21/P32 | `P3_PAUSED / P33_2LTT_BOUNDARY` | `EVIDENCE_DISCIPLINE` | `OUT-ABX-ACTION-INTAKE` | 仅新版本固定实际 K 或强 R 才重开 | P21/P32 reports；revision249 |','| `DIR-U-ABX-ORIGINAL-CIRCLE` | ABX 原圆环 P3 实际消费者分支停放 | P21/P33 | `P3_PAUSED / P34_P1_RELATION_DISCOVERY` | `EVIDENCE_DISCIPLINE` | `OUT-ABX-ACTION-INTAKE` | 仅新版本固定实际 K 或强 R 才重开 | P21/P33 reports；revision250 |')
 e.replace_in_index(pan,'source_state_revision: 249','source_state_revision: 250');e.replace_in_index(pan,'projection_generation: 20260921-outcome-249','projection_generation: 20260922-outcome-250');e.replace_in_index(pan,'semantic_status: FOUR_TRACK_P32_NO_QUALIFIED_CONSUMER_P33_2LTT_V5_NEXT','semantic_status: FOUR_TRACK_P33_COVERAGE_CLOSED_P34_P1_ORIGIN_RELATION_NEXT');e.replace_in_shard(pan,'全景视野/003 - 当前机器证明包与原生重放.md','| `OUT-HOTT-FOUR-TRACK-PLAN` | P32 HoTT-specific双条件来源发现 | `DIR-U-HOTT-FOUR-TRACK` | P31/P32 | `P32_SCOPED / P33_NEXT` | scope内无actual consumer；2LTT是边界而非命中 | 不证明HoTT缺陷 | P32 report；revision249 |','| `OUT-HOTT-FOUR-TRACK-PLAN` | P33 2LTT v5边界覆盖裁决 | `DIR-U-HOTT-FOUR-TRACK` | P32/P33 | `P33_COVERAGE_CLOSED / P34_NEXT` | 已有条件边界不连原X，回到P1 | 不证明HoTT缺陷 | P33 report；revision250 |');e.replace_in_shard(pan,'全景视野/003 - 当前机器证明包与原生重放.md','| `OUT-ABX-ACTION-INTAKE` | ABX P3停放，独立 P32已完成来源发现 | `DIR-U-ABX-ORIGINAL-CIRCLE` | P15/P17/P19/P20/P22/P25/P26/P27/P28/P29/P30/P31/P32 | `P3_PAUSED / P33_2LTT_BOUNDARY` | 避免重复，保留新实际K重开条件 | 不证明原M/N桥 | P21/P32 reports；revision249 |','| `OUT-ABX-ACTION-INTAKE` | ABX P3停放，P33回到P1 | `DIR-U-ABX-ORIGINAL-CIRCLE` | P15/P17/P19/P20/P22/P25/P26/P27/P28/P29/P30/P31/P32/P33 | `P3_PAUSED / P34_P1_RELATION_DISCOVERY` | 避免重复，保留新实际K重开条件 | 不证明原M/N桥 | P21/P33 reports；revision250 |');e.append_to_shard(pan,'全景视野/006 - ERCF-3 与 T3 脉冲及失败台账.md','\n## P33：2LTT v5边界覆盖裁决（revision250）\n\nv5相关边界已由本地2LTT theorem control/crisp防线覆盖，不能连接原X或K；P2反射子线关闭，P34回到P1。\n');e.append_to_shard(pan,'全景视野/008 - 当前未完成.md','\n16. `P34-P1-ORIGIN-RELATION-DISCOVERY-001`：从R_min/P6/P7/P19等资产出发，选择未覆盖的来源—操作—复原数学关系或不变量。\n')
 simple={x:(ROOT/x).read_text() for x in r.MUTABLE if x not in {r.STATE,'MEMORY.md','方向追踪.md','全景视野.md','扩展认知.md'}};simple[r.PREFIX+'FRONTIER.md']=simple[r.PREFIX+'FRONTIER.md'].replace('- P32严格来源发现没有找到同时具HoTT身份与actual self-reflection consumer的资产；2LTT v5提供outer-layer边界，P33需全文核对。入口：`audit/p32-hott-specific-reflection-consumer-discovery-20260921/P32-HOTT-SPECIFIC-REFLECTION-CONSUMER-DISCOVERY-REPORT.md`。','- P33确认2LTT v5相关边界已由既有机器/来源资产覆盖且不连原X；P34回到P1寻找来源—操作—复原数学关系。入口：`audit/p33-2ltt-v5-self-metatheory-boundary-audit-20260922/P33-2LTT-V5-SELF-METATHEORY-BOUNDARY-AUDIT-REPORT.md`。',1);simple[r.PREFIX+'RESUME.md']=simple[r.PREFIX+'RESUME.md'].replace('当前 active goal 在P32后继续：严格双条件来源发现没有得到actual HoTT self-reflection consumer；P33全文审计2LTT v5的inner/outer边界及其与O1–O6的关系。不要重审P3/P1最小接口/跨后端/Guard停放分支。入口：`audit/p32-hott-specific-reflection-consumer-discovery-20260921/P32-HOTT-SPECIFIC-REFLECTION-CONSUMER-DISCOVERY-REPORT.md`；revision249。','当前 active goal 在P33后回到P1：2LTT v5相关边界已被本地原文/机器控制覆盖，且不提供原X/O6桥。P34发现未覆盖的来源—操作—复原数学关系；P3等待实际K、P4未触发。入口：`audit/p33-2ltt-v5-self-metatheory-boundary-audit-20260922/P33-2LTT-V5-SELF-METATHEORY-BOUNDARY-AUDIT-REPORT.md`；revision250。',1)
 rows=[]
 for d in (mem,dire,pan,essay):rows+=e.payload_rows(d,ROOT)
 seen={x['path'] for x in rows}
 for rel in r.MUTABLE:
  if rel not in seen:rows.append({'path':rel,'expected_sha256':h(ROOT/rel),'text':r.dump(st).decode() if rel==r.STATE else simple[rel]})
 session=f'# {SID}\n\n- host: codex-desktop\n- model: runtime-model-not-certified-by-tool\n- tier: T3\n- status: `P33_COVERAGE_CLOSED / P34_P1_ORIGIN_RELATION_DISCOVERY_NEXT / NO_NEW_HOTT_DEFECT_CLAIM`\n- load_receipt: research plan snapshot `{pl["snapshot"]}`; current v5 primary sections, local 2LTT sources and prior kernel receipt reviewed.\n- authorization: 用户已授权按 goal-3 持续推进、公开/本地侦察和 checkpoint；不启动 Sub Agent、不 push、不发布。\n';runs={'schema_version':'hott-session-runs/v1','session_id':SID,'primary_runs':[{'kind':'P33 coverage verifier','result':'PASS_WITH_SCOPE'}],'new_math_claims':[],'new_kernel_replay':False};rows += [{'path':BASE+'SESSION.md','expected_sha256':None,'text':session},{'path':BASE+'RUNS.json','expected_sha256':None,'text':r.dump(runs).decode()},{'path':BASE+'CORE_COGNITION_AUDIT.md','expected_sha256':None,'text':audit(st['current_core'])}]
 payload={'schema_version':'cognition-checkpoint/v1','session_id':SID,'load_profile':'research','task_ids':[PLAN],'authorization':'用户已授权按goal-3持续推进、公开/本地侦察和checkpoint；不启动Sub Agent、不push、不发布。','files':rows};(OUT/'P33-CHECKPOINT-PAYLOAD.json').write_bytes(r.dump(payload));res=r.checkpoint(ROOT,pl['snapshot'],payload,apply=a.apply);(OUT/('P33-CHECKPOINT-APPLY.json' if a.apply else 'P33-CHECKPOINT-DRY-RUN.json')).write_bytes(r.dump(res));print(json.dumps({k:v for k,v in res.items() if k!='paths'},ensure_ascii=False,indent=2))
if __name__=='__main__':main()
